### ISSUE TITLE
No 'for' property set in the datetime html

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2715] opened 2016-04-29 19:52 UTC
Causes testing to fail in #2714 

Currently, with two fields, the html is
```html
<div class="FormField field-type-datetime">...</div>
<div class="FormField field-type-datetime">...</div>
```
whereas it needs to be 
```html
<div class="FormField field-type-datetime" for="fieldA">...</div>
<div class="FormField field-type-datetime" for="fieldB">...</div>
```

Without this, when checking for the fieldB stuff, the testing goes into the first div it matches, which is for fieldA, and then everything fails. 

I was thinking the PR would fail the CI checks, but presumably CI is not currently checking datetime. If this PR is merged as is, all future checks will fail.

**Comment by mxstbr** [comment] 2016-04-30 07:50
That sounds reasonable. Is that a blocker for #2714, and does it only happen for the datetime field?

**Comment by jstockwin** [comment] 2016-04-30 08:01
It only happens for the datetime field, but the current testing practise adds a model with a name and two datetime fields, fieldA and fieldB. FieldA is initial, and fieldB is not. 

This means on the view where fieldB is checked, there should be two datetime fields on the same page, thus causing an error due to not having a for field. 

So yes it's a blocker for #2714, but it also only happens for the datetime field. I could change the datetime testing to not include fieldB tests for now, but that's inconsistent with the other tests. 

I hope that's clear

**Comment by mxstbr** [comment] 2016-04-30 08:06
That's a perfectly clear explanation, thanks! The problem is that I don't really want to tinker with the admin interface itself right now, since #2566 is still WIP, will be merged soon and won't have those updates.

What do you think we should do? Can this wait?

**Comment by jstockwin** [comment] 2016-04-30 08:15
This is all for work on #2291. I'd probably defer to @webteckie for a definitive answer on where to go, but personally I would do the following:

I could make a new PR which only concerns itself with FieldA for now. I'd say that's a good temporary solution, as it still does some testing on the datetime field, while circumventing this issue. Then when this issue is closed, we can add fieldB back into the testing.

**Comment by jstockwin** [comment] 2016-04-30 08:46
@mxstbr what's the best way of doing this temp fix? Should I comment out the lines relating to fieldB, and comment that they are pending this issue being resolved, or should I remove the lines altogether to keep the code clean?

**Comment by mxstbr** [comment] 2016-04-30 10:41
Comment them out for now, it'd be weird to then have to duplicate the work afterwards. :+1:

**Comment by webteckie** [comment] 2016-04-30 11:59
@mxstbr a fix for this should not conflict with your branch since it would probably be a change in the field rendering, right?   In any case, we really do not want to step in your toes and can wait if it worries you :-)

**Comment by mxstbr** [comment] 2016-04-30 12:14
Well not really, since we'd need to render the field with a `for` property which I don't think we do at the moment, but maybe I'm missing something here...

**Closed** 2016-05-11 06:02 UTC
Labels: bug
