### ISSUE TITLE
4.0.0-beta5 MongoError: Pool Destroyed - Mongo replica set

### ISSUE THREAD

**Issue by dani190** [keystonejs/keystone#4225] opened 2017-04-20 03:18 UTC
I seem to be having an issue only on 4.0.0-beta5. So far this issue does not appear to happen on 4.0.0-beta4.

My app seems to work fine but when switching between the admin UI and my other pages, eventually I will get the following error in my console:

```
Error thrown for request: /
MongoError: pool destroyed
    at Pool.write (/var/www/node_modules/mongodb-core/lib/connection/pool.js:880:12)
    at Cursor._find (/var/www/node_modules/mongodb-core/lib/cursor.js:287:22)
    at nextFunction (/var/www/node_modules/mongodb-core/lib/cursor.js:585:10)
    at Cursor.next [as _next] (/var/www/node_modules/mongodb-core/lib/cursor.js:693:3)
    at nextObject (/var/www/node_modules/keystone/node_modules/mongodb/lib/cursor.js:671:8)
    at Cursor.next (/var/www/node_modules/keystone/node_modules/mongodb/lib/cursor.js:261:12)
    at findOne (/var/www/node_modules/keystone/node_modules/mongodb/lib/collection.js:1404:10)
    at Collection.findOne (/var/www/node_modules/keystone/node_modules/mongodb/lib/collection.js:1390:44)
    at tryCatcher (/var/www/node_modules/bluebird/js/release/util.js:16:23)
    at ret [as findOneAsync] (eval at <anonymous> (/var/www/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at /var/www/node_modules/connect-mongo/src/index.js:195:48
    at tryCatcher (/var/www/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/var/www/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/var/www/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/var/www/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I have attempted to upgrade MongoDB and Node to the latest versions as well as all packages without any luck.

MongoDB - 3.4.3
Node -7.9.0

MongoDB replica set configured with 5 members

**Comment by dani190** [comment] 2017-04-21 14:10
So far the only way I seem to be able to resolve this is to run beta 3 with my replica set. In development beta 5 works fine but dev doesn't have a replica set configured.

Any help is appreciated. Looks like I will need to stick with beta 3 for now as even beta 4 has an issue where pages refuse to load (Also reported in the issue tracker).

**Comment by dani190** [comment] 2017-05-26 02:37
The fix for this was to update mongoose to the latest version within the keystone.js app.
I just ended up making a local copy and modified this.

This should be noted so it can be fixed in future updates.

**Comment by dani190** [comment] 2017-10-26 18:57
I just checked and don't see Mongoose updated yet.
Any word on when this can be updated?

**Comment by dani190** [comment] 2017-11-01 22:03
FYI, this is still happening in beta 7. I had to downgrade to get my app working again with replica sets

**Comment by dani190** [comment] 2018-06-25 13:41
@stennie I just checked and it doesn't look like I am using a back ported version of KeystoneJS any more. I do have mongoose set to the latest version in my package.json file. I have not seen the pool destroyed error in a long time.

**Comment by stennie** [comment] 2018-06-29 06:11
@dani190 I'll close this issue since it no longer appears to be reproducible. 

If you have a moment, it would still be helpful to confirm the specific version of Mongoose you are using now. 

Thanks,
Stennie

**Closed by stennie** 2018-06-29 06:11 UTC
Labels: 4.0-release-candidate, bug

**Comment by dani190** [comment] 2018-06-29 14:17
I am showing that I am on 5.1.7
