### ISSUE TITLE
Pagination Bug in 4.0.0-beta.5

### ISSUE THREAD

**Issue by woodytang** [keystonejs/keystone#4468] opened 2017-10-18 00:46 UTC
http://demo.keystonejs.com/blog/yy
check this demo;

I encountered the exact same problem as the pagination object can not return a correct total page;

it seems 

		if (locals.data.category) {
			q.where('categories').in([locals.data.category]);
		
		}
where doesn't really work here:(

**Comment by linuxenko** [comment] 2018-04-21 17:44
I've the same problem with wrong amount of total pages. It seems like it counts them without any conditions. 

For example http://demo.keystonejs.com/blog/news  , there is only 6 records, but pagination shows about 10 pages. If I open the http://demo.keystonejs.com/blog/news?page=9 for example, it will show the blank page.

**Comment by stennie** [comment] 2018-06-01 22:34
Closing a duplicate of #4056.

**Closed by stennie** 2018-06-01 22:34 UTC
Labels: bug
