### ISSUE TITLE
Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by angjelo** [keystonejs/keystone#1942] opened 2015-12-09 02:22 UTC
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

KeystoneJS Configuration Error:

Please provide a `cookie secret` value for session encryption.

I changed the path , but nothing worked ... I updated everything that I had to.
I guess something is messed up in the installation process ... If anyone has a suggestion or a complete guide that I need to follow to install keystone feel free to send it !

**Comment by ericelliott** [comment] 2015-12-09 02:27
Thanks!

I think this is a duplicate of [this open issue](https://github.com/keystonejs/keystone/issues/1752). It's fixed in the 0.4.x line. I think it may be unlikely that we'll see a 0.3.x fix. If this is indeed a duplicate, feel free to close this one, since it's already being tracked.

**Comment by morenoh149** [comment] 2015-12-27 23:46
closing as dupe of #1752

**Closed by morenoh149** 2015-12-27 23:46 UTC
