### ISSUE TITLE
Wrong z-index for dropdown in a document field

### ISSUE THREAD

**Issue by Chaptykov** [keystonejs/keystone#6157] opened 2021-07-21 21:16 UTC
# Bug report

## Describe the bug

Dropdown list appears under a form footer. 

## To Reproduce

1. Add document field
2. Hover „More formatting“

## Expected behaviour

Dropdown list appears above UI. 

## Screenshots

![image](https://user-images.githubusercontent.com/1920602/126560885-9fe6aad7-8e3f-439f-b53c-20c12b1f12cd.png)

## System information

- OS: OS X
- Browser: Chrome

**Comment by bladey** [comment] 2021-07-22 00:14
Thanks @Chaptykov!

**Comment by dcousens** [comment] 2022-05-23 22:26
(An earlier) Duplicate of https://github.com/keystonejs/keystone/issues/7395

**Closed by dcousens** 2022-05-23 22:26 UTC
