### ISSUE TITLE
sortable cloudinaryImages

### ISSUE THREAD

**Issue by pangorgo** [keystonejs/keystone#2019] opened 2015-12-28 13:34 UTC
What do you think about drag&drop sorting of cloudinaryImages field type?
I personally miss sorting feature on galleries a lot, and would like to work on that if there is green light for such enhancement.

**Comment by mxstbr** [comment] 2016-04-29 14:54
Duplicate of #1060, see https://productpains.com/post/keystonejs/allow-reordering-of-cloudinaryimages!

**Closed by mxstbr** 2016-04-29 14:54 UTC

**Comment by n-lavrenko** [comment] 2017-06-11 17:35
+1
