### ISSUE TITLE
Enable Google's Geocoding API for auto-detect fix

### ISSUE THREAD

**Issue by hatzipanis** [keystonejs/keystone#1608] opened 2015-08-23 23:26 UTC
I'm not sure if this is new but Google has a Geocoding API that, when enabled, solved an auto-detecting issue I was having in both the backend and my front-end. 

Regarding the auto-detect feature the Keystone docs state `To enable these features, obtain an API Key from Google and enable the Google Maps v3 and Google Places APIs for it` with no word of the Geocoding API. According to the Geocoding API docs `This service is also available as part of the Google Maps JavaScript API` but I have always had the two recommended API's enabled and they were when this stopped working. Enabling the Geocoding API fixed that.

Are we doing something differently now? Did anyone else notice auto-detect stop working for them?

**Comment by jordanyim1** [comment] 2015-11-24 13:52
Hi, you might have the same error as me - https://github.com/keystonejs/keystone/issues/1864

**Comment by morenoh149** [comment] 2015-11-30 19:44
closing as duplicate of #1864

**Closed by morenoh149** 2015-11-30 19:44 UTC
