### ISSUE TITLE
In admin UI, if validation fails, the page is still refreshed and data is lost

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone#2386] opened 2016-03-08 13:00 UTC
The page reloads even if validation is false to display the flash message, but does not pass any of the validated data to the newly loaded page.

Either validated fields should be autopopulated from validated data if a field is invalid, or the page should not reload.

I want to look in to this further to see what method will work best with the code.

**Comment by morenoh149** [comment] 2016-03-08 15:36
yeah the page is probably still performing a submit. If the page simply validated before allowing a submit that would fix things.

**Comment by webteckie** [comment] 2016-03-08 18:16
@Noviny this is a duplicate of #2239  This should get addressed once the Admin UI becomes a SPA (soon).  Please close this ticket, if you agree it's the same issue.

**Closed** 2016-03-08 22:16 UTC
