### ISSUE TITLE
about filesupload

### ISSUE THREAD

**Issue by janryWang** [keystonejs/keystone#1298] opened 2015-04-11 12:44 UTC
when I use the files upload function , and I can not delete the file, When I print the req.body object, it will show me the "remove:,,,". 
I found the cause of the problem.
https://github.com/keystonejs/keystone/blob/master/fields/types/localfiles/LocalFilesField.js#L163
https://github.com/keystonejs/keystone/blob/master/fields/types/localfiles/LocalFilesField.js#L165
https://github.com/keystonejs/keystone/blob/master/fields/types/localfiles/LocalFilesType.js#L385
According to this modification can fix this issue below.

```
if (!(/^(delete|reset)$/.test(method)) || !ids) return; //delete---> remove

if (thumb && thumb.props.deleted) remove.push(thumb.props.public_id);//public_id---->id

```

**Comment by creynders** [comment] 2015-04-23 07:15
Not entirely clear what the fix is, are you saying this:

```js
if (thumb && thumb.props.deleted) remove.push(thumb.props.public_id);
```

Should be replaced with:

```
if (thumb && thumb.props.deleted) remove.push(thumb.props.id);
```

**Comment by mxstbr** [comment] 2016-04-29 11:53
This is duplicate of #162!

**Closed by mxstbr** 2016-04-29 11:53 UTC
Labels: bug
