### ISSUE TITLE
[v0.3]Cloudinary image album delete not working

### ISSUE THREAD

**Issue by waqas19921** [keystonejs/keystone#2957] opened 2016-05-27 04:31 UTC
i have used cloudinary images field in model as

`image: { type: Types.CloudinaryImages, autoCleanup : true}`

everything works fine but it will not delete images from cloudinary account upon delete from admin UI

**Comment by ddaddy** [comment] 2016-06-07 09:42
Just bumping this.
Would love to see the autoCleanup of `CloudinaryImages` work the same way as it does for `CloudinaryImage`

**Comment by mxstbr** [comment] 2016-06-07 10:46
Duplicate of #162, maybe?

**Comment by ddaddy** [comment] 2016-06-07 10:51
I'm not so sure it's a duplicate. #162 talks about letting the adminUI prompt to cleanup.
`CloudinaryImage` & `CloudinaryImages` already have the `autoCleanup` option, it just hasn't been fully implemented for the multiple version `CloudinaryImages`. It works great with the singular `CloudinaryImage`

The `autoCleanup` option allows it to work from anywhere and not just the Admin UI.

**Comment by mxstbr** [comment] 2016-06-07 10:53
Ah, right, I understand the problem now! Yeah, that's definitely a bug. We'll be reworking the storage fields entirely for 0.4, so that'll hopefully get fixed when we do that!

**Comment by Noviny** [comment] 2017-10-04 13:53
Closing this as we are no longer working to update 0.3

**Closed by Noviny** 2017-10-04 13:53 UTC
Labels: bug
