### ISSUE TITLE
require: true in save method isn't work

### ISSUE THREAD

**Issue by kamontat** [keystonejs/keystone#4645] opened 2018-05-31 08:42 UTC
### Expected behavior

SOME ERROR link `image not found`, or `link not found`

### Actual/Current behavior

(err = null) and model save **correctly**

### Steps to reproduce the actual/current behavior

1. change some model 
```js
Banner.add({
	name: {
		type: Types.Text,
		initial: true,
	},
	image: {
		type: Types.Url,
		require: true,
		initial: true,
	},
	link: {
		type: Types.Url,
		require: true,
		initial: true,
	},
	order: {
		type: Types.Select,
		default: 0,
		initial: true,
		numeric: true,
		options: [{
			value: 1,
			label: 'First',
		}, {
			value: 2,
			label: 'Second',
		}, {
			value: 3,
			label: 'Third',
		}, {
			value: 4,
			label: 'Fourth',
		}, {
			value: 5,
			label: 'Fifth',
		}, {
			value: 0,
			label: 'None',
		}],
		emptyOption: false,
	},
});
```
2. create new model
```js
const model = new Banner.model({});
```
3. save model
```js
model.save(err => {
	if (err) console.error(err);
	else console.log(model);
});
```
4.1 EXPECTED: SOME ERROR image not found, link not found
4.2 ACTUAL:   (err = null) and model save correctly

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0-beta.5
| Node             | v9.11.1

**Comment by stennie** [comment] 2018-05-31 08:59
@kamontat Keystone 4.0.0-beta.5 was released in Jan 2017. Can you please retest with 4.0.0-beta.8 and confirm if the issue is still reproducible?

Thanks,
Stennie

**Comment by kamontat** [comment] 2018-05-31 18:30
I already update the newest version, and the bug is still exist.

**Comment by stennie** [comment] 2018-05-31 23:09
@kamontat Great, thanks for confirming and including details to reproduce.

Regards,
Stennie

**Comment by stennie** [comment] 2018-06-03 09:37
@laurenskling Good catch! We're trying to clean up the backlog of Keystone issues to get 4.0 out, so any help greatly appreciated :).

@kamontat, your original model has `require:true` instead of `required:true` which is allowing you to save with those fields missing.

If you are using `name image` as the `autokey` and both values are null, the unique indexed value will also be null and result in the duplicate key error you've encountered. 

If you use the expected `required` attribute this should not be an issue. You'll also need to edit or remove any documents which have the expected fields missing.

Regards,
Stennie

**Closed by stennie** 2018-06-03 09:37 UTC
Labels: bug, needs reproduction
