### ISSUE TITLE
Error: Cannot find module 'reactify'

### ISSUE THREAD

**Issue by sendyhalim** [keystonejs/keystone#1332] opened 2015-04-23 01:51 UTC
Hi, I'm newbie in keystone and tried to run keystone, but I got error `Error: Cannot find module 'reactify'` on admin page.
- I checked the `node_modules/keystone/node_modules` from root of my project and it seems that reactify is not installed.
-  then I tried to `sudo npm install` and rebuild everything using `gulp build-scripts`, resulted in `Browserify error` -> `Error: Cannot find module './admin/src/app.js'` 

Tried with keystone version `0.3.6` and latest commit, `0.3.5` works fine.

**Comment by JedWatson** [comment] 2015-04-23 09:28
Hi @sendyhalim, thanks for the bug report.

My apologies - this is being caused by a browserify setting in package json that refers to a package that was removed from the dev process. I'll release a new version in a minute that has the fix in it.

**Comment by sendyhalim** [comment] 2015-04-23 09:31
@JedWatson Ohh I see. Thanks for the response :+1:

**Comment by JedWatson** [comment] 2015-04-23 09:45
I fixed this and pushed a new version `0.3.7`, should be fixed now. Let me know if you still experience the issue!

**Comment by sendyhalim** [comment] 2015-04-23 11:05
There's another error, `Uncaught Error: Cannot find module 'bytes'` when I'm on admin page (`EditForm.js`), it seems that `bytes` package is not included. 

I managed to fix this by adding `bytes` in `/admin/packages.js` then rebuild `gulp build-packages`. After that error still occured `Uncaught Error: Cannot find module '/node_modules/bytes/lib/byte-convert.js'`, so I dig in to `/node_modules/bytes/index.js` and tried to change:
```
var convertFunction = require(__dirname + '/lib/byte-convert.js');
var parseFunction = require(__dirname + '/lib/byte-parse.js');
```

to
 
```
var convertFunction = require('./lib/byte-convert.js');
var parseFunction = require('./lib/byte-parse.js');
```

then rebuild again `gulp build-packages` and now keystone running fine, so I think the problems are browserify cannot convert `__dirname` to relative and `admin/src/packages.js` need to include `bytes` package.

**Comment by orthes** [comment] 2015-04-23 11:18
Yes, the same problem here. I've updated to ```0.3.7``` and I see ```Uncaught Error: Cannot find module '/node_modules/keystone/node_modules/bytes/lib/byte-convert.js'``` error.

**Comment by JedWatson** [comment] 2015-04-23 12:58
I had the same experience and changed the paths manually myself before building the `packages.js` script for `0.3.7`. Not sure why it's throwing the `Uncaught Error: Cannot find module 'bytes'` error, that didn't show up in my testing :(

I'll run another test from a fresh install now I can download the update from npm and see what I can work out; I've also opened a PR on the `bytes.js` repo to fix the root problem here.

May also be able to downgrade to `< 2.0.0` of that package, since the breaking changes were introduced in a rewrite.

**Comment by JedWatson** [comment] 2015-04-23 13:51
I've rolled back the `bytes` package and included it in the common set (having realised why the local fix wasn't working...) so this will hopefully _never be a problem again_.

v0.3.8 has been published and seems to be fine.

**Closed by JedWatson** 2015-04-23 13:51 UTC

**Comment by orthes** [comment] 2015-04-23 14:31
:+1:

**Comment by sendyhalim** [comment] 2015-04-23 15:38
:100:
