### ISSUE TITLE
Custom /keystone admin path

### ISSUE THREAD

**Issue by digitalcraft** [keystonejs/keystone#370] opened 2014-05-18 08:34 UTC
Would be good to make it easier to change the admin url
'/admin'
'/cms'

Also I saw there was some options to change the main image on the keystone splash page from config's but it didn't work straight away so i ended up changing the template.

I've added a heap of security and auth stuff too, I saw someone asking about roles and stuff. I will send a few pull requests in a week or two I'm just balls deep in code atm and need to get it out the door.

Additionally I noticed that the implementation of google analytics wasn't the same on the keystone admin template and the public template (i don't remember specifics there, if it's not obvious I will do a PR for that too later on)

**Comment by digitalcraft** [comment] 2015-03-31 11:36
@RecoX I made a fork of the keystone project and made modifications there for white-label options. Sorry for not replying sooner.

Has there been any progress of getting this into master?

**Comment by dcousens** [comment] 2015-05-03 09:56
Duplicate of #627,  while this came first, #627 has more discussion.  Closing.

**Closed by dcousens** 2015-05-03 09:56 UTC
Labels: new feature

**Comment by namacious** [comment] 2018-01-26 09:41
Hello It's too simple to change the admin path. 

I have spend 2 days for that how do i change the admin path and it's just on config to set the admin 

`keystone.set('admin path' , "admin")`

Let me know if you need any help

**Comment by mitul69** [comment] 2018-01-26 09:43
Hello

It's too simple to change the admin path.
I have spend 2 days for that how do i change the admin path and it's just on config to set the admin

keystone.set('admin path' , "admin")
Let me know if you need any help

skype : patelmit69

**Comment by max8hine** [comment] 2018-03-09 06:03
@mitul69 it fixed the issues but will cause all the channels could not open error under Admin UI
