### ISSUE TITLE
Unknown plugin "transform-class-properties"

### ISSUE THREAD

**Issue by sylvainlap** [keystonejs/keystone#3223] opened 2016-07-27 14:34 UTC
### Steps to reproduce the behavior

Using a clone of https://github.com/keystonejs/keystone-test-project and its Keystone dependency on the current master branch. Navigate to /keystone.
### Expected behavior

No error :)
### Actual behavior

Keystone throws error.

```
$ npm start

> keystone-test@1.0.0 start D:\DEV\WORKSPACE\keystone-test-project
> node keystone.js

Application Mounted

------------------------------------------------
KeystoneJS Started:
Keystone Test is ready on port 3000
------------------------------------------------

Application Started
GET /keystone/signin 200 8.241 ms
2016-07-27 16:07:87 error building Signin/index.js:
Unknown plugin "transform-class-properties" specified in "D:\\DEV\\WORKSPACE\\keystone-test-project\\node_modules\\inline-style-prefixer\\package.json" at 0, attempted to resolve relative to "D:\\DEV\\WORKSPACE\\keystone-test-project\\node_modules\\inline-style-prefixer" while parsing file: D:\DEV\WORKSPACE\keystone-test-project\node_modules\inline-style-prefixer\static.js
```

**Comment by SharadKumar** [comment] 2016-07-28 11:30
Yes - this is reproducible on `master`. #3178

**Comment by SharadKumar** [comment] 2016-07-28 11:50
```
GET /admin/signin 200 8.746 ms
2016-07-28 21:07:45 error building Signin/index.js:
Unknown plugin "transform-class-properties" specified in "/Users/XYZ/GitHub/project/admin/node_modules/inline-style-prefixer/package.json" at 0, attempted to resolve relative to "/Users/XYZ/GitHub/project/admin/node_modules/inline-style-prefixer" while parsing file: /Users/XYZ/GitHub/project/admin/node_modules/inline-style-prefixer/static.js
```

**Comment by JedWatson** [comment] 2016-07-28 15:26
I can't reproduce this with a fresh checkout of master and a clean npm install. I'm running Keystone linked though. Can you both try `rm -rf node_modules && npm install` and see if you can still reproduce it?

**Comment by danielmahon** [comment] 2016-07-28 20:26
Same issue on latest `master` @4cb2d51

````
4:22:47 PM web.1 |  ------------------------------------------------
4:22:47 PM web.1 |  KeystoneJS Started:
4:22:47 PM web.1 |  redacted is ready on port 5000
4:22:47 PM web.1 |  ------------------------------------------------
4:22:50 PM web.1 |  GET /keystone/signin 200 6.168 ms
4:22:52 PM web.1 |  2016-07-28 16:07:45 error building Signin/index.js:
4:22:52 PM web.1 |  Unknown plugin "transform-class-properties" specified in "/Volumes/PROJECTS/Projects/redacted/node_modules/inline-style-prefixer/package.json" at 0, attempted to resolve relative to "/Volumes/PROJECTS/Projects/redacted/node_modules/inline-style-prefixer" while parsing file: /Volumes/PROJECTS/Projects/redacted/node_modules/inline-style-prefixer/static.js
````

**Comment by mxstbr** [comment] 2016-07-28 20:43
Which verison of npm are you on? (`$ npm -v`)

**Comment by danielmahon** [comment] 2016-07-28 20:44
node `v6.3.1`
npm `3.10.6`

**Comment by JedWatson** [comment] 2016-07-29 12:29
OK so we replicated this while deploying to a staging (linux) server today, with keystone (master) as a dependency in a project's package.json. Node 6.x, npm 3.x

I realised it's happening because babel has a plugin (`babel-plugin-transform-class-properties`) specified in the package.json of an Aphrodite dependency (`inline-style-prefixer`). This is _really_ weird, because babel should be ignoring everything in `node_modules` by default. Also, I still can't reproduce it locally (OS X, Node 6.3.1, npm 3.10.3)

I fixed it by ensuring Aphrodite is loaded from the common packages bundle (it should have been but there was a condition meaning it wasn't), which should make this symptom go away, but the underlying issues are:

* why on earth is Babel applying transforms in a package under node_modules?
* why on earth is it only happening in some environments?

@danielmahon @SharadKumar @sylvainlap can you confirm that the new updates to master fix this in your environments please? then we should really still try and get to the bottom of it.

**Comment by SharadKumar** [comment] 2016-07-29 13:17
Hi @JedWatson - clearing up `node_modules` and latest master worked fine. Thanks.

**Comment by JedWatson** [comment] 2016-07-29 14:06
Great, thanks for letting me know! Now to figure out what is up with Babel... that's concerning.

**Comment by PatrickJongmans** [comment] 2016-08-15 11:32
Related issue with 'inline-style-prefixer'

`GET /keystone/ 200 28.522 ms
2016-08-15 13:08:65 error building App/index.js:
Unknown plugin "add-module-exports" specified in .......
`

**Comment by dijs** [comment] 2016-08-16 03:46
@PatrickJongmans Getting the same thing.

**Comment by dijs** [comment] 2016-08-16 23:03
Versions:

Node: v6.2.0
Npm: 3.9.3

**Comment by w01fgang** [comment] 2016-08-20 21:36
@PatrickJongmans now there is another error in console of the browser and no UI renders
```
Uncaught Error: Cannot find module 'aphrodite/no-important'  packages.js:4
```
tested on MAC OS on fresh [keystone-test-project](https://github.com/keystonejs/keystone-test-project) with latest keystone from repo

**I have tried to understand whats wrong:**
When I run the project with `npm run dev` then change all `aphrodite/no-important` to `aphrodite` in  `node_modules/keystone/*`, I see the errors in the console
```
2016-08-20 22:08:90 error building FieldTypes:
Unknown plugin "add-module-exports" specified in "/private/tmp/keystone-test-project/node_modules/inline-style-prefixer/package.json" at 1, attempted to resolve relative to "/private/tmp/keystone-test-project/node_modules/inline-style-prefixer" while parsing file: /private/tmp/keystone-test-project/node_modules/inline-style-prefixer/static.js
```
then I install `babel-plugin-add-module-exports` and after changes there another error
```
2016-08-20 22:08:60 error building FieldTypes:
Couldn't find preset "stage-0" relative to directory "/private/tmp/keystone-test-project/node_modules/inline-style-prefixer" while parsing file: /private/tmp/keystone-test-project/node_modules/inline-style-prefixer/static.js
```
than I install needed presets
```
npm i babel-preset-stage-0
```
then I make another changes and finally I see
```
2016-08-20 23:08:18 rebuilt FieldTypes
2016-08-20 23:08:43 rebuilt Signin/index.js
2016-08-20 23:08:28 rebuilt App/index.js
```
and UI works again

**Comment by dijs** [comment] 2016-08-20 23:45
@w01fgang Yes, I am getting the same...

**Comment by DaTebe** [comment] 2017-06-10 13:29
I have a similar issue. If needed I'll open a new issue. But maybe some of you can help me?

`2017-06-10 15:06:39 error building Signin/index.js:`
`Unknown plugin "transform-runtime" specified in "/home/user/.babelrc" at 0, attempted to resolve relative to "/home/user" while parsing file: /home/user/projects/datebe/node_modules/object-assign/index.js`

Just a little background:
OS: Ubuntu
Node: 7.10.0
NPM: 5.0.3
I used the yeoman generator to create a new KeystoneJS Beta5 project. Creation went fine. Starting the project also works. Accessing the first page also works. But when I try to access the `keystone/signin` path the error appears. 

Kind regards,
Daniel

**Comment by w01fgang** [comment] 2017-06-10 15:55
@DaTebe It seems that `transform-runtime` plugin is not installed but does exist in `.babelrc`

you need to install `babel-plugin-transform-runtime`

**Comment by DaTebe** [comment] 2017-06-10 16:16
I've already tried to install it in my Project. I'll try to install it globally.

**Comment by mmick66** [comment] 2017-07-14 12:10
I had the same error, unrelated to Keystone, so in case it will help anyone, here is what fixed it...

I was using the Babel transpiler and noticed that my `~/.babelrc` had the "transform-class-properties" dependency specified. So, I created a local `myproject/.babelrc` with only `{ "presets": ["env"] }` inside. 

It worked after that!

**Comment by Noviny** [comment] 2017-10-03 22:24
We've since removed aphrodite. Closing.

**Closed by Noviny** 2017-10-03 22:24 UTC
Labels: bug
