### ISSUE TITLE
Sub Menu randomly goes missing?

### ISSUE THREAD

**Issue by Vincent-Loi** [keystonejs/keystone#2883] opened 2016-05-18 09:15 UTC
In Keystone 0.4, the sub menu sometimes goes missing? This is intermittent but does happen quite often.
### Expected behavior

<img width="931" alt="screen shot 2016-05-18 at 10 13 29 am" src="https://cloud.githubusercontent.com/assets/17518173/15353476/32a0bdca-1ce1-11e6-9910-5937e9fa2f9a.png">
### Actual behavior

<img width="909" alt="screen shot 2016-05-18 at 10 12 57 am" src="https://cloud.githubusercontent.com/assets/17518173/15353527/67eb63fe-1ce1-11e6-89bf-df0cb5b940f6.png">
### Fix

A quick refresh on the page will fix the issue and the menu reappears

**Comment by jstockwin** [comment] 2016-05-18 09:21
@webteckie I think you were saying you experienced this too? Did you ever manage to pin down a way to reproduce this? I've still been unable to make it happen.

**Comment by mxstbr** [comment] 2016-05-18 09:23
Same, that's really weird! @Vincent-Loi do you have reproducible steps to make it happen reliably?

**Comment by Vincent-Loi** [comment] 2016-05-18 09:26
@jstockwin @mxstbr Hm not straightforward but I found that restarting the server/keystone and then quickly clicking through the parent tabs might do it

**Comment by jstockwin** [comment] 2016-05-18 09:40
@Vincent-Loi Still can't reproduce, not for lack of trying. 
When it happens, are there any errors in the keystone console, or the browser console? 
If you inspect element in your browser and have a look for the `<nav class="secondary-navbar">` element, what do you see? Is it there? If so, why can't you see it?

**Comment by webteckie** [comment] 2016-05-18 11:08
@jstockwin @mxstbr you will really need to try harder on this one:=)  You may need to click around and about a few times.  @Vincent-Loi thanks for creating the issue as I forgot to when I first saw this...of course, at that moment I was the only one that could see it and @mxstbr thought I was crazy :=)  Glad someone else has been able to see this :=)

**Comment by jstockwin** [comment] 2016-05-18 11:10
I clicked around for a good 5 minutes and it never disappeared. Do you mean click around the sub-menu itself? Or back and forth from the item screen? I assume you did it on the test server?

**Comment by webteckie** [comment] 2016-05-18 11:16
Focus on one submenu.  Click it, click one of its items.  Click the submenu again.  Click menu.  Repeat N times:=)

**Comment by Vincent-Loi** [comment] 2016-05-18 11:19
@webteckie Glad I'm not the not only experiencing this either, even though it's not happening to others haha.

@jstockwin Well for me, clicking around the primary menu or just one and refreshing a few times also helps reproduce it too, I just did it to get the screenshots. Yes, this issue exists locally and on server.

`<nav class="secondary-navbar">` isn't there when the menu goes missing..

## Working
<img width="452" alt="screen shot 2016-05-18 at 12 13 03 pm" src="https://cloud.githubusercontent.com/assets/17518173/15356720/6906d9b0-1cf2-11e6-993f-319c2b68a7c4.png">

## Missing
<img width="453" alt="screen shot 2016-05-18 at 12 12 38 pm" src="https://cloud.githubusercontent.com/assets/17518173/15356713/63892eb6-1cf2-11e6-8c3a-3d5c637da93a.png">

**Comment by jstockwin** [comment] 2016-05-18 11:20
@Vincent-Loi thanks. What are those 64 warnings in your console?

**Comment by Vincent-Loi** [comment] 2016-05-18 11:25
@jstockwin Good spot haha. It's just a large bunch of these though.. assuming its defaultColumns I specified but removed from my model?

List.js:153 Invalid Column specified: __name__
List.js:153 Invalid Column specified: createAt
List.js:153 Invalid Column specified: author

**Comment by r3wt** [comment] 2016-05-18 15:49
The search for intelligent life continues.

**Comment by terenzeyuen** [comment] 2016-05-20 23:00
So, to reproduce this:
1. Go to a section that has only **One** secondary nav.
2. Resize your browser's width or height.
3. To get it back, go to another section that has more than one secondary nav item...refresh the page.

**Comment by terenzeyuen** [comment] 2016-05-20 23:05
Think fixed it too...just change length from 1 to 0 at line 29, admin/client/App/components/Navigation/Secondary/index.js
<img width="1019" alt="screen shot 2016-05-21 at 00 04 06" src="https://cloud.githubusercontent.com/assets/2553680/15444375/bb8ef4fa-1ee7-11e6-9cd2-561aa8e4abd7.png">

**Comment by terenzeyuen** [comment] 2016-05-20 23:17
Changing this line from length > 1 to length > 1 seems to fix it for us. :)
/admin/client/App/components/Navigation/Secondary/index.js

Works responsively too.

<img width="1019" alt="screen shot 2016-05-21 at 00 04 06" src="https://cloud.githubusercontent.com/assets/2553680/15444488/42fb1c88-1ee9-11e6-8f3d-43dd0b673d8e.png">

**Comment by mxstbr** [comment] 2016-05-21 05:34
:+1: PR?

**Comment by jstockwin** [comment] 2016-05-24 14:03
@Vincent-Loi / @webteckie since I never managed to reproduce this, could one of you check that @terenzeyuen's solution solves the problem for you? 

@teaualune - a Pull Request with that change would be great if you don't mind! Thanks

**Comment by webteckie** [comment] 2016-05-24 21:10
I made that suggested change and couldn't duplicate the issue.  Not sure the change really addresses the issue but it doesn't seem to cause any other issues either.  And if it actually fixed something for @terenzeyuen then I say feel free to PR the change!  Eventually I ran into issues mentioned in #2888 which render the nav bar unusable, anyways :-)

**Comment by terenzeyuen** [comment] 2016-05-24 21:48
Hey guys, sorry been busy. It certainly fixed it on mine and Vincent's case. Odd. I will make a PR for the change over the weekend!

**Comment by AurelioDeRosa** [comment] 2016-12-15 10:08
This issue should be closed as it has been fixed.

**Comment by jstockwin** [comment] 2016-12-15 10:09
👍

**Closed by jstockwin** 2016-12-15 10:09 UTC
Labels: bug
