### ISSUE TITLE
Changing User name field

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#968] opened 2015-01-29 20:52 UTC
Is there a setting I must enable to change a user's `name` attribute?
![screenshot 2015-01-29 12 51 08](https://cloud.githubusercontent.com/assets/587438/5966024/a2a4d090-a7b5-11e4-84a1-aa95cbc2e545.png)
```javascript
'use strict';
var keystone = require('keystone'),
    Types = keystone.Field.Types;

var User = new keystone.List('User');

User.add({
  name: {
    type: Types.Name,
    required: true,
    index: true
  },
  email: {
    type: Types.Email,
    initial: true,
    required: true,
    index: true
  },
  password: {
    type: Types.Password,
    initial: true,
    required: true
  }
}, 'Permissions', {
  isAdmin: {
    type: Boolean,
    label: 'Can access Keystone',
    index: true
  }
});

// Provide access to Keystone
User.schema.virtual('canAccessKeystone').get(function() {
  return this.isAdmin;
});

/**
 * Relationships
 */
// User.relationship({
//   ref: 'Post',
//   path: 'author'
// });

/**
 * Registration
 */
User.defaultColumns = 'name, email, isAdmin';
User.register();
```

**Comment by snowkeeper** [comment] 2015-01-30 04:26
Confimed for master.
![noname](https://cloud.githubusercontent.com/assets/6615106/5971174/f0ce6170-a80d-11e4-8031-0a09eaa15c3c.png)

**Comment by snowkeeper** [comment] 2015-01-30 07:21
I did a little digging and found where it seems the error is happening, but I am not sure if it is expected for some reason.  

https://github.com/keystonejs/keystone/blob/master/lib/list.js#L83-L85
```
Object.defineProperty(this, 'nameIsEditable', { get: function() {
		return (this.fields[this.mappings.name] && this.fields[this.mappings.name].type === 'text') ? !this.fields[this.mappings.name].noedit : false;
	}});
```

This checks if the field is type `text`.  Changing it to test `type === 'name'` and changing the name field def to include `noedit: false` shows the field as it should.

I can make the PR if y'all confirm that is the actual culprit.

**Comment by snowkeeper** [comment] 2015-01-30 08:05
I tried some other things and found the actual blocker that stops the UI from functioning like 0.2.x.
https://github.com/keystonejs/keystone/blob/master/lib/list.js#L140-L142
```javascript
if (el.field === this.nameField || el.field.hidden) {
		return;
}
```
Removing  `el.field === this.nameField ||` fixes the UI issue without adjusting 
https://github.com/keystonejs/keystone/blob/master/lib/list.js#L83-L85
```
Object.defineProperty(this, 'nameIsEditable', { get: function() {
        return (this.fields[this.mappings.name] && this.fields[this.mappings.name].type === 'text') ? !this.fields[this.mappings.name].noedit : false;
    }});
```
Although I am wondering if `nameIsEditable` is functiong as intended.

@JedWatson when you get settled back in can you give some insight.

**Comment by snowkeeper** [comment] 2015-01-30 08:12
Changing `nameIsEditable` give a UI like so:
![1_007](https://cloud.githubusercontent.com/assets/6615106/5972807/953a016e-a82d-11e4-892b-6f818ee43cd3.png)

Changing `getOptions()` produces a UI like 0.2.x:
![1_005](https://cloud.githubusercontent.com/assets/6615106/5972811/a5153072-a82d-11e4-990b-64d9e0157949.png)

**Comment by morenoh149** [comment] 2015-01-30 09:03
ah so then it sounds like it was intended to be configurable. I think changing it so `nameIsEditable` is `true` by default would be better.

**Comment by snowkeeper** [comment] 2015-01-30 10:04
I figured everything out I think...

Keystone makes special use of a Field defined `name` to display a header on the form. 
```javascript
Object.defineProperty(this, 'nameIsEditable', { get: function() {
        return (this.fields[this.mappings.name] && this.fields[this.mappings.name].type === 'text') ? !this.fields[this.mappings.name].noedit : false;
}});
```
 `nameIsEditable` is setting a boolean `true` if a `name` field is not explicitly defined as `noedit:true`,  but is only checking for the type `text`.  So `Types.Select`, `Types.Name` etc are defined `false` and are not allowed to be editable in 0.3.0 due to `getOptions()` not including `name` fields in `list.uiElements`.

So the new code preventing editing a name field that is not defined as `Types.Text` or `String` is from `getOptions()`
https://github.com/keystonejs/keystone/blob/master/lib/list.js#L140-L142
```javascript
if (el.field === this.nameField || el.field.hidden) {
		return;
}
```

I imagine this is a styling choice to stop using a true header for `name` all the time as in 0.2.x and let the name field be editable.

If we want to keep the same look as in 0.2.x then `getOptions` should be fixed.  
![0 2 x name](https://cloud.githubusercontent.com/assets/6615106/5974020/56b64de8-a83d-11e4-9ba9-88df9a243ba5.png)

If we want to make the `name` field a header and editable then we can update `nameIsEditable` to stop checking type.
```javascript
Object.defineProperty(this, 'nameIsEditable', { get: function() {
        return (this.fields[this.mappings.name]) ? !this.fields[this.mappings.name].noedit : false;
}});
```
![0 3 0 name](https://cloud.githubusercontent.com/assets/6615106/5974021/5fae38ca-a83d-11e4-868b-81900e392777.png)

**Closed** 2015-02-05 05:35 UTC
Labels: bug, needs documentation

**Comment by snowkeeper** [comment] 2015-02-05 05:58
@sebmck , I am still getting text for `Types.Name` in the UI without an editable field.  
![tester user admin user - google chrome_021](https://cloud.githubusercontent.com/assets/6615106/6055673/fc3ddc98-acd1-11e4-8a89-ad6357a45a0e.png)

**Comment by sebmck** [comment] 2015-02-05 06:01
@snowkeeper Whoops, forgot to remove a condition. Fixed, let me know if that did the trick.

**Comment by snowkeeper** [comment] 2015-02-05 06:12
Thanks @sebmck, looks good!  
![tester user admin user - google chrome_022](https://cloud.githubusercontent.com/assets/6615106/6055761/0773d034-acd4-11e4-9125-cde8151ba08f.png)
