### ISSUE TITLE
windows compatibility: monorepo does not symlink

### ISSUE THREAD

**Issue by bholloway** [keystonejs/keystone#1487] opened 2019-08-13 00:49 UTC
From @1337cookie https://github.com/keystonejs/keystone-5/pull/1463#issuecomment-519957463

@MadeByMike and I saw the same issue. It is not seen when using `admin` privillages but that  is definitely not advised and not a solution.

```
C:\Users\user\Documents\web\keystone-5>bolt
⚡️   bolt v0.23.6 (node v10.16.1)
�   [1/4] Validating project...
�   [2/4] Installing project dependencies...
$ C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\bolt\node_modules\.bin\yarn config get user-agent yarn/1.17.3 npm/? node/v10.16.1 win32 x64
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "apollo-server-express > apollo-server-core > apollo-tracing@0.5.2" has incorrect peer dependency "graphql@0.10.x - 14.1.x".
warning "graphql-playground-react > react-codemirror@1.0.0" has incorrect peer dependency "react@>=15.5 <16".
warning "graphql-playground-react > react-codemirror@1.0.0" has incorrect peer dependency "react-dom@>=15.5 <16".
[4/4] Building fresh packages...
$ yarn build:build-field-types && preconstruct dev && node ./packages/build-field-types/bin.js dev  && yarn run --silent contributing-guide
yarn run v1.17.3
$ rimraf packages/build-field-types/lib && babel packages/build-field-types/src --out-dir packages/build-field-types/dist --ignore '**/__tests__/**/*','**/__mocks__/**/*'
Successfully compiled 42 files with Babel.
Done in 4.41s.
� info project is valid!
� error { [Error: EPERM: operation not permitted, symlink 'C:\Users\user\Documents\web\keystone-5\packages\arch\packages\alert\src\index.js' -> 'C:\Users\user\Documents\web\keystone-5\packages\arch\packages\alert\dist\alert.cjs.js.flow']
� error   errno: -4048,
� error   code: 'EPERM',
� error   syscall: 'symlink',
� error   path:
� error    'C:\\Users\\user\\Documents\\web\\keystone-5\\packages\\arch\\packages\\alert\\src\\index.js',
� error   dest:
� error    'C:\\Users\\user\\Documents\\web\\keystone-5\\packages\\arch\\packages\\alert\\dist\\alert.cjs.js.flow' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Error: spawn C:/Users/user/AppData/Local/Yarn/Data/global/node_modules/bolt/node_modules/.bin/yarn ENOENT
error     at notFoundError (C:/Users/user/AppData/Local/Yarn/Data/global/node_modules/cross-spawn/lib/enoent.js:11:11)
error     at verifyENOENT (C:/Users/user/AppData/Local/Yarn/Data/global/node_modules/cross-spawn/lib/enoent.js:46:16)
error     at ChildProcess.cp.emit (C:/Users/user/AppData/Local/Yarn/Data/global/node_modules/cross-spawn/lib/enoent.js:33:19)
```

**Comment by bholloway** [comment] 2019-08-13 00:50
I will install windows VM and try to investigate this.

**Comment by bholloway** [comment] 2019-08-13 09:32
Maybe try a directory outside user directory.

Otherwise I shall try when I can.

**Comment by bholloway** [comment] 2019-08-13 11:38
When installing Git in windows.

![image](https://user-images.githubusercontent.com/6868309/62938570-9f21ec00-be12-11e9-9af2-7e890f5d1cb9.png)

I'll check the box and see how it goes.

**Comment by bholloway** [comment] 2019-08-13 13:45
Stuck in hell. Had to install python, windows build tools. Build tools install failed. 😒

**Comment by gautamsi** [comment] 2019-08-13 13:53
I do want this to work on Windows. for now I used WSL (Windows Subsystem for Linux) for Windows 10 so that I can get through any issue.

**Comment by 1337cookie** [comment] 2019-08-13 17:45
Seems like a windows/symlink limitation put in place as some sort of security measure. 
The short answer is Microsoft would like you to "enable developer" mode in windows if you want to create a symlink from a non-elevated command shell.

<details>
  <summary>How to enable developer mode CLICK HERE TO SHOW </summary>
  
1. Open settings (Win + I) and click Update and Security.

![2019_08_14_05_25_04_Settings](https://user-images.githubusercontent.com/15826769/62963338-e761fe00-be54-11e9-8c88-a96a02742c70.png)

2. Click "For Developers" on the left menu.

![2019_08_14_05_25_04_Settings2](https://user-images.githubusercontent.com/15826769/62963346-e9c45800-be54-11e9-86d9-521cd8a6d167.png)

3. Select the "Developer mode" radio box and wait for it to install.
![2019_08_14_05_26_49_Settings3](https://user-images.githubusercontent.com/15826769/62963348-eaf58500-be54-11e9-81ee-bbd89eb5a19f.png)

I personally didn't require a restart or to sign out/sign in.
</details>



More related stuff @ ember.js docs including how to use "Local Security Policy" to change this setting, https://ember-cli.com/user-guide/#enabling-symlinks :
``
To create symlinks the account running Ember CLI must have the SeCreateSymbolicLinkPrivilege. Users in the Administrators group have this permission already. However, if UAC (User Access Control) is enabled, users in the Administrators group must run their shell using Run As Administrator because UAC strips away certain permissions from the Administrators +group, including SeCreateSymbolicLinkPrivilege.
``


Windows developer blog info https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/: 
``
For users who have Developer Mode enabled, the mklink command will now successfully create a symlink if the user is not running as an administrator.
``

Mystery solved?

**Comment by 1337cookie** [comment] 2019-08-13 21:06
> Stuck in hell. Had to install python, windows build tools. Build tools install failed. 😒

npm install -g --production windows-build-tools@4.0.0

**Comment by bholloway** [comment] 2019-08-14 11:38
Restarted installation with a fresh VM snapshot.

* Enable windows Settings > For developers > developer mode
* Install git with `symlink` option
* Install `nvm-windows` and `nvm install latest` and `nvm use ...` that version
* [admin] `npm install -g --production windows-build-tools@4.0.0`
* [admin] `npm install -g node-gyp` (per [this issue](https://github.com/nodejs/node-gyp/issues/1195#issuecomment-300873375) with node-gyp)
* clone the repo
* `bolt install`

Now that I go through the motions I realise that I _have_ used "developer mode" previously.
I'm not sure the git `symlink` option is helpful, possibly a detail to determine later.

I'm encountering `can't read shim path` too now.

**Comment by bholloway** [comment] 2019-08-14 11:40
Possibly https://github.com/boltpkg/bolt/issues/207

**Comment by 1337cookie** [comment] 2019-08-15 11:52
> Possibly [boltpkg/bolt#207](https://github.com/boltpkg/bolt/issues/207)

Yeah I also came across that one.

So I built the bolt package including the changes in this PR @ https://github.com/boltpkg/bolt/pull/215 I had to install and use the [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) with ubuntu, node and yarn, to build it.

Using "yarn link" on the updated bolt directory in windows and "yarn link bolt" in the keystone directory, running "bolt", "bolt dev" and "bolt demo meetup dev" seems to work as expected, with the todo and meetup demo working properly in the browser.

<details>
<summary>Click here to see output from "bolt", "bolt dev" and "bolt demo meetup dev"</summary>

```
C:\Users\usernameremoved\Documents\web\keystone-5>bolt
⚡️   bolt v0.23.6 (node v10.16.1)
�   [1/4] Validating project...
�   [2/4] Installing project dependencies...
$ C:\Users\usernameremoved\Documents\web\bolt\node_modules\.bin\yarn config get user-agent yarn/1.12.3 npm/? node/v10.16.1 win32 x64
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ yarn build:build-field-types && preconstruct dev && node ./packages/build-field-types/bin.js dev  && yarn run --silent contributing-guide
yarn run v1.12.3
$ rimraf packages/build-field-types/lib && babel packages/build-field-types/src --out-dir packages/build-field-types/dist --ignore '**/__tests__/**/*','**/__mocks__/**/*'
Successfully compiled 42 files with Babel.
Done in 1.42s.
� info project is valid!
� success created links!
� info project is valid!
� success created links!
� Contributing to KeystoneJS?
� Read the full Contributing Guide (https://github.com/keystonejs/keystone-5/blob/master/CONTRIBUTING.md)
Done in 4.53s.
�   [3/4] Linking workspace dependencies...
�   [4/4] Linking workspace binaries...
�  success Installed and linked workspaces.
�   Done in 24.51s.

C:\Users\usernameremoved\Documents\web\keystone-5>bolt dev
⚡️   bolt v0.23.6 (node v10.16.1)
$ yarn demo todo dev
$ yarn --cwd ./demo-projects todo dev
$ yarn --cwd todo dev
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev
i Command: keystone dev
√ Validated project entry file ./index.js
√ Keystone server listening on port 3000
√ Initialised Keystone instance
√ Connected to database
√ Keystone instance is ready �
� Keystone Admin UI:   http://localhost:3000/admin
� GraphQL Playground:  http://localhost:3000/admin/graphiql
� GraphQL API:         http://localhost:3000/admin/api

C:\Users\usernameremoved\Documents\web\keystone-5>bolt demo meetup dev
⚡️   bolt v0.23.6 (node v10.16.1)
$ yarn --cwd ./demo-projects meetup dev
$ yarn --cwd meetup dev
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev
i Command: keystone dev
√ Validated project entry file ./index.js
√ Keystone server listening on port 3000
√ Initialised Keystone instance
- Connecting to database[ ready ] compiled successfully
\ Connecting to database[ wait ]  compiling ...
- Connecting to database[ ready ] compiled successfully
√ Connected to database
√ Keystone instance is ready �
� Keystone Admin UI:   http://localhost:3000/admin
� GraphQL Playground:  http://localhost:3000/admin/graphiql
� GraphQL API:         http://localhost:3000/admin/api
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully
```
</details>

Running "bolt demo blog dev" however shows a new error which might not be related.

<details>
<summary>Click here to see "bolt demo blog dev" output</summary>

```C:\Users\usernameremoved\Documents\web\keystone-5>bolt demo blog dev
⚡️   bolt v0.23.6 (node v10.16.1)
$ yarn --cwd ./demo-projects blog dev
$ yarn --cwd blog dev
$ cross-env NODE_ENV=development DISABLE_LOGGING=true node -r dotenv-safe/config `yarn bin`/keystone dev
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\usernameremoved\Documents\web\keystone-5\demo-projects\blog\`yarn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
error Error: spawn ../bolt/node_modules/.bin/yarn ENOENT
error     at notFoundError (C:/Users/usernameremoved/Documents/web/bolt/node_modules/cross-spawn/lib/enoent.js:11:11)
error     at verifyENOENT (C:/Users/usernameremoved/Documents/web/bolt/node_modules/cross-spawn/lib/enoent.js:46:16)
error     at ChildProcess.cp.emit (C:/Users/usernameremoved/Documents/web/bolt/node_modules/cross-spawn/lib/enoent.js:33:19)
```
</details>

Regardless I think the symlink issue can be solved by documenting the "developer mode" option in the docs for the demo projects and pushing for https://github.com/boltpkg/bolt/pull/215 to be merged/reassessed.

**Comment by bholloway** [comment] 2019-08-15 12:10
That branch from the bolt PR did work for me in windows.

I spoke to one of the bolt maintainers in person today - They will need me to show why it works and determine whether it is the best change.

So I’ll  working on that now.

**Comment by MadeByMike** [comment] 2019-08-20 06:11
Seems like this could be "fixed" by documenting the issue?

**Comment by bholloway** [comment] 2019-08-20 06:42
Yes @MadeByMike docs for the "Developer Mode".

We also need this bolt PR to merge boltpkg/bolt#241. So a PR to keystone to update the dependency.

**Comment by 1337cookie** [comment] 2019-09-22 07:44
PR has been merged in bolt 0.24.1 (funny how the PR # and version match 🤔simulation theory confirmed?)

**Comment by gautamsi** [comment] 2019-10-11 23:46
after #1727 I see this error

```
🎁 error @arch-ui/controls the dist directory isn't included in the published files for this package, please add it to the files field in the package's package.json
error Command failed with exit code 1.                                                                                  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. 
```

**Comment by bholloway** [comment] 2019-10-12 00:08
AFAIK bolt has released the fix but we still need to consume here

**Comment by gautamsi** [comment] 2019-10-12 00:19
PR #1727 deprecated use of bolt and now insist on yarn, I have latest yarn installed (v1.19.1).

**Comment by Vultraz** [comment] 2019-11-01 09:16
@gautamsi getting that error too. No idea how to fix :(

**Comment by Vultraz** [comment] 2019-11-01 13:46
Ok, after hours and hours of looking I've tracked down the `dist directory isn't included in the published files` problem! It's a bug in `preconstruct` [Opened a PR](https://github.com/preconstruct/preconstruct/pull/205).

**Closed** 2019-11-03 22:13 UTC
Labels: core
