### ISSUE TITLE
Add a `json` database adapter

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1177] opened 2019-05-16 04:08 UTC
This will greatly simplify our demo projects and minimum getting started requirements.

The adapter can be "dumb" and just read/write disk on every adapter request. It's not meant for prod.

**Comment by dcousens** [comment] 2019-05-16 04:20
> It's not meant for prod.

You say that,  but,  knowing life,  please back it with something well tested,  because it will be used...

**Comment by jesstelford** [comment] 2019-05-16 04:47
Definitely should have tests.

... And probably a `console.warn("You're using the JSON DB adapter. This is not meant for production. You are at risk of losing all your data.")` 👍

**Comment by jesstelford** [comment] 2019-06-20 05:02
Work has begun! See #1310

**Comment by molomby** [comment] 2020-02-12 04:55
Dupe of #947? Also relates to #324.

**Comment by jesstelford** [comment] 2020-02-13 10:26
In-memory, and JSON adapters are distinct. It just so happens I was able to reuse the JSON adapter implementation for the In-memory implementation too 👍

**Closed** 2021-04-08 06:55 UTC
Labels: database, dx, needs-review
