### ISSUE TITLE
Putting TextArray/NumberArray field on initial true blocks creation dialog in AdminUI

### ISSUE THREAD

**Issue by Ventis** [keystonejs/keystone#1031] opened 2015-02-10 13:55 UTC
In KeystoneJS 0.3.0, if you have a model which has a field of type TextArray/NumberArray and you put this field on initial:true; the creation dialog that should pop up when you click the "Create Foo" button doesn't show. It throws no error, not in the UI and not in the console.

**Comment by creynders** [comment] 2015-03-02 13:44
I can confirm this is a problem. It throws an `Uncaught TypeError: undefined is not a function` in the console. Unfortunately, since there's no sourcemap it simply puts it on `app.js:1`

**Comment by creynders** [comment] 2015-03-02 14:12
The culprit is https://github.com/keystonejs/keystone/blob/11f4083e0929d53dc2ffe840dc890c272276b490/fields/mixins/ArrayField.js#L14
It assumes `this.props.value` to be an array, but it's really a string if no default value was provided. I.e. this can be solved with passing `{default:[]}` to the field configuration @Ventis 

However, I think the value should be set to an empty array in the field initializer or a dedicated error should be thrown, no? What's your preferred approach @JedWatson ?

**Comment by JedWatson** [comment] 2015-07-20 04:23
This should be fixed in 0.4, leaving this open until we confirm.

**Comment by brianjd** [comment] 2015-12-20 04:44
Having this issue in 0.4.0-alpha(20151219).

**Comment by mxstbr** [comment] 2016-08-25 02:25
Fixed in current `master` as of #3393

**Closed by mxstbr** 2016-08-25 02:25 UTC
Labels: bug
