### ISSUE TITLE
`isRequired` on a field with knex adapter throws errors during back link updates

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#1553] opened 2019-08-29 02:01 UTC
The back linking process for a to-single field uses a brute-force approach right now where it forces the linked field to `null`, then immediately after sets it to the id.

But if you've got `isRequired` set, knex will throw an error during the first phase of the back linking.

**Comment by singhArmani** [comment] 2020-02-05 02:11
@jesstelford @MadeByMike : Hi guys, I couldn't reproduce this issue. It seems to be resolved. Closing it now :)

**Closed by singhArmani** 2020-02-05 02:11 UTC
Labels: Relationship, bug, knex, needs-review

**Comment by MadeByMike** [comment] 2020-02-05 02:51
Fixed by Tim \o/
