### ISSUE TITLE
4.0.0-beta5 Randomly Stops Responding to Requests (Node 6.9.2 / Ubuntu 14 / node keystone.js)

### ISSUE THREAD

**Issue by peterpme** [keystonejs/keystone#4116] opened 2017-03-17 20:32 UTC
### Steps to reproduce the behavior
Random, still trying to figure it out.

Node version: 6.9.2

### Expected behavior

Requests that responds
```
0|bootler- | GET / 200 100 ms
0|bootler- | GET / 200 100 ms
```

### Actual behavior

```
0|bootler- | GET / 200 169.014 ms
0|bootler- | GET / 200 264.525 ms
0|bootler- | GET / - - ms
0|bootler- | GET / - - ms
```

Thanks!

**Comment by jstockwin** [comment] 2017-03-19 10:25
I experienced an issue related to [this](https://github.com/Automattic/mongoose/issues/2603#issuecomment-278280963) when using keystone with a mongo replica set. Whenever the replicaset held an election, something wen't wrong and caused exactly this behaviour to happen. 

That said, the issue only affected mongoose 4.6-4.7.2, and beta5 uses 4.7.8, so it should be fixed in beta5 (and  indeed, I've not seen the problem since switching). 

I guess this is probably not your issue, but it's exactly the same behaviour so I thought it was probably worth mentioning.

**Comment by thejameskyle** [comment] 2017-03-22 02:19
@peterpme is there any more information you can add?

**Comment by peterpme** [comment] 2017-03-22 15:07
@thejameskyle thanks for your response!

Unfortunately this will happen randomly and I haven't been able to narrow down reproduction steps.

I was going to see if upgrading the mongoose module to the latest version would help

Thanks again

**Comment by dani190** [comment] 2017-04-20 19:58
I have this issue also. This happens on beta4. Beta 5 works but i start getting Mongo Pool destroyed messages https://github.com/keystonejs/keystone/issues/4225

**Comment by jstockwin** [comment] 2017-10-02 22:15
Latest message was that this is confirmed fixed in Beta5, so I'm going to close this (since the Mongo Pool destroyed error has its own issue).

**Closed by jstockwin** 2017-10-02 22:15 UTC
Labels: needs reproduction
