### ISSUE TITLE
Setting publish date on blog post causes page to be unresponsive.

### ISSUE THREAD

**Issue by kidthales** [keystonejs/keystone#1097] opened 2015-02-22 19:16 UTC
Setting a published date on a blog post via admin UI causes page to become unresponsive.  Stepping through with debugger shows the selected date keeps going back in time.  Test site setup with Yeoman, same results with either Chrome or Iceweasel.

**Comment by webteckie** [comment] 2015-02-22 19:25
Duplicate of #1038

**Closed** 2015-02-22 23:20 UTC

**Comment by JedWatson** [comment] 2015-02-28 12:29
Also, fixed in 0.3.2
