### ISSUE TITLE
Cannot access Keystone Homepage (localhost:3000)

### ISSUE THREAD

**Issue by duythang** [keystonejs/keystone#4014] opened 2017-02-18 08:27 UTC
I am having problem. I tried to finish installation as guide mentioned in http://keystonejs.com/getting-started/
Software versions i installed: 
**node** - v7.5.0 (lastest version)
**mongodb** - v3.4.2 (lastest version)
**OS** - ubuntu 14.4 - 64b
However, i cannot access to Homepage (localhost:3000.)

Please, refer picture: 
![untitled](https://cloud.githubusercontent.com/assets/9314819/23091706/7e36414a-f5ff-11e6-9bcc-768ccdb41c58.jpg)

Can you help me ? Thank you

**Comment by jstockwin** [comment] 2017-02-18 12:36
How long are you waiting before killing it with `^C`? That BSON error happens for me and isn't an issue at all. If you wait a bit longer it should say something like "Keystone started successfully", and then you'll be good to go.

**Comment by fffuture** [comment] 2017-02-18 22:23
Have a same problem. 
Try to `node keystone` and `npm start`.
```~/my-test-project$ node keystone
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fffuture/my-test-project/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fffuture/my-test-project/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```
Also I have this error while installing node_modules: 
```'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:92: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/home/fffuture/my-test-project/node_modules/bson/build'

```
and 
```make: Entering directory '/home/fffuture/my-test-project/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
kerberos.target.mk:98: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: Leaving directory '/home/fffuture/my-test-project/node_modules/kerberos/build'
```

**Comment by duythang** [comment] 2017-02-20 01:09
Use node 4.4.2; MongoDB 3.0.14.. It can run well. However, still happen error "js-bson: Failed to load c++ bson extension, using pure JS version"

**Comment by duythang** [comment] 2017-02-20 01:10
@jstockwin: it cannot run

**Comment by kadosh1000** [comment] 2017-02-21 14:03
@duythang this is an issue while using any nodeJS version higher than 5.x
it seems that keystone not supports the higher versions of nodeJS.

**Comment by bassjacob** [comment] 2017-02-21 19:57
@duythang I'm able to use node@7 without any issues with Keystone. Can you please paste the output of these commands here?

`npm ls keystone`
`npm ls mongoose`
`npm ls mongodb`
`npm ls mongodb-core`

**Comment by lanzhiheng** [comment] 2017-02-25 06:34
![image](https://cloud.githubusercontent.com/assets/8858472/23328890/61cf812a-fb67-11e6-8b85-47e8c8c53e85.png)

![image](https://cloud.githubusercontent.com/assets/8858472/23328873/ef85cc6e-fb66-11e6-9661-36b828a582a2.png)

![image](https://cloud.githubusercontent.com/assets/8858472/23328892/6fb82684-fb67-11e6-95bf-247536716acb.png)


I have the same problem. It sounds like the mongoose's bug.   like [this](https://github.com/Automattic/mongoose/issues/2285) .  Should keystone.js update the mongoose's version  to fix this issue ？

**Comment by bassjacob** [comment] 2017-02-26 00:43
@duythang can you confirm if you're also using keystone@0.3?

@lanzhiheng very likely we should try release a dependency bump for the 0.3 branch. @JedWatson do we have plans for another 0.3 release at any point?

**Comment by komcal** [comment] 2017-02-26 13:13
@duythang I have same problem. It's happen in keystone package not in your project.
I fix this issue by this command
```
cd node_modules/keystone
```
in package.json change mongoose version to 4.7.7
run
```
npm i
```
back to your project and start again

**Comment by duythang** [comment] 2017-03-01 06:28
@bassjacob : Yes i am using keystone 0.3

**Comment by bassjacob** [comment] 2017-03-01 07:47
In that case, it's likely the issue is that 0.3 is using a version of mongoose that is incompatible and has a showstopper bug on node@7.

You can either wait for a new version to be released, or try passing your own version of mongoose to keystone before starting it (see http://keystonejs.com/docs/getting-started/#gettingstarted-startinganewproject - the section header is BYO Express and Mongoose) and see if version 4.7.7 works with your app.

Alternatively, 4.0.0-beta5 is pretty stable and we're getting closer to releasing 4.0 so if you can upgrade to the 4 branch this problem should go away as well.

**Comment by duythang** [comment] 2017-03-01 09:02
@bassjacob : Thank you . When will 4.0 version be released ?

**Comment by bassjacob** [comment] 2017-03-01 10:40
no set date, but there aren't many things left to do for it to be done

**Comment by iTsFILIPOficial** [comment] 2017-03-01 12:44
@bassjacob Do you have a issues to track what left of something similar?

**Comment by jjmpsp** [comment] 2017-03-01 19:04
@bassjacob Is there an official roadmap for these 'many things' / features that you speak of? Would love to contribute to the project in any way that I can if it means a stable release will come sooner!

**Comment by JacksonGL** [comment] 2017-03-02 23:48
Switching back to Node v6.x works for me.

**Comment by Noviny** [comment] 2017-09-20 15:59
Closing issue as 0.3 issue we are not going to resolve.

**Closed by Noviny** 2017-09-20 15:59 UTC
