### ISSUE TITLE
How can I populate data in a populated element?

### ISSUE THREAD

**Issue by quitequinn** [keystonejs/keystone#2668] opened 2016-04-22 02:03 UTC
I have a page, and it has collections added to it. Inside those collections are more elements. How do I populate both the collection and the elements inside it.

3 models:

Page
```javascript
Page.add({
    title: { type: String, initial: true, required: true},
    collections: { type: Types.Relationship, ref: 'Collection', many: true, sortable: true}
});
```
Collection
```javascript
Collection.add({
    title: { type: String, initial: true, required: true},
    elements: { type: Types.Relationship, ref: 'Element', many: true, sortable: true}
});
```
Element
```javascript
Element.add({
    title: { type: String, initial: true, required: true}
});
```
and I'm trying to load them...
```javascript
view.on('init', function(next) {

    var q = keystone.list('page').model.findOne({
        state: 'published',
        }).populate('collections collections[*].elements');

    q.exec(function(err, result) {
        if (result !== null) {
            locals.data.page = result;
        }else{
            return res.status(404).render('errors/404')
        }
    });

});
```
I think I could do it something like this...
```javascript
var async = require('async');

view.on('init', function(next) {

    var q = keystone.list('page').model.findOne({
        state: 'published',
        });

    q.exec(function(err, result) {
        locals.data.page = result;

        var cl = locals.data.page.collections;
        async.forEachOf( cl, function(collection, i, callback){
            keystone.list('Collection').model.findById(collection).populate('elements').exec(function(err, elements) {

                cl = locals.data.page.collections;
                if (collection !== null) {

                    cl[i] = elements;       
                    callback();
                }
            });
        }, function(err){
            next(err)
        });
    }
});
```
But there must be a better way.

I've also made a stack question.
http://stackoverflow.com/questions/36783491/keystonejs-how-can-i-populate-data-in-a-populated-element

**Comment by geloescht** [comment] 2016-04-22 07:20
This is actually about mongoose. Keystone lists are a thin wrapper over mongoose models.

**Comment by quitequinn** [comment] 2016-04-22 17:06
I see, so there isn't a "keystone" solution... I just need to learn more about mongoose?

**Comment by geloescht** [comment] 2016-04-22 18:01
Right. I don't know a lot about deep population in mongoose, but it seems to be possible somehow. Just remember that you can and should use embedded subdocuments where possible instead of population. MongoDB was designed to store large hierarchical documents, unlike relational databases where joins are preferred.

**Comment by mxstbr** [comment] 2016-04-29 17:04
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Closed by mxstbr** 2016-04-29 17:04 UTC
