### ISSUE TITLE
[0.4] Keystone does not like String _id field

### ISSUE THREAD

**Issue by r1b** [keystonejs/keystone#2234] opened 2016-02-06 17:00 UTC
I had a collection with String _id fields (they look like urls, e.g: http://example.com/something). When viewing the list in Keystone, none of the list entries displayed. The call to /api/{list} returned an undefined _id.

I am OK with restricting _id to ObjectId, but I think it should be mentioned in the documentation & validated on startup.

**Comment by morenoh149** [comment] 2016-02-06 18:18
This is something probably inherited from mongodb.

**Comment by erg0dic** [comment] 2016-02-06 19:15
From mongodb docs:

> The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array.

https://docs.mongodb.org/manual/core/document/

**Comment by molomby** [comment] 2016-02-10 05:15
Dupe of #932?

**Comment by bassjacob** [comment] 2017-01-04 09:23
closing due to inactivity. please reopen if this is still an issue.

**Closed by bassjacob** 2017-01-04 09:23 UTC
Labels: bug

**Comment by mahnunchik** [comment] 2018-12-11 21:02
@bassjacob  Why it is closed?

> The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array.

It is not true for keystone 4
