### ISSUE TITLE
Failed to load c++ bson extension

### ISSUE THREAD

**Issue by sononix** [keystonejs/keystone#959] opened 2015-01-28 16:00 UTC
tried following  a yo generator install of keystone but getting this error 
```
$ node keystone
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```
I only get the server running when I stop and restart the terminal - any thoughts on removing the error

**Comment by JohnnyEstilles** [comment] 2015-01-28 22:33
@sononix, can you provide additional specifics:

* OS (I ask because I've encountered this issue on OSX when command developer tools are no available)
* Keystone version
* Node.js version
* Anything else you think might be relevant

**Comment by sononix** [comment] 2015-01-29 07:49
OS 10.10.1
keystone 0.2.42

Developer tools are installed
Mongodb - v2.6.7
GNU Make 3.81
gcc version 4.9.2 (Homebrew gcc 4.9.2_1) 

mongodb installed using brew - I think only way I could get it to work 
node was using version v0.10.32 - updated to v0.10.36 using nvm for management

that about it that I can think of

**Comment by JohnnyEstilles** [comment] 2015-01-30 01:13
I haven't been able to replicate your issue, so unfortunately I don't have a definitive solution for you. However, I have encountered this issue in the past on more than one occasion. One time was related to the lack of developer tools on OS X (clearly not your case). Another time it was caused by some dependencies not properly installed (probably due to install errors I didn't notice). Something you can try is to reinstall all the app's dependencies. I'm not sure if you've tried this already, but it worked for me (at least once) the past.


```
cd /path/to/your/app
npm cache clean
rm -rf node_modules
npm install
```

> NOTE: You may need to use `sudo` to run the above commands.

**Comment by SLyHuy** [comment] 2015-03-21 03:31
I have this issue too.

OS: Window 8.1
MongoDB: 3.0.1
Keystone: 0.3.2

**Comment by SLyHuy** [comment] 2015-03-21 04:00
When remove node_modules and install again. I have some alert:

```
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git undefined
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git undefined
npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficar
ra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
^CTerminate batch job (Y/N)? Y

C:\Document\SHuyLy\Dropbox\ProjectWorkSpace\S-Site\s-coding\scoding>rd /s /q nod
e_modules

C:\Document\SHuyLy\Dropbox\ProjectWorkSpace\S-Site\s-coding\scoding>npm install
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.
x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/michaelficarra/cscodegen.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/michaelficarra/cscodegen.git) undefined
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git undefined
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git undefined
npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficar
ra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
\
```

And this issue still happen.

**Comment by naeemshaikh27** [comment] 2015-04-23 07:16
I m having the same issue.
```
$ node keystone
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```
This is always there before server starts.

**Comment by naeemshaikh27** [comment] 2015-04-23 07:18
issue exists even after
```
cd /path/to/your/app
npm cache clean
rm -rf node_modules
npm install
```
And the OS is windows-7,8

**Comment by SLyHuy** [comment] 2015-04-23 07:23
I think because Window OS dont have js-bson then they run pure JS. It is not big problem, because everything is fine. After I publish the code to online server using CentOS, this Error will no longer.

**Comment by naeemshaikh27** [comment] 2015-04-23 16:39
OK.. Thanks for reply. But there is another window 7 on which the code runs fine without the warning..

**Comment by webteckie** [comment] 2015-04-24 00:54
I have the same issue both in Windows 7 and CentOS 7.  This started happening in one of the 3.x versions as I had not seen it before.  In CentOS 7 I get:

```
processing: /src/keystone.js

2015-04-24 00:29:57,526 INFO success: node entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-04-24 00:29:57,881 DEBG 'node' stdout output:
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

2015-04-24 00:29:57,881 DEBG 'node' stderr output:
js-bson: Failed to load c++ bson extension, using pure JS version
```

Now this CentOS is a VM running in a windows host; not sure if windows' still the culprit as @SLyHuy doesn't see it in his CentOS deployment.

**Comment by snowkeeper** [comment] 2015-04-24 01:16
This error originates from your MongoDB installation.  This SO answer should help:
http://stackoverflow.com/a/22054632

**Comment by Arcane07** [comment] 2015-04-24 19:54
I had the same problem, it was because of the python version, i had to specify the version:
```
npm cache clean
rm -rf node_modules
export PYTHON=python2.7
npm install --python=python2.7
```

**Comment by kartsims** [comment] 2015-11-20 15:53
Same problem here, the SO answer did not help

OSX 10.11.1
Mongo 3.0.7
Node 5.0.0

It seems that the error comes some keystone (sub?)dependencies relying on outdated libraries. I only got here so far and it is quite annoying as it works great on Ubuntu 14.04 with a similar setup

**Comment by Kimpo79** [comment] 2015-11-25 10:17
Same problem here
OSX 10.11.1
Mongo 3.0.7
Node 4.2.1

**Comment by fridays** [comment] 2015-12-01 11:59
Same here 

OSX 10.11.1
Mongo 3.0.7
Node 5.0.0

**Comment by udp** [comment] 2015-12-01 18:46
Just because it hasn't already been mentioned here - this is a warning, not an error.  I've just been ignoring it.

**Comment by ignlg** [comment] 2015-12-01 19:00
And it happens on Ubuntu 14.04 LTS too

**Comment by fridays** [comment] 2015-12-02 14:05
Just upgraded to the master branch, the error is gone.

In package.json:
```
"keystone": "https://github.com/keystonejs/keystone.git",
```
Then
```
rm -rf node_modules
npm install
```

**Comment by KuroTsuto** [comment] 2015-12-09 02:59
As @snowkeeper alluded, for Node 4 at least, this error is entirely upstream. [It originates in the `bson` package itself](https://github.com/mongodb/js-bson/issues/145), which the `mongodb` package depends on, which `mongoose` depends on. The error was corrected right around `bson@4.20`.

@fridays's suggestion to use the **unstable Keystone 0.4.x alpha** branch from master eliminates the error as the `mongoose` dependency was updated, resulting in a bson 4 dependency.

If Keystone 0.3.x is to be maintained, the solution is to bump the `mongoose` dependency from `~3.8.35` to `^4.1.3`. There are [backwards incompatible changes between Mongoose 3 and 4](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) - so Keystone updates might have to be backported from 0.4.x, or applied separately if 0.4.x is largely incompatible.

All of that said, since a pure JS fallback is available for bson and this error does not impede execution, I can't imagine that this issue should take much priority!

**Comment by morenoh149** [comment] 2015-12-27 23:46
closing as dupe #1752

**Closed by morenoh149** 2015-12-27 23:46 UTC

**Comment by manuel-alcocer** [comment] 2017-02-21 06:25
Ainsss...

I think is not necessary ninja tricks for solving this problem.

After creating your keystone project, install npm-check-updates for all users:

`user@debian:~/myproject/my-site$ sudo npm install -g npm-check-updates`

Then update your site packages.json:

`user@debian:~/myproject/my-site$ npm-check-updates -u`

And finally update all packages:

`user@debian:~/myproject/my-site$ npm install `

One last thing. If you chose 'jade' during deployment of keystone, maybe you will need to install 'jade' explicitly:

`user@debian:~/myproject/my-site$ npm install jade --save`

**Comment by codecoaster** [comment] 2017-03-07 06:36
@manuel-alcocer : thank you, this was the only solution i found that worked for running Keystone.

Cheers :+1:

**Comment by agreen757** [comment] 2017-04-24 20:28
`Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND'`

Had an issue where it was working locally but giving above error on Heroku.
I have so far added a postInstall script:

`"postinstall": "npm i keystonejs/keystone"`

This works but slows down deployments.
What is the version of keystone to which I have to upgrade to avoid this?
