### ISSUE TITLE
The renderTrackingMeta get an error when user item has no field `name`

### ISSUE THREAD

**Issue by sandklock** [keystonejs/keystone#1245] opened 2015-03-24 10:26 UTC
I have 2 Models

    var App = new keystone.List('App', {
        track: { createdAt: true, createdBy: 'owner' }
    });
    App.add({
	owner: { type: Types.Relationship, ref: 'User' }
    });

and 

    var User = new keystone.List('User', {map: {name: 'email'} });
    User.add({
	email: { type: Types.Email, initial: true, required: true, index: true }
    });

When I go to App edit page in admin, it shows nothing. I check in console, there is an error

    Uncaught TypeError: Cannot read property 'first' of undefined

So I check in \keystone\admin\src\components\EditForm.js. I realize you have a todo comment at line 94 and line 98 using name.first and name.last.

    // todo: harden logic around user name
    ...
    <span className="item-details-meta-info">{data.createdBy.name.first} {data.createdBy.name.last}</span>
    ...

I think it should show the email instead of name that mapping in User model?

Can we finish this todo soon or any idea for quick fix? I'm using the latest commit of github so I can receive the update asap :D

Thanks,

**Comment by albertovaccarella** [comment] 2015-05-05 00:46
Same issue here

I think the problem is that data.createdBy (same for data.updatedBy) contains an ObjectId of the User model rather than an entire User object

Any suggestions on how to work around this?

**Comment by jorisw** [comment] 2015-11-12 15:11
Yeah. So essentially Keystone assumes that you want your users to have a name field of type `Types.Name`. Therefore users are assumed by Keystone to have a `name.first`and `name.last`, and you'll find that the Admin will also bug out when viewing items where `tracking` is enabled, if you remove the name field on the User model or change its type:

```
TypeError: undefined is not an object (evaluating 'data.updatedBy.name.first')
renderTrackingMetaitem.js:352
```

I would propose that the `name` field on users is made optional and that the Admin UI check if it exists before trying to read it.

**Comment by mxstbr** [comment] 2016-04-29 10:29
We're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone)!

**Closed by mxstbr** 2016-04-29 10:29 UTC
