### ISSUE TITLE
ArrayField

### ISSUE THREAD

**Issue by jbpin** [keystonejs/keystone#3130] opened 2016-07-07 12:11 UTC
Here is a fix for ArrayField mixin
```
      componentWillReceiveProps: function (nextProps) {
		if (!nextProps.value || Array.isArray(nextProps.value)) {
			return;
		}
		if (nextProps.value.join('|') !== reduceValues(this.state.values).join('|')) {
			this.setState({
				values: nextProps.value.map(newItem),
			});
		}
	},
```

**Comment by mxstbr** [comment] 2016-07-07 13:19
Would you mind submitting a PR with this change so we can take a look? What does this fix?

**Comment by jbpin** [comment] 2016-07-07 14:32
Sorry.. I'm bit busy but I'll try. I 4.0.0-alpha. I have issue with Array type like NumberArray for exemple. When I create a new "thing" containing this type of property the admin crash because `this.props.value` is undefined. In a same way validator on NumberArray receive a string or a unique number from the field when there is only one element, so inputIsValid return false.

**Comment by promethe42** [comment] 2016-07-17 15:30
I guess it fixes the issue related to using fields of types Types.TextArray or Types.NumberArray.
Without this, the Admin UI crashes as soon as you create an iteam with a field of one of those types.

I've tried:
* latest master
* 0.3.21
* 0.3.20
* 0.3.19
* 0.3.17
* 0.3.9

On master, the error is:
```
Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60ItemsRow%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
TypeError: e is null
require<[449]</i<.getHostNode()
 packages.js:3005
require<[398]</b.getHostNode()
 packages.js:2492
require<[449]</i<.getHostNode()
 packages.js:3005
require<[391]</u<.updateChildren()
 packages.js:2397
require<[440]</v<.Mixin._reconcilerUpdateChildren()
 packages.js:2929
require<[440]</v<.Mixin._updateChildren()
 packages.js:2941
require<[440]</v<.Mixin.updateChildren()
 packages.js:2941
require<[402]</h.Mixin._updateDOMChildren()
 packages.js:2633
require<[402]</h.Mixin.updateComponent()
 packages.js:2622
require<[402]</h.Mixin.receiveComponent()
 packages.js:2613
require<[449]</i<.receiveComponent()
 packages.js:3007
require<[398]</b._updateRenderedComponent()
 packages.js:2515
require<[398]</b._performComponentUpdate()
 packages.js:2514
require<[398]</b.updateComponent()
 packages.js:2509
require<[398]</b.receiveComponent()
 packages.js:2504
require<[449]</i<.receiveComponent()
 packages.js:3007
require<[398]</b._updateRenderedComponent()
 packages.js:2515
require<[398]</b._performComponentUpdate()
 packages.js:2514
require<[398]</b.updateComponent()
 packages.js:2509
require<[398]</b.performUpdateIfNecessary()
 packages.js:2504
require<[449]</i<.performUpdateIfNecessary()
 packages.js:3007
s()
 packages.js:3082
require<[475]</o<.perform()
 packages.js:3189
require<[475]</o<.perform()
 packages.js:3189
require<[457]</<.perform()
 packages.js:3083
require<[457]</O()
 packages.js:3085
bound ()
 self-hosted:752
require<[475]</o<.closeAll()
 packages.js:3192
require<[475]</o<.perform()
 packages.js:3189
require<[422]</f.batchedUpdates()
 packages.js:2797
u()
 packages.js:3082
r()
 packages.js:3063
require<[456]</l<.enqueueSetState()
 packages.js:3074
require<[394]</r.prototype.setState()
 packages.js:2446
l/</r</s.prototype.handleChange()
 packages.js:1808
bound ()
 self-hosted:750
c()
 packages.js:3443
o/</</<()
 packages.js:1837
require<["redux-thunk"]</r/</</<()
 packages.js:4777
o/</</c.dispatch()
 packages.js:3408
loadItems/</<()
 admin.js:3276
[71]</List.prototype.loadItems/<()
 admin.js:8268
a()
 packages.js:4795
```

On the v0.3 branches, the error is indeed about `this.props.value` being undefined.

**Comment by wmertens** [comment] 2016-07-17 15:39
@promethe42 can you make a PR? I would be especially interested in a solution that uses lodash to compare the arrays.

**Comment by promethe42** [comment] 2016-07-17 15:43
@wmertens I don't have a solution. The proposed fix won't work on master. If you can point me to the right direction I could find a fix and make a PR.

**Comment by promethe42** [comment] 2016-07-17 15:54
Ok for some reason if fails here:

https://github.com/keystonejs/keystone/blob/master/admin/client/App/screens/List/components/ItemsTable/ItemsTableRow.js#L43

because `ColumnType` is invalid (`null` or `undefined` I guess) when `col = Object {type: "id", label: "ID", path: "id"}`.

**Comment by wmertens** [comment] 2016-07-17 15:55
@promethe42 👍 that's the spirit 😄 

I think the error you encountered is actually a different one, here: https://github.com/keystonejs/keystone/blob/173da409fbf0ec2364c03999bca65cb9c32e5ef0/admin/client/App/screens/List/components/ItemsTable/ItemsTableRow.js#L41

That's due to #3157, because some field is not of the right type. I don't fully understand it, and in my branch I worked around that for now.

The error which @jbpin describes would be a different one, and maybe yours is triggered thanks to his fix.

**Comment by JedWatson** [comment] 2016-07-22 17:42
That underlying issue has been fixed now, can someone confirm whether this is still an issue?

**Comment by promethe42** [comment] 2016-07-22 19:50
I can confirm I don't have the problem anymore when I use the `master` branch. Thanks for the fix!

**Closed** 2016-07-22 20:07 UTC
Labels: bug

**Comment by Jpascual55** [comment] 2018-03-09 07:39
Hi, I'm having now the problem that @jbpin describe in his second message here. Anyone could help me about this? It appears be fixed.

**Comment by taliberman** [comment] 2018-05-08 11:06
Same here, 
Same error on the latest version.

**Comment by sourav-prescriber-360** [comment] 2018-09-17 14:19
@Jpascual55  @taliberman  did u find a solution ? I see few PR raised with a working solution [ tested by me ] but not merged
