### ISSUE TITLE
Removing value from Type.TextArray creates empty string

### ISSUE THREAD

**Issue by ChristianRich** [keystonejs/keystone#1594] opened 2015-08-20 06:55 UTC
After removing all 3 records from 'states' I would expect to have an empty array, instead I have 3 null length strings.

{ 
    "_id" : ObjectId("55d5785e262616d78140baa6"), 
    "shortname" : "au", 
    "name" : "australia", 
    "created" : ISODate("2015-08-19T14:00:00.000+0000"), 
    "locations" : [
        "sydney", 
        "melbourne", 
        "brisbane", 
        "perth", 
        "adelaide", 
        "hobart", 
        "cairns"
    ], 
    "states" : [
        "",
        "",
        ""
    ], 
    "__v" : NumberInt(1)
}

**Comment by morenoh149** [comment] 2015-08-20 07:41
this line must not be triggering? https://github.com/keystonejs/keystone/blob/64f3831374781e1b3cc08ecca6eb962327f4e05a/fields/types/textarray/TextArrayType.js#L59 could you check in a debugger

**Comment by ChristianDen** [comment] 2015-08-20 07:46
I actually don't have a debugging environment setup in Node. Can you recommend one?

**Comment by morenoh149** [comment] 2015-08-20 09:22
try https://github.com/node-inspector/node-inspector

**Comment by JedWatson** [comment] 2015-08-21 05:48
I don't think the like @morenoh149 linked to would help in this case. The problem is that the UI is passing empty strings in the POST body when the form is submitted - we'd want to look at the Field component to figure out why.

**Comment by mxstbr** [comment] 2016-04-29 13:06
This is likely fixed in 0.4, can you try and if you're still having this issue comment again? Thanks!

**Closed by mxstbr** 2016-04-29 13:06 UTC
