### ISSUE TITLE
Admin UI: Lookup values for related collection

### ISSUE THREAD

**Issue by maxkoryukov** [keystonejs/keystone#2992] opened 2016-06-03 07:34 UTC
### Expected behavior

In the admin UI, tab `posts`: trying to filter, using field `Blog`. The list of blogs should contain blogs.

### Actual behavior

Currently, the list is empty

![selection_002](https://cloud.githubusercontent.com/assets/8887971/15771910/55e5f662-2987-11e6-82af-bac1e3a95119.png)

### Steps to reproduce the behavior

Go to the admin UI, open `posts`, and try to filter, using field `Blog`.

----

Version: "keystone": "^0.3.16"

Log:

```
GET /keystone/posts 200 1100.208 ms
API Error (database error):
{ [MongoError: Failed to parse: { find: "pages", filter: { __t: "Blog" }, sort: { note: 1 }, limit: "10" }. 'limit' field must be numeric.]
  name: 'MongoError',
  message: 'Failed to parse: { find: "pages", filter: { __t: "Blog" }, sort: { note: 1 }, limit: "10" }. \'limit\' field must be numeric.',
  waitedMS: 0,
  ok: 0,
  errmsg: 'Failed to parse: { find: "pages", filter: { __t: "Blog" }, sort: { note: 1 }, limit: "10" }. \'limit\' field must be numeric.',
  code: 9 }
Unhandled rejection MongoError: Failed to parse: { find: "pages", filter: { __t: "Blog" }, sort: { note: 1 }, limit: "10" }. 'limit' field must be numeric.
    at Function.MongoError.create (/home/www/site/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/www/site/node_modules/mongodb-core/lib/cursor.js:200:36)

```

**Comment by moret** [comment] 2016-06-28 17:05
I can confirm this behaviour.

**Comment by maxkoryukov** [comment] 2016-06-28 20:38
@moret, I have fixed this bug manually in the `node_modules`, but I don't think, that my way of fixing - is the best way :/

**Comment by maxkoryukov** [comment] 2016-06-28 20:38
Anyway:

> commented 26 days ago ... 

I think this will be fixed in **0.4**

**Comment by moret** [comment] 2016-06-28 21:21
@maxkoryukov you're absolutely right, I commented just to keep the reference.

**Comment by morenoh149** [comment] 2016-06-29 00:24
@moret https://help.github.com/articles/subscribing-to-conversations/

**Comment by moret** [comment] 2016-06-29 00:29
@morenoh149 you misunderstood my comment, I wished to point out where in the codebase it seems to be the issue, not merely subscribe to the conversation. If you feel it doesn't add anything I will refrain from doing so in the future.

**Comment by wmertens** [comment] 2016-06-29 05:15
@moret thanks for pointing out where the problem is, I tried to fix it. Would be nice if someone can confirm it fixed.

**Comment by moret** [comment] 2016-06-29 13:41
@wmertens great. I changed my package.json to `"keystone": "git@github.com:keystonejs/keystone.git#a0d9a42e1c84b7987cbc9ae62eef8a1153d3bd25"`, removed and reinstalled node_modules and tested. I can confirm it's fixed, thank you a lot!

**Comment by wmertens** [comment] 2016-06-29 15:42
@moret awesome, I'll close this then and ask @jed to please push a new v0.3 patch release :)

**Closed by wmertens** 2016-06-29 15:42 UTC
