### ISSUE TITLE
Deleting related record makes selection unusable

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2382] opened 2016-03-07 18:29 UTC
When a model has a type: Types.Relationship to another class, select a document in the Admin UI and save.  Then delete the related document and return to the document where it was linked.  Instead of showing a select/dropdown it is stuck on "Loading..." placeholder text.

**Comment by mxstbr** [comment] 2016-03-15 05:27
Good catch! On v4 this only happens when **`many` is true**:

<img width="866" alt="screen shot 2016-03-15 at 16 24 32" src="https://cloud.githubusercontent.com/assets/7525670/13768459/8d579ee4-eaca-11e5-8648-2a6d52e169d5.png">

When `many` is not true, it simply renders an empty select.

Steps to reproduce:

1) Have a `Types.Relationship` field
2) Create a relationship between two things
3) Delete the thing where you did not select the relationship

**Comment by jjhesk** [comment] 2016-03-25 14:11
+1

**Comment by geloescht** [comment] 2016-05-28 08:49
@jstockwin @webteckie Could you try and reproduce this in e2e in the way Max described, please?
@mxstbr Should we simply drop the missing relationship target or display something like 'deleted item'?

**Comment by mxstbr** [comment] 2016-05-28 09:25
I think simply dropping it should be fine, not sure that displaying "Deleted item" instead gives the user any more insight. :+1:

**Comment by jstockwin** [comment] 2016-05-28 09:58
This can now be demonstrated in current master by running the following command, with XXXX replaced with this issue number.
`node test/e2e/server.js --env default --config ./test/e2e/adminUI/nightwatch.json --test test/e2e/adminUI/tests/group999FixMe/XXXX.js`

When this issue is fixed, please move `XXXX.js` to `.../group007Misc/somethingSensible.js`, and also change `'demonstrate issue XXXX': function(browser)` in this file to something more sensible. If you can see a way to make these tests more generic, or add additional testing, then please go ahead.

**Comment by geloescht** [comment] 2016-06-30 10:44
@mxstbr @JedWatson While looking for a way to fix this I found out that we are currently loading related items one-by-one. We could fix the current code, sure, but would you agree that a refactor would make more sense? We could do so much better by populating relationship fields when loading the item and grabbing data directly from the possible options when adding new related items. Is there a way to do this with the current API?

**Comment by export-mike** [comment] 2017-03-16 04:30
I'm now closing this issue. 

As it's no longer reproducible and no longer a problem. From having internal communication at thinkmill with some of the guys here its likely this has been fixed with some rework on the redux state, thats been corrected since the issue opened.

**Closed** 2017-03-16 04:31 UTC
Labels: bug, reproduced (e2e)
