### ISSUE TITLE
Cannot delete last item from a TextArray

### ISSUE THREAD

**Issue by AndreasSvendby** [keystonejs/keystone#2664] opened 2016-04-21 09:19 UTC
I'm using Keystone v0.4.0 (from master branch) and I've added a field for tags as TextArray. If I add tags, I can delete all but the last tag. After removing it and saving, it shows up again after the refresh.

**Comment by Vincent-Loi** [comment] 2016-04-22 22:45
I'm having trouble with this too and any relationship fields. Any solutions?

**Comment by suryagh** [comment] 2016-04-24 02:18
I will take a look into this

**Comment by suryagh** [comment] 2016-04-24 02:47
@AndreasSvendby @AndreasSvendby  Is this the issue in question?

![issue](https://cloud.githubusercontent.com/assets/5177920/14765200/260803e2-09a5-11e6-8786-a997fad29875.gif)

**Comment by Vincent-Loi** [comment] 2016-04-24 07:36
@suryagh Yes, that's exactly our issue

**Comment by AndreasSvendby** [comment] 2016-04-25 07:03
@suryagh Yes, except when I try other fields (as the Author-field here) are saved correctly. Only the tag fields that are not.

**Comment by suryagh** [comment] 2016-04-27 00:33
@Vincent-Loi @AndreasSvendby what are the versions of keystone you are running?

**Comment by Vincent-Loi** [comment] 2016-04-27 01:22
@suryagh I'm using v0.4. If it helps, I found out that it worked sometime before 4th April, not sure which commit though

**Comment by AndreasSvendby** [comment] 2016-04-27 09:02
@suryagh I'm also using v0.4.0 (updated from master branch a couple of days ago)

**Comment by mxstbr** [comment] 2016-04-29 17:04
This is a duplicate of #1655, so I'll close it for now! Thanks for reporting this, we'll look into it!

**Closed by mxstbr** 2016-04-29 17:04 UTC
