### ISSUE TITLE
Keystone init with wysiwyg-options have no effect.

### ISSUE THREAD

**Issue by itzaks** [keystonejs/keystone#3953] opened 2017-01-28 21:24 UTC
### Steps to reproduce the behavior
Install keystone from master. Init with (from the docs):
```
keystone.init({
'wysiwyg override toolbar': false,
'wysiwyg menubar': true,
'wysiwyg skin': 'lightgray',
'wysiwyg additional buttons': 'searchreplace visualchars,'
 + ' charmap ltr rtl pagebreak paste, forecolor backcolor,'
 +' emoticons media, preview print ',
'wysiwyg additional plugins': 'example, table, advlist, anchor,'
 + ' autolink, autosave, bbcode, charmap, contextmenu, '
 + ' directionality, emoticons, fullpage, hr, media, pagebreak,'
 + ' paste, preview, print, searchreplace, textcolor,'
 + ' visualblocks, visualchars, wordcount',
});
```

Tried this with keystone-demo but wouldn't build. "Error: Cannot find module 'jade'". So only tried this with my current project, which is a keystone mounted with custom express app. Not sure if that effects the behaviour, but here are the relevant init options (coffeescript + my custom tinymce options): 

```
@app = new express()
keystone.init(
	'wysiwyg cloudinary images': true
	'wysiwyg additional plugins': 'powerpaste, importcss'
	'wysiwyg additional options':
		powerpaste_html_import: 'clean'
		powerpaste_word_import: 'clean'
		content_css: '/css/app.css'
)

@app.use '/keystone', keystone.Admin.Server.createStaticRouter(keystone)
@app.use keystone.get('session options').cookieParser
@app.use keystone.expressSession
@app.use keystone.session.persist
@app.use '/keystone', keystone.Admin.Server.createDynamicRouter(keystone)
```

### Expected behavior
Changes in the TinyMCE wysiwyg editor (theme/buttons/plugins etc)

### Actual behavior
Remains the default wysiwyg editor style, nothing is effected with/without adding `wysiwyg` options in keystone.init.

**Comment by jstockwin** [comment] 2017-01-29 18:43
@itzaks Since you're trying it on a non-standard configuration, would you mind trying again with the demo project? The error about jade can be solved by doing `npm install jade`. If it works on the demo project then that'll help us work out where the problem is!

**Comment by itzaks** [comment] 2017-01-30 15:53
I'll try, thanks :)

**Comment by itzaks** [comment] 2017-01-30 16:00
Yes, in the demo version at least I see the changes reflected in the admin. Although adding `	'wysiwyg cloudinary images': true` yields ´Failed to load: http://localhost:3000/keystone/js/lib/tinymce/plugins/uploadimage/plugin.min.js` in the console resulting in the TinyMCE-area not being rendered. But at least there is something happening, thus it seems like running keystone on a custom express server is what is causing the bug.

**Comment by sfqpublic** [comment] 2017-03-14 13:12
I have the same issue,using keystonejs 0.4 beta5,adding 'wysiwyg cloudinary images':true yields  Failed to load: http://localhost:3000/keystone/js/lib/tinymce/plugins/uploadimage/plugin.min.js in the console resulting in the TinyMCE-area not being rendered.
The project use yo generator-keystone ,merely unchanged except some pug templates

**Comment by Noviny** [comment] 2017-04-03 06:52
Closing this in favour of #3529, as that appears to be the continuing part of this issue. Looking in to it now.

**Closed by Noviny** 2017-04-03 06:52 UTC
