### ISSUE TITLE
Error on saving boolean required fields through admin UI

### ISSUE THREAD

**Issue by maxkoryukov** [keystonejs/keystone#2939] opened 2016-05-25 00:28 UTC
### Expected behavior

There should be a way to save Collection items with **boolean, required** fields which have default value.

### Actual behavior

For the field `showOnMain`, described as follows:

```javascript

Post.add(
    { heading: 'Appearance'},
    { showOnMain: { type: Boolean, required: true, default: false, index: true } },
);
```

I got an error on save with empty checkboxes:

```
There was a problem saving your changes:
Show On Main is required
```

![keystonebug](https://cloud.githubusercontent.com/assets/8887971/15524146/1b7c0296-2239-11e6-82fa-2b02b66ce2a7.png)

### Steps to reproduce the behavior

1. Declare the Post among other models, with field, mentioned above.
2. Go to keystone admin
3. Clear checkbox
4. Save
5. Error

**Comment by maxkoryukov** [comment] 2016-05-25 00:28
I am sure, that clearing `required:true` for every Boolean field - is the hack, not the solution.

**Comment by geloescht** [comment] 2016-05-25 09:00
In keystone, `required: true` on a Boolean field means "must be checked". So, it's a feature, not a bug. It makes a lot of sense if you consider that a boolean by definition cannot have any value other than `true` or `false`. `undefined` is not a boolean, but Javascript will always convert `undefined` to `false` when you need it.
Or, to give you another example, even though an empty string IS a string, it is not enough to fulfil the `required: true` condition of a string field. Having `required: true` defined on a field is not the keystone equivalent to the SQL definition `NOT NULL`.
If you want to force the user to explicitly make a decision instead of accepting a default value, you can use a numeric select field:
```javascript
{
  type: Types.Select,
  options: [ {label: 'on', value: 1}, {label:'off', value: 0} ],
  numeric: true,
  required: true
}
```

**Comment by mxstbr** [comment] 2016-05-25 09:36
What @geloescht say basically answers the question perfectly. 👌 

Also, we're closing all questions and support requests to keep the issue tracker unpolluted. Please ask this question on [Stackoverflow](https://stackoverflow.com/questions/tagged/keystonejs) or [Gitter](https://gitter.im/keystonejs/keystone) instead!

**Closed by mxstbr** 2016-05-25 09:36 UTC

**Comment by maxkoryukov** [comment] 2016-05-26 01:33
@mxstbr , I thought this was a bug.. 

It is not a feature request, but when I want to display `boolean` value to user (expecting boolean response), I use checkboxes with boolean values - true/false, or some kind of three-state button... It is very useful, when you want to keep the DB in clear state, when `undefined` means **there is no answer**, but not **false** (and `false` means **false** ;) )

**Comment by maxkoryukov** [comment] 2016-05-26 01:33
Thank you!
