### ISSUE TITLE
I tested the demo，if I add a new user，the problem happened，" Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by LXF5133** [keystonejs/keystone#4508] opened 2017-11-13 09:33 UTC
Mongoose model 'error' event fired on 'User' with error:
 Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.checkPassword (C:\lxf-test\node_modules\dumb-passwords\lib\index.js:11:46)
    at password.validate (C:\lxf-test\node_modules\keystone\fields\types\password\PasswordType.js:203:36)
    at password.validateInput (C:\lxf-test\node_modules\keystone\fields\types\password\PasswordType.js:173:19)
    at doFieldValidation (C:\lxf-test\node_modules\keystone\lib\list\updateItem.js:108:9)
    at C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:941:9)
    at eachOf (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:991:5)
    at Object.eachLimit (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:3089:3)
    at C:\lxf-test\node_modules\keystone\lib\list\updateItem.js:164:10
    at C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:3686:9
    at replenish (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:882:17)
    at C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:886:9
    at eachOfLimit (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:913:22)
    at C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:918:16
    at _parallel (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:3685:5)
    at Object.series (C:\lxf-test\node_modules\keystone\node_modules\async\dist\async.js:4525:3)

**Comment by w01fgang** [comment] 2017-11-19 22:30
duplicate of #4496

**Closed** 2018-05-27 08:46 UTC
Labels: bug
