### ISSUE TITLE
Don't allow duplicate items in relationship fields

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone#288] opened 2018-09-07 12:38 UTC
While its possible to set as many duplicate items on a nested list as you like, it's not possible to retrieve that list verbatim (including order and duplicates).

This is a bug in the adapter layer (for mongoose) and the way it retrieves items during the `itemsQuery` phase (it joins on the items, then only returns the unique'd list of join successes, meaning any duplicate information is lost).

**Comment by MadeByMike** [comment] 2019-07-23 01:20
Should this be renamed: "Don't allow duplicate items in relationship fields"?

Duplicate of #1364

**Comment by jesstelford** [comment] 2019-07-23 03:30
Let's maintain this issue as the original. Thanks for finding the duplicate!

From #1364:

> _"I think we should fail validation if duplicate IDs are connected."_

**Comment by MadeByMike** [comment] 2019-07-23 03:33
I'm updating the title to "Don't allow duplicate items in relationship fields" as both issues have come to this as the same conclusion.

**Comment by molomby** [comment] 2020-06-29 07:03
Just a note, this can be worked around currently by manually creating unique indexes on the aux tables created by the relationship field. It might not give you very helpful errors but it will maintain your data integrity.

**Closed** 2021-04-08 06:50 UTC
Labels: bug, verified
