### ISSUE TITLE
Switch datetime to 24h, truncate seconds

### ISSUE THREAD

**Issue by asliwinski** [keystonejs/keystone#4379] opened 2017-07-03 21:10 UTC
I decided to post my question here, since I didn't get any answers on StackOverflow.
How can I disable the am/pm (switch the time format to 24h) and truncate the seconds (i.e. always set to 00) in Admin UI? I'm ok with editing the core files, just need a quick solution.
You may actually consider it a bug, since I tried to use the format string option and it doesn't seem to work at all.

keystone version: 4.0.0-beta.5

**Comment by gsteinert** [comment] 2017-12-31 15:41
In answer to your question, using format should solve the issue.

There is a bug in the format option, but that is already covered by #3160. Can this be marked as a duplicate?

**Comment by stennie** [comment] 2018-07-29 01:21
Closing as duplicate of #3160

**Closed by stennie** 2018-07-29 01:21 UTC
Labels: question
