### ISSUE TITLE
Any idea how to keep Chinese doc syncing? 

### ISSUE THREAD

**Issue by weekwood** [keystonejs/keystone#982] opened 2015-02-03 01:38 UTC
How to list out all the commits with doc modification, want to update Chinese docs

**Comment by snowkeeper** [comment] 2015-02-03 03:38
I thought about that a while ago.  Would a running issue like this that we update work or should it be a room set up on Slack?

Here are the areas I changed recently...

http addition
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L173-L182

https addition
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L219

unix web socket
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L218-L237

session config
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L282

https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L315

Headings
https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/database.jade#L349-L374

Menu
https://github.com/keystonejs/keystone/blob/master/docs/content/en/templates/mixins/docsnav.jade#L76-L81
https://github.com/keystonejs/keystone/blob/da3eaa4a73357612389331df10b2cf7f84b71025/docs/content/en/templates/mixins/docsnav.jade#L51

**Comment by weekwood** [comment] 2015-02-03 03:39
+1 for creating slack room, Thanks @snowkeeper.

**Comment by snowkeeper** [comment] 2015-02-03 04:36
We have a [documentation](https://keystonejs.slack.com/messages/documentation/) channel on Slack already.   I will post there in the future.  @JohnnyEstilles this might interest you since you are working on ES docs.

**Comment by JohnnyEstilles** [comment] 2015-02-03 04:37
@snowkeeper / @weekwood, creating a Slack room is a good idea to broadcast when docs need to be updated, however it does not allow us to keep track of which updates have and have not been completed. 

A few days ago I started a discussion on [Slack](https://keystonejs.slack.com/archives/questions/p1422339654000046) regarding this topic. These were the suggestions solutions that came out of that discussion:

- creating an issue everyting  docs are updated signaling that translations are required
- require separated PRs for doc changes and tag the PR with labels signaling translation requirements

I proposed the first one (which in hindsight I would also suggest be tagged with the required languages), thinking that it would allow us to keep track in an already familiar way of pending translations. The proponents of the last idea suggested that we might wait until all translations are submitted before merging the original docs changes. Some expressed their concern regarding the delay in merging the original PR. 

Alternatively we could create some sort of matrix depicting features pending documentation (in English, Chinese or whatever language). This would allow translators to see all required work in a single place. 

Whatever is decided, it would be nice if it were documented in the Wiki, so that everyone is on the same page.

**Comment by snowkeeper** [comment] 2015-02-03 05:09
I vote for adding issue labels for each language then requiring a new issue be created whenever a PR requires updates to the docs.  

When a language PR has been merged remove the label on the issue.

The same would be applied to doc updates that do not stem from a PR; create an issue with the required labels.

**Comment by weekwood** [comment] 2015-02-03 05:13
+1 create issue and add issue labels

**Comment by JedWatson** [comment] 2015-02-03 05:32
So to recap:

- English is the "source" language, translations are created from it
- Create a new issue when a docs update is needed (or, when new docs are added that need translation)
- The issue is tagged with every language that needs translation added
- As translations are merged, the tags are removed
- When all translations are done the issue is closed

Did I miss anything? Does this work for everyone?

**Comment by snowkeeper** [comment] 2015-02-03 05:54
I am on board.  Also agree with @JohnnyEstilles about adding the process to the wiki.

**Comment by weekwood** [comment] 2015-02-03 05:55
looks good.

**Comment by snowkeeper** [comment] 2015-02-03 06:02
How about also adding the **needs documentation** label to every issue or set a standard title format

**Comment by JohnnyEstilles** [comment] 2015-02-03 06:14
+1 create issue/add labels

**Comment by JohnnyEstilles** [comment] 2015-02-03 06:19
One additional suggestion ...

Once the English docs are created/modified we should reference the PR for the docs (either in the body or the title of the docs issue), so that the translators can easily find the commits to the docs that need to be translated.

**Comment by snowkeeper** [comment] 2015-02-03 07:07
Here is a proposal for the wiki.  Please edit at will.

### Documentation Translation Guidelines  
Keystone's source language is **English**.  We have **Chinese** and **Spanish** translations currently available.  Any new documentation should include the source language before it can be merged.  

In order to keep the process open and available to any who wishes to contribute we have developed the following guidelines to follow.   

**When should a new documentation issue be created?**
1. Features that should be documented.
2. PR's that require new documentation.
3. PR's that submit new documentation to be translated.
4. PR's that submit significant updates to current documentation.  Typos, grammer, and other small language specific updates do not require a new issue.
5. Missing documentation from a specific language.
6. Current documentation that needs to be addressed.

**How should the documentation issue be created?**
1. The title should describe the feature to be documented.
2. Add the global TAG **needs documentation**
3. Add TAGS for each language that needs documentation
4. Link the PR from the source language addition.  If no PR is available include a link to the source file (including the beginning line number). eg: https://github.com/keystonejs/keystone/blob/master/docs/content/en/pages/docs/configuration.jade#L218-L237
5. Describe what needs to be documented or any issues that need attention.

**How should the documentation issue be managed?**
1. If you would like to accept the task of creating a translation or are thinking about doing so make a comment on the issue .  The comment can be as simple as 'considering' or 'in progress'.  If you claim a translation you can be assigned to the issue.
2. Once a PR has been accepted and merged the TAG specific to the languages involved should be removed.  You can ping @keystonejs/contributors to have that done for you.
3. Once all language TAGS have been removed the issue should be closed.

**Comment by weekwood** [comment] 2015-02-03 11:38
![image](https://cloud.githubusercontent.com/assets/310350/6019478/e266c77c-abdb-11e4-9189-d155c17f8fdc.png)
mention is not working

**Comment by webteckie** [comment] 2015-02-03 12:29
Keep in mind that no everyone  (like me) has permissions to tag/untag.  Thus, someone else with that level of permission would have to handle it.

**Comment by weekwood** [comment] 2015-02-03 14:18
@snowkeeper think we need a branch to manage PR instead of master or 0.2.0

**Comment by snowkeeper** [comment] 2015-02-04 00:57
@weekwood at some point we probably should separate the versions to keep the differences in them.

**Comment by snowkeeper** [comment] 2015-02-05 06:36
I added the guidelines to the wiki. 
For the time being I included @keystonejs/contributors as the ping.  If any contributor has an issue with the ping  you can change it or let me know and I will.

**Comment by JohnnyEstilles** [comment] 2015-02-05 06:44
This is awesome @snowkeeper! 

I do  have a question regarding the following:

> 2. Once a PR has been accepted and merged the TAG specific to the languages involved should be removed. You can ping a collaborator (@keystonejs/contributors ) to have that done for you.

Since individual who accepts/merges the PR also have permissions to add/remove `tags`, wouldn't it be easier for that individual to remove the tag?

**Comment by snowkeeper** [comment] 2015-02-05 07:06
@JohnnyEstilles I agree.  My thought process in including that line was to avoid putting any extra responsibilities on @JedWatson plate and let the OP or a collaborator manage that.

Should we remove it or change it?

**Comment by JohnnyEstilles** [comment] 2015-02-05 07:13
@snowkeeper I understand what you mean. I, of course, do not intend to speak on @JedWatson's behalf, but it doesn't seem to me like it would be an overwhelming burden. Personally, I believe the tasks of accepting/merging the PR and removing the task fall within the same domain, so it would make sense for the same individual to do both.

That said, @JedWatson is the owner and primary collaborator of this project, so I think he should make the final call.

**Comment by JedWatson** [comment] 2015-02-05 22:38
Thanks everyone. I'm happy to take on tagging / untagging of doc issues w/ PRs - helps me keep on top of the state of everything. As long as the issue it's related to is linked from the PR then it's pretty easy.

Shall we close this now? seems to be resolved :)

**Comment by JohnnyEstilles** [comment] 2015-02-06 00:31
@snowkeeper, I hope you don't mind I've made some minor edits on your Wiki entry.

- Removed the *You can ping a collaborator ...* note (Thank you @JedWatson for graciously accepting to tag/untag the issues for us)
- Added our *de-fact* navigation links to the top of your article
- Converted the references to the [English](http://keystonejs.com) and [Chinese](http://keystonejs.com/zh/) translations to links to the actual translations (thought it might be useful)
- Mentioned that the Spanish translation will be coming soon (still a work in progress, I haven't submitted a PR yet)
- Added link to your article from the [Knowledge Base](https://github.com/keystonejs/keystone/wiki/Knowledge-Base)
- minor formatting edits

So, unless anyone else has something to add, I think we can consider this issue resolve! :-)

**Closed by JohnnyEstilles** 2015-02-06 00:31 UTC
Labels: suggestion

**Comment by snowkeeper** [comment] 2015-02-06 00:43
Looks good to me @JohnnyEstilles.  Thanks
