### ISSUE TITLE
nuxt.js started project not starting 

### ISSUE THREAD

**Issue by alexgrant999** [keystonejs/keystone#3204] opened 2020-06-26 02:57 UTC
# Bug report

## Describe the bug

I loaded the started project choosing 

npm init keystone-app coaching2
Completed all the steps choosing the nuxt option.
When I use npm run dev, the builder gets stuck at 'connecting to database'

I was able to get the started project running using a blank setup.  When I comment out this line:
```
    new NuxtApp({
      srcDir: 'src',
      buildDir: 'dist',
    }),
```
it works,  

here is the terminal information with the nuxt code included, it gets stuck at 'connecting to database':

```
npm run dev

> @keystonejs/example-projects-nuxt@5.0.7 dev /Users/alexgrant/Development/coaching/coaching2
> cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev

ℹ Command: keystone dev
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
No cookieSecret value was provided. Please generate a secure value and add it to your app. Until this is done, a random cookieSecret will be generated each time Keystone is started. This will cause sessions to be reset between restarts. See [https://www.keystonejs.com/keystonejs/keystone/#config] for details.
✔ Initialised Keystone instance
⠋ Connecting to databaseℹ Preparing project for development                                                                                                12:49:27
ℹ Initial build may take a while                                                                                                   12:49:27

ℹ NuxtJS collects completely anonymous data about usage.                                                                           12:49:28
  This will help us improving Nuxt developer experience over the time.
  Read more on https://git.io/nuxt-telemetry

⠋ Connecting to database
```

**Comment by petr-vysotskiy** [comment] 2020-06-27 19:32
Try setting NUXT_TELEMETRY_DISABLED=1 env variable

**Comment by matheuschimelli** [comment] 2020-07-09 02:58
@alexgrant999 What database are you using? It looks like you are having a trouble with your database connection instead of it been a Nuxt.js trouble

**Comment by thekarinka** [comment] 2020-07-31 11:21
> Try setting NUXT_TELEMETRY_DISABLED=1 env variable

This can be problem while build. I think that this should be added to doc (Or maybe generator? But what about value?).

Also can be simply resolved by adding `telemetry: false` to Nuxt config next to src and build dir in index.js.

**Comment by MadeByMike** [comment] 2020-08-12 01:08
Duplicate of #3049

**Closed by MadeByMike** 2020-08-12 01:08 UTC
