### ISSUE TITLE
map of a readonly field duplicates the field

### ISSUE THREAD

**Issue by magalhas** [keystonejs/keystone#1480] opened 2015-06-18 19:50 UTC
Example:

```
const Page = new keystone.List('Page', {
  map: { name: 'title' },
  defaultColumns: 'title'
});

const pageSchema = {
  title: { type: String, index: true, noedit: true }
};
```

To get around this the `title` field must be set as `hidden: true`, but this doesn't happen if the field is not read only.

**Comment by mxstbr** [comment] 2016-04-29 12:48
I'll close this issue due to age and not quite understand what the problem is—feel free to comment again if you think this is a bug and still exists!

**Closed by mxstbr** 2016-04-29 12:48 UTC
