### ISSUE TITLE
Can we do User Groups/Roles?

### ISSUE THREAD

**Issue by jamlen** [keystonejs/keystone#106] opened 2014-01-03 22:42 UTC
I need to be able to have users belonging to groups and roles and grant them different levels of access to the Administration of Keystone.

Is this something that is currently possible? If so how?

**Comment by jonesrussell** [comment] 2015-05-11 21:23
I'm in need of this functionality myself.  Is there an ETA or anything I can do to assist?

**Comment by morenoh149** [comment] 2016-02-04 16:40
@jonesrussell review https://github.com/keystonejs/keystone/pull/2111

**Comment by morenoh149** [comment] 2016-02-24 23:20
closing as dupe of https://github.com/keystonejs/keystone/issues/803 my recommendation is to evaluate the [rbac module](https://www.npmjs.com/package/rbac)

**Closed by morenoh149** 2016-02-24 23:20 UTC
Labels: new feature, question
