### ISSUE TITLE
Theming the Admin UI

### ISSUE THREAD

**Issue by davideberlein** [keystonejs/keystone#1255] opened 2015-03-25 11:05 UTC
Hello,

@JedWatson in issue #442 you mentioned thinking about how the admin ui can be themed.
Have you made any progress on this topic?
I think the bootstrap approach having a variables.less would be an easy and functional solution.
The user could pass a path to his own variables.less file in which he can overwrite any variables as keystone.init() option.
Since keystone is based on bootstrap thisnvariables.less file propably would consist of 90% bootstrap varibales.

What do you think?

Best regards

David

**Comment by ctaepper** [comment] 2015-03-29 18:29
here is what i do:

- create custom less file and import default keystone.less into it adding my custom styles and overwriting keystone bootstrap variables
```
@import "../../node_modules/keystone/public/styles/keystone";
// change keystone navbar background
@navbar-keystone-bg: green;
```
- gulp task to convert that file to css
- add this route to express config to overwrite the keystone default stylesheet with your own
```javascript
app.get('/keystone/styles/keystone.min.css', function (req, res) {
    res.sendfile('./dist/styles/keystone.min.css');
});
```

it is obviously some form of workaroud, but it pretty much gets the job done

**Comment by davideberlein** [comment] 2015-03-30 06:48
Thanks for the feedback @ctaepper!
Looks like a doable workaround.. however having a proper integration would even be better..
If I have the time I might look into the keystone source and check if I can find a good solution

**Comment by mxstbr** [comment] 2016-04-08 08:49
Closing as a duplicate of #220!

**Closed by mxstbr** 2016-04-08 08:49 UTC
