### ISSUE TITLE
Keystone 4.0.0-beta.5 - List with hidden: true is hidden from admin ui navbar but not admin homepage

### ISSUE THREAD

**Issue by tomhardman0** [keystonejs/keystone#4075] opened 2017-03-08 09:30 UTC
I've been trying to add a hidden model to the admin UI but it still appears on the admin homepage once logged in (e.g. /keystone). I don't think this is the correct behaviour, but I'm not entirely sure. (Keystone 4.0.0-beta.5)

Any direction towards where I should look in Keystone to fix this myself would be appreciated, I'm happy to submit a PR.

### Steps to reproduce the behavior
Add a new keystone list with option hidden set to true. When entering Keystone's admin ui it will be hidden from the nav bar but not the homepage.

### Expected behavior
The list would be hidden from the navbar and the admin homepage.

### Temporary workaround
I'm overriding the admin ui styles so that particular model's button is hidden from the admin ui homepage, by targeting it's data-list-path attr.

Thanks

**Comment by Noviny** [comment] 2017-03-09 03:46
Hi @tomhardman0, just tried this out using the following schema:

```
var keystone = require('keystone');
var transform = require('model-transform');

var PostCategory = new keystone.List('PostCategory', {
	autokey: { from: 'name', path: 'key', unique: true },
	sortable: true,
	hidden: true,
});

PostCategory.add({
	name: { type: String, required: true },
});

PostCategory.relationship({ ref: 'Post', refPath: 'categories' });

transform.toJSON(PostCategory);
PostCategory.register();
```

I couldn't reproduce the bug. The list was hidden in the keystone admin UI, neither part of the home page or the menu. From reviewing the code it looks like it is still working as intended, so I'm going to close this as an issue. happy to work with you to resolve why it's not working in your case. Are there any extra details you can provide?

The place where hidden lists are filtered out is a call to [getOptions()](https://github.com/keystonejs/keystone/blob/master/admin/server/routes/index.js) in the keystone admin [index route](https://github.com/keystonejs/keystone/blob/master/lib/list/getOptions.js).

**Closed by Noviny** 2017-03-09 03:46 UTC
