### ISSUE TITLE
Error when trying to edit a entry in admin UI

### ISSUE THREAD

**Issue by AndreasSvendby** [keystonejs/keystone#2949] opened 2016-05-26 08:10 UTC
### Expected behavior

When selecting a entry in a list in the admin UI, it should load on first attempt
### Actual behavior

If a entry contains a Types.LocalFile and hasn't been loaded for a while, it does not load, and the following error is printed in console: fields.js:4296 Uncaught TypeError: Cannot read property 'filename' of undefined. When reloading the page, the admin UI loads the entry without any issues. It seems that if the entry has been opened recently this is not an issue. This also tends to break other parts of the admin UI, as trying to press the dashboard icon (house) I get the following error: packages.js:17 Uncaught TypeError: Cannot read property 'getNativeNode' of null
### Steps to reproduce the behavior

Use KeystoneJS from the master branch. Add a model with a Types.LocalFile field. Start KeystoneJS and create some entries. After not using the admin UI for some time, the error tends to appear when trying to edit entries. It does appear to happen somewhat randomly.

**Comment by mxstbr** [comment] 2016-05-27 07:54
Hmm, interesting. @keystonejs/testing has anything like this come up in e2e testing at all?

**Comment by jstockwin** [comment] 2016-05-27 07:56
@mxstbr Not that I've seen,  but we don't currently do any e2e testing with file uploads, since this isn't really possible with travis.

**Comment by mxstbr** [comment] 2016-05-27 07:59
Well, there is no uploading happening here, just an empty `LocalFile` field should suffice as far as I can tell?

**Comment by jstockwin** [comment] 2016-05-27 07:59
Ah alright. I assumed it was something to do with having a file uploaded. Will try to reproduce :)

**Comment by jstockwin** [comment] 2016-05-27 08:30
@mxstbr I can't reproduce this. I've logged in to the test server, created 5 new local file items (none of which actually have any files uploaded with them). Browsed around for a bit, then gone back to admin U I home and left everything running for 20 minutes. I went back and all the items seemed to load fine.

I'll leave it for a bit longer and try again, but even if I can reproduce it like this, e2e is probably not going to be able to, without quite a large sleep in the middle...

**Comment by mxstbr** [comment] 2016-05-27 08:34
Thanks for trying, I'll try manually too!

**Comment by AndreasSvendby** [comment] 2016-05-27 11:22
If you can't reproduce it I can try to set up a new project and see if I can reproduce it in a fresh project. It'll have to wait until next weekend or so, as we're launching on Tuesday, so a bit bogged down until then.

Also, when I tried changing to a commit from mid/end of April (#00f7fa47bb1830b4d5812a2c4da17184cbac4bfa) the error disappeared.

**Comment by Noviny** [comment] 2017-03-29 03:26
Closing this issue, as it shouldn't be affecting keystone 4. Still interested in what was causing it if it affecting older version.

**Closed by Noviny** 2017-03-29 03:26 UTC
Labels: bug
