### ISSUE TITLE
TypeError: selectedFields.keys().some is not a function After Fresh Installation

### ISSUE THREAD

**Issue by ilker-capli** [keystonejs/keystone#9409] opened 2024-11-26 10:30 UTC
**Steps to Reproduce**

- npx create-keystone-app@latest
- cd app
- npm run dev
- Open http://localhost:3000 with Safari Browser

- Create New User
- Click Users (http://localhost:3000/users?fields=email%2Cpassword)

![image](https://github.com/user-attachments/assets/088796cd-7292-4bd2-a4c9-5ab2907e72b7)

**Unhandled Runtime Error**

TypeError: selectedFields.keys().some is not a function. (In 'selectedFields.keys().some((k, i) => !list.fields[k].views.Cell.supportsLinkTo && i === 0)', 'selectedFields.keys().some' is undefined)

**Comment by ilker-capli** [comment] 2024-11-26 10:33
#9393 Related with issue

**Comment by dcousens** [comment] 2024-11-26 22:25
Duplicate of #9393

**Closed by dcousens** 2024-11-26 22:25 UTC
