### ISSUE TITLE
[0.3] Cannot filter by TextArray

### ISSUE THREAD

**Issue by erg0dic** [keystonejs/keystone#2476] opened 2016-03-21 17:58 UTC
Looks like addFilterToQuery needs to be implemented on the TextArray type here:
https://github.com/keystonejs/keystone/blob/v0.3.x/fields/types/textarray/TextArrayType.js

a la SelectType:
https://github.com/keystonejs/keystone/blob/v0.3.x/fields/types/select/SelectType.js

@mikesteele

**Comment by mikesteele** [comment] 2016-03-21 18:09
![screen shot 2016-03-21 at 2 05 01 pm](https://cloud.githubusercontent.com/assets/3904909/13928902/0da94172-ef6e-11e5-8f3f-9e4d2fb5111c.png)

Currently, selecting a TextArray attribute under "Add Filter" does nothing. (See screenshot) 

Ideally, the TextArray filter would include an input, and allow the user to search for text that is in any item in the TextArray.

**Comment by mxstbr** [comment] 2016-03-21 19:32
Very true, not all fields are complete just yet, we're in the process of overhauling them! (ref #2438) I'd love a PR implementing this for TextArray

**Comment by erg0dic** [comment] 2016-03-21 20:09
More than happy to implement this for both 0.3 and 0.4 since our users need this feature :)

**Comment by mxstbr** [comment] 2016-03-21 20:25
:+1: awesome, mention me in the PR and/or ping me on Slack and I'll review it asap!

**Comment by mxstbr** [comment] 2016-03-21 21:39
I'll close this as a duplicate of #1776, looking forward to your PR!

**Closed by mxstbr** 2016-03-21 21:39 UTC
Labels: (keystone) fields, enhancement, help wanted
