### ISSUE TITLE
"dependsOn" field prop in keystone 5

### ISSUE THREAD

**Issue by Davo1997** [keystonejs/keystone#2231] opened 2020-01-13 14:16 UTC
Where is the "dependsOn" property of fields  in list???

**Comment by MadeByMike** [comment] 2020-06-03 07:33
Closing this as a duplicate of #2260

There is no `dependsOn` in Keystone 5 and we're not yet sure how we should approach this in v5+

**Closed by MadeByMike** 2020-06-03 07:33 UTC
Labels: needs-review

**Comment by acmoune** [comment] 2021-04-02 21:04
Probably because your are considering PostgreSQL too, but it is alright.

**Comment by acmoune** [comment] 2021-04-02 21:05
Probably because your are considering PostgreSQL too, but it is alright.
