### ISSUE TITLE
Default values are not working on initial fields

### ISSUE THREAD

**Issue by Ventis** [keystonejs/keystone#379] opened 2014-05-23 08:49 UTC
I first noticed this on Select fields but it seems to be not working on every type of field.

Basically if you do something like this: 

```
type: {label:'Type', type: Types.Select, options:waypointTypes, initial: true,required: true, default:'mkw'}
```
the default value is not filled in and it gives a validation error if you try to create the item without filling in a value.

I'm cautiously making an issue of this because I don't know if this is a bug or by design?

**Comment by alsoicode** [comment] 2015-04-22 18:26
Disappointed to see that this is *still* not fixed in the latest version installable via Yeoman.

**Comment by creynders** [comment] 2015-04-23 06:52
@alsoicode disappointment is an _excellent_ motivator :grin: Feel free to submit a PR with a fix. Not only will it help out a small group of dedicated people spending a LOT of their free time on a product you're using, for free, but it will also give you a better understanding of the internals of said product. Which is always useful.
First job would be to identify the problematic field types.

**Comment by alsoicode** [comment] 2015-04-23 12:15
Actually, I submitted a bug report on this issue nearly a year ago: https://github.com/keystonejs/keystone/issues/453

and also a PR that was merged: https://github.com/keystonejs/keystone/pull/473

I am also an Open Source creator and maintainer:
https://github.com/iambrandontaylor/django-admin-sortable
https://github.com/alsoicode/django-simple-math-captcha

I know a tremendous amount of time and effort goes into projects like this, so I do what I can to help out and give back when I have time. I was just hoping this fix would have gone out in a minor release before 0.3.x.

**Comment by creynders** [comment] 2015-04-23 12:35
So this is a regression then?

**Comment by alsoicode** [comment] 2015-04-23 13:09
I can't seem to find a tag with the fix in it, but it's working in the 0.3.x series.

**Comment by creynders** [comment] 2015-04-23 13:18
Ok, I'll find out what rabbit hole it disappeared in :smile:

**Comment by alsoicode** [comment] 2015-04-23 13:20
Awesome. Thanks!

**Comment by creynders** [comment] 2015-04-24 11:18
@alsoicode Ummm ... I'm pretty confused ATM. The `select` field seems to function correctly in the latest keystone version and since the `yo` generated `package.json` sets the keystone version to `~0.3.0` it should automatically install the latest keystone version. So: either this has been fixed by someone _very_ recently or maybe you didn't update `generator-keystone`? In which case it maybe installed keystone v0.2.x?

**Comment by alsoicode** [comment] 2015-04-24 11:31
I'm betting that my `generator-keystone` was out-of-date since it works in the 0.3.x series.

**Comment by creynders** [comment] 2015-04-24 11:36
Phew... :smile: 

Closing this, since it seems to be fixed. If not @Ventis @alsoicode let me know.

**Closed by creynders** 2015-04-24 11:36 UTC
Labels: bug

**Comment by alsoicode** [comment] 2015-04-24 11:38
I'm almost certain that was the case. I've force updated my generator and made a new project to test and all seems well.

**Comment by creynders** [comment] 2015-04-24 11:38
:cake: and :beers:

**Comment by alsoicode** [comment] 2015-04-24 11:39
It's a bit early for a beer on the east coast of the US at the moment, but it's always "Beer-thirty" somewhere :)

**Comment by creynders** [comment] 2015-04-24 11:40
Hence the :cake: It makes you thirsty :)

**Comment by alsoicode** [comment] 2015-04-24 11:42
HAHA
