### ISSUE TITLE
Date picker for CalendarDay or DateTimein AdminUI?

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2565] opened 2020-03-21 13:44 UTC
I've seen this referenced in other issues (for instance https://github.com/keystonejs/keystone/issues/2366), but I don't know if there's been any movement on this.  It's a fairly large inconvience at our end, since the client isn't happy having to enter date strings 'manually'.  Is there any hope of a change in the near future?  The issues seemed to indicate that a fairly simple workaround was possible, using the native date picker.

**Comment by MadeByMike** [comment] 2020-06-03 07:00
This is a duplicate of #2185, and #2366.

Totally understand that this is an important issue and it's high on our priorities.  Please consider contributing to https://github.com/keystonejs/keystone/pull/2922 where we've broken down the work required into a number of smaller tasks.

**Closed by MadeByMike** 2020-06-03 07:00 UTC
