### ISSUE TITLE
After upgrade to 1.0.1: Error: Cannot use GraphQLInputObjectType "IDFilter" from another module or realm.

### ISSUE THREAD

**Issue by chemicalkosek** [keystonejs/keystone#7116] opened 2021-12-22 13:52 UTC
After upgrading to 1.0.1 such error occurs:

```
 GraphQL API Starting on http://localhost:3000/api/graphql
Error: Cannot use GraphQLInputObjectType "IDFilter" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/home/maciek/Dokumenty/websites/amicus2021/backend/node_modules/@keystone-6/core/node_modules/graphql/jsutils/instanceOf.js:35:13)
    at Object.isInputObjectType (/home/maciek/Dokumenty/websites/amicus2021/backend/node_modules/@keystone-6/core/node_modules/graphql/type/definition.js:174:34)
    at createAdminMeta (/home/maciek/Dokumenty/websites/amicus2021/backend/node_modules/@keystone-6/core/dist/initConfig-2fd803cd.cjs.dev.js:166:43)
    at Object.createSystem (/home/maciek/Dokumenty/websites/amicus2021/backend/node_modules/@keystone-6/core/dist/initConfig-2fd803cd.cjs.dev.js:3085:21)
    at setupInitialKeystone (/home/maciek/Dokumenty/websites/amicus2021/backend/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:399:18)
    at initKeystone (/home/maciek/Dokumenty/websites/amicus2021/backend/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:165:41)
```

Node:  v14.15.4

Reverting to 1.0.0 fixes the problem.

**Comment by Noviny** [comment] 2021-12-22 23:46
Hi! We've been having trouble reproducing this, but it looks like an issue where something other than keystone has also installed the `graphql` package.

Seeing your lockfile or and your `package.json`'s dependencies would help us get to the bottom of this.

**Comment by Noviny** [comment] 2021-12-23 00:01
And I'm back! I did a little more digging, and verified that `@keystone-6/auth`, `@keystone-6/core`, and `@keystone-6/fields-document` all use graphql, and we updated the graphql dependency of all of these.

If keystone is the only thing installing `graphql`, upgrading all 3 of these at once should resolve the issue.

If not, see previous message about lockfiles and `package.json`

**Comment by chemicalkosek** [comment] 2021-12-23 07:16
Sure

Package.json:
```
{
  "name": "keystone-app",
  "version": "5.0.0",
  "private": true,
  "scripts": {
    "dev": "keystone dev",
    "start": "keystone start",
    "build": "keystone build",
    "postinstall": "keystone postinstall",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix"
  },
  "dependencies": {
    "@keystone-6/auth": "^1.0.1",
    "@keystone-6/core": "^1.0.1",
    "@keystone-6/fields-document": "^1.0.1",
    "dotenv": "^10.0.0",
    "slugify": "^1.6.4"
  },
  "engines": {
    "node": "^14.15 || ^16.13"
  },
  "devDependencies": {
    "@babel/core": "^7.16.5",
    "@babel/eslint-parser": "^7.16.5",
    "@babel/preset-react": "^7.16.5",
    "@types/node": "^16.11.16",
    "@typescript-eslint/eslint-plugin": "^5.8.0",
    "@typescript-eslint/parser": "^5.8.0",
    "eslint": "^8.5.0",
    "eslint-config-airbnb": "^19.0.2",
    "eslint-config-airbnb-typescript": "^16.1.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-wesbos": "^3.0.2",
    "eslint-plugin-html": "^6.2.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "prettier": "^2.5.1",
    "typescript": "^4.5.4"
  }
}
```

Lock file:
https://gist.github.com/chemicalkosek/785843943acf909f0ac9a3dcdf8f6fbc

**Comment by Nikitoring** [comment] 2022-01-30 20:15
I have same problem( I try to delete yarn.lock, node_modules but it doesn't work for me

**Comment by jschuur** [comment] 2022-08-19 17:55
This just started happening for me too. package.json and package-lock.json:

https://gist.github.com/jschuur/ef5a00e34e9cea168cb1f01748e127f4

I use npm and the current version is 8.15.1. If I rebuild the node_modules folder with yarn with a `resolutions` declaration the problem goes away, but I'm baffled why it cropped up all of a sudden:

```
  "resolutions": {
    "graphql": "^15.8.0",
    "**/graphql": "^15.8.0"
  }
```

**Comment by joshkelly** [comment] 2022-08-19 22:49
I'm hitting the same issue running an `npm init keystone-app`
npm 8.18
node 16.17
keystone-app@7.0.1

package-lock and debug.log : https://gist.github.com/joshkelly/cf0c3768f910a863b8302f4c003e4137.js

**Comment by jschuur** [comment] 2022-08-20 08:30
> I'm hitting the same issue running an `npm init keystone-app` npm 8.18 node 16.17 keystone-app@7.0.1

Yeah, this definitely looks like a new issue that is affecting npm users now. I get the same problem when I npx create a fresh skeleton project and then run 'npm install' which triggers the keystone post install.

Sure, the node modules are already installed and ready to go after create-keystone-app, but once I install any new package with npm, I get the duplicate graphql error.

Steps to replicate:

1. npx create-keystone-app keystone-bug
2. cd keystone-bug
3. yarn dev
4. npm install lodash
5. yarn dev

Step 3 still works, step 5 gets the error posted at the top of the thread.

I began my project a week ago and it only just happened when the Aug 19th update came out, so it looks like this broke things for npm users.

**Comment by dcousens** [comment] 2022-08-20 13:02
@jschuur to clarify, you're saying this is only a problem if you are using `npm`, and not a problem when using `yarn`?

**Comment by jschuur** [comment] 2022-08-20 13:35
> @jschuur to clarify, you're saying this is only a problem if you are using `npm`, and not a problem when using `yarn`?

Correct. I can use yarn with my existing project and use yarn with a new project fine, both without locking the graphql version via `resolutions`.

However, I can't continue to use npm to install new modules, since the August 19th update. That worked before, doesn't now.

**Comment by mzsigler** [comment] 2022-08-20 22:51
npx create-keystone-app is failing for me on a new project with the same error. yarn create keystone-app works as expected.

**Comment by dcousens** [comment] 2022-08-22 02:56
@jschuur, @mzsigler @joshkelly and others, please see our technical writeup for this problem in https://github.com/keystonejs/keystone/issues/7816#issuecomment-1221725768

I think I will close this issue for now as it is quite old and any new problems should be addressed separately.

**Closed by dcousens** 2022-08-22 02:56 UTC
