### ISSUE TITLE
CloudinaryImage field doesn't work for an uploading

### ISSUE THREAD

**Issue by kaaboeld** [keystonejs/keystone#2659] opened 2020-04-05 08:55 UTC
# Bug report

## Describe the bug

I try to upload an image through the admin panel, but API returns error with an empty body.
I have tried to use another uploader with the same Credentials all well.

## To Reproduce
1. createList with field { type: CloudinaryImage, adapter: cloudinaryAdapter }
2. Run application
3. Go to Admin panel
4. Select image for "CloudinaryImage" field
5. Open the Browser console
5. Try upload
6. See error

In Server console:
```
internal/fs/streams.js:151
function _openReadFs(stream) {
RangeError: Maximum call stack size exceeded
...
```
In browser console:
```
Failed to load resource: net::ERR_CONNECTION_RESET
index.js:439 Uncaught (in promise) Error
    at _callee2$ (index.js:439)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (main.c5366187bc25d7d03514.bundle.js:102106)
    at _next (main.c5366187bc25d7d03514.bundle.js:102108)
```

## Expected behaviour

File uploaded to Cloudinary

## System information

- OS: Windows
- Browser: chrome
- Node: v13.11.0
- DB: MongoDb

## Additional context

Packges list:
```
"dependencies": {
    "@keystonejs/adapter-mongoose": "^5.2.1",
    "@keystonejs/app-admin-ui": "^5.9.2",
    "@keystonejs/app-graphql": "^5.1.2",
    "@keystonejs/app-next": "^5.1.1",
    "@keystonejs/auth-passport": "^5.1.3",
    "@keystonejs/auth-password": "^5.1.2",
    "@keystonejs/fields": "^7.0.0",
    "@keystonejs/fields-wysiwyg-tinymce": "^5.2.1",
    "@keystonejs/file-adapters": "^6.0.0",
    "@keystonejs/keystone": "^6.0.1",
    "cross-env": "^7.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^9.7.5",
    "postcss-cli": "^7.1.0",
    "tailwindcss": "^1.2.0"
  }
```

**Comment by KnightWebnApps** [comment] 2020-04-05 10:09
I experienced the same error when using the LocalFileAdapter 

# System

OS: MacOS High Sierra
Brower: Chrome
Node: 13.8.0
DB: MongoDb Atlas

**Comment by thekevinbrown** [comment] 2020-04-06 00:48
Suspected duplicate of https://github.com/keystonejs/keystone/issues/2101

Try downgrading to Node v12 until the upstream package can publish a dependency bump that solves this issue.

**Comment by kaaboeld** [comment] 2020-04-06 04:36
@thekevinbrown thanks! Ur solution work for me.

**Comment by thekevinbrown** [comment] 2020-04-08 07:50
Cool, I'll close this issue in that case.

**Closed by thekevinbrown** 2020-04-08 07:50 UTC
