### ISSUE TITLE
Keystone app breaks with interal slice call on getGqlNames

### ISSUE THREAD

**Issue by PhilBookst** [keystonejs/keystone#9000] opened 2024-02-01 00:10 UTC
Create a new keystone project via yarn create keystone-app, start the app and access localhost:3000, and the error below is thrown

The app should work

<img width="847" alt="image" src="https://github.com/keystonejs/keystone/assets/68562883/82b8900b-5de0-4c50-a078-6697ac1f3484">

node v v18.18.2, but also tried 20 and 16. tested on all browsers. m1 mac 14.2.1 (if it matters)

**Comment by jaycho46** [comment] 2024-02-01 15:50
Is there any way to start project?

**Comment by tauantcamargo** [comment] 2024-02-01 18:01
@dcousens do you have an status for it?

**Comment by jonesjaycob** [comment] 2024-02-01 22:01
Same here. I'm getting errors on a fresh install. 
![Screenshot 2024-02-01 at 2 00 20 PM](https://github.com/keystonejs/keystone/assets/45607883/f03cf6ce-3eec-4b42-ba86-d37388ec6225)

**Comment by jaycho46** [comment] 2024-02-02 00:52
When I used the 'pnpm-lock.yaml' from the 'framework-nextjs-app-directory' example, the project worked.

**Comment by dcousens** [comment] 2024-02-02 01:23
I can reproduce this problem with `yarn`, but not `pnpm`, I had limited time to debug this yesterday but should hopefully have a resolution next week.

**Comment by dcousens** [comment] 2024-02-02 01:26
Likely some dependency has changed behaviour

**Comment by borisno2** [comment] 2024-02-02 05:59
It looks like it has to do with a recent Apollo Client update. Adding
```json
  "overrides": {
    "@apollo/client": "3.7.0"
  },
```
to my `package.json` fixed it for me (later version might also work, I didn't go through and find the actual version where it broke).

Is has something to fetching the adminMetaData here https://github.com/keystonejs/keystone/blob/b6f86573ff0e7bd42fa50413d0e969bee28e3a9a/packages/core/src/admin-ui/utils/useAdminMeta.tsx#L63-L76

**Comment by LoganConnor44** [comment] 2024-02-02 21:59
> Is there any way to start project?

Without @borisno2 's override there is no way to start a project outside of using the other work-around that is mentioned indirectly which is using pnpm.

I tried on a prior application, multiple fresh installs, and a few dockerized environments - all with primarily npm and a few with yarn.

**Comment by dansp89** [comment] 2024-02-03 17:16
> When I put the 'pnpm-lock.yaml' from this repository, the project works fine.


It worked 100%, thanks!

**Comment by dcousens** [comment] 2024-02-05 03:05
The problem is that `@apollo/client` isn't returning the expected data from `useQuery`, despite the request and response being well-formed.

I think I might pin us to `"@apollo/client": "3.8.10"` for now, until this can be resolved upstream.

**Comment by starblazingunicorn** [comment] 2024-02-05 09:58
I have same problem :(  nothing is helping. Any suggestions for a workaround?

**Comment by dcousens** [comment] 2024-02-05 10:00
@starblazingunicorn have you resolved `"@apollo/client"` to `"3.8.10"`?
I am looking to make a patch for this tomorrow in any event.

**Comment by starblazingunicorn** [comment] 2024-02-05 11:49
@dcousens I tried it! but it's not working :/

**Comment by flippinjoe** [comment] 2024-02-05 14:35
We're currently seeing something similar, but our apollo/client is locked at 3.7.17 and does not cause the error locally.  More importantly, this isn't the first time this kind of issue has happened within keystone dependencies.  I wonder if it would make more sense to strictly lock packages within keystone packages to prevent further unanticipated issues

**Comment by dcousens** [comment] 2024-02-05 21:26
@flippinjoe interesting, if you're seeing something similar but your version is locked, how did this pop up for you? Did you update some other dependency?

**Comment by flippinjoe** [comment] 2024-02-06 00:48
@dcousens apologies for the initial hastiness.  Ours was a little bit more involved because we have a monorepo with 2 separate keystone instances.  On one of them we had locked version to 5.7.17, the other we did not.  Due to deduping this worked fine locally, but broke down once we published (one service worked, one did not).

**Comment by macsimtv** [comment] 2024-02-06 16:16
have you found a solution to the problem? I was unable to create a new project :/

**Comment by unbywyd** [comment] 2024-02-06 20:27
I love KeystoneJS, but every new installation is a loss of several hours of life! Every time there are problems, I also encountered this problem, nothing helped except for: **npm i @keystone-6/core@5.7.0** downgrading the version

**Comment by RiskySaptra** [comment] 2024-02-07 00:48
> I love KeystoneJS, but every new installation is a loss of several hours of life! Every time there are problems, I also encountered this problem, nothing helped except for: **npm i @keystone-6/core@5.7.0** downgrading the version
> 
> **Solution for me**: `npm i @keystone-6/core@5.7.0`

wont work

**Comment by dcousens** [comment] 2024-02-07 01:41
Fixed in https://github.com/keystonejs/keystone/pull/9003

**Closed** 2024-02-07 02:20 UTC
Labels: dependencies, 🐛 bug

**Comment by dcousens** [comment] 2024-02-08 02:54
If you missed, this has been fixed and released in https://github.com/keystonejs/keystone/releases/tag/2024-02-07 - please LMK if you see the issue again
