### ISSUE TITLE
Removal of last remaining element in nested-list is not saved...

### ISSUE THREAD

**Issue by Jexah** [keystonejs/keystone#4363] opened 2017-06-12 06:35 UTC
Removal of last remaining element in nested-list is not saved -- given that at least one of its fields has been populated and saved at least once.

 
### Expected behavior
The single Item in the sublist should be deleted from the database on save.

### Actual/Current behavior
When using a nested list from `nested-lists`, if you add a sub-item to an empty list, give the sub-item a value (tested with text, date, reference), save, the item stays: good. Now if we attempt to remove the item from the list, it appears to work until we save, at which point it reappears.

### Steps to reproduce the actual/current behavior
Create a List with any sublist. Create a new Item in that List. Add a sub-item and populate one of the fields. Click Save. Now remove the sub-item you have created and click Save.

I was able to fix this issue by changing line 193 of `/keystone/fields/types/list/ListType.js`:
```
return utils.defer(callback);
```
to
```
values = [];
```

I believe this issue is happening because somewhere further up or down the chain, the "values" object hasn't been set to `null` -- which represents a value of "no value", as opposed to "do not set the value at all". Instead it is `undefined` because there is nothing in React (as opposed to setting to a null value) and this hasn't been handled between React and Keystone's `updateItem` function. This is then coming back down into the `updateItem` function. Changing `values` to `null` here works, because the only time a `ListType` can be passed down to `updateItem` from the Admin UI as `undefined` is if it is empty.

Obviously combining the `undefined`, `null`, and `''` value checks would be more appropriate, but in reality the `getValueFromData` function should be returning `null` or `[]` for this case, to indicate an empty `List`, rather than just changing the behaviour of `undefined` from "do not change" -- as it is in every other `FieldType` to "empty the `List`".

**Edit**: Of note may be that the `get` function in `/lib/path.js` returns `undefined` as the `parts[i]` key is not found in the `obj` object in line 52. This implies that the `get` function is being passed an `obj` with the sublist missing completely, rather than the sublist being an empty array.

**Edit 2**: I cannot for the life of me figure out where the value of the sublist is being set to `undefined` (or more likely, just deleted). If I could find it I'd change it to `[]` and show where I found it. Please forgive me for I am a React noob. It may be that when one sends an empty List to MongoDB, it doesn't store it as a zero-length List, rather an empty List which may be returned as `undefined` when queried. Please let me know whether that idea is pants-on-head stupid or whether it actually holds some water.

**Edit 3**: So React omits the sublist in the information it sends to the server if the sublist is empty, as seen in the Network Panel of Chrome Dev Tools. It does this because it only sends the elements, and not any array definition:
```
------WebKitFormBoundaryXXXXXXXXXXXXXXXX
Content-Disposition: form-data; name="sublistname[0][sublistfield]"

Sublist Field Value
```

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         |  4.0.0-b5
| Node             | 8.1.0 x86-64

**Comment by Reedyuk** [comment] 2017-10-26 19:57
I'm also experiencing the same issue, when i try to save my empty array, it keeps the previous value. I check the values of the pre and post hooks and the previous value is still there.

**Comment by stennie** [comment] 2018-05-31 11:33
Closing as duplicate of #4332.

**Closed by stennie** 2018-05-31 11:33 UTC
Labels: 4.0-release-candidate, bug
