### ISSUE TITLE
about keystonejs on heroku

### ISSUE THREAD

**Issue by gofighting123** [keystonejs/keystone#2077] opened 2016-01-08 11:31 UTC
i am new to keystonejs,
i start a [sydjs-site](https://github.com/JedWatson/sydjs-site) app on heroku but i got an error as follow:
```
2016-01-08T11:20:58.650816+00:00 heroku[slug-compiler]: Slug compilation finished
2016-01-08T11:21:12.694690+00:00 heroku[web.1]: Starting process with command `node keystone.js`
2016-01-08T11:21:15.181127+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2016-01-08T11:21:27.421384+00:00 app[web.1]: Error: Cannot find module 'react-router'
2016-01-08T11:21:27.421389+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:336:15)
2016-01-08T11:21:27.421390+00:00 app[web.1]:     at Function.Module._load (module.js:286:25)
2016-01-08T11:21:27.421390+00:00 app[web.1]:     at Module.require (module.js:365:17)
2016-01-08T11:21:27.421391+00:00 app[web.1]:     at require (module.js:384:17)
2016-01-08T11:21:27.421392+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/keystone/server/createComponentRouter.js:3:19)
2016-01-08T11:21:27.421393+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2016-01-08T11:21:27.421394+00:00 app[web.1]:     at Module._extensions..js (module.js:452:10)
2016-01-08T11:21:27.421395+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:138:7)
2016-01-08T11:21:27.421396+00:00 app[web.1]:     at Module.load (module.js:355:32)
2016-01-08T11:21:27.421397+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2016-01-08T11:21:27.421397+00:00 app[web.1]:     at Module.require (module.js:365:17)
2016-01-08T11:21:27.421398+00:00 app[web.1]:     at require (module.js:384:17)
2016-01-08T11:21:27.421399+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/keystone/server/createApp.js:6:29)
2016-01-08T11:21:27.421400+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2016-01-08T11:21:27.421401+00:00 app[web.1]:     at Module._extensions..js (module.js:452:10)
2016-01-08T11:21:27.421401+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:138:7)
2016-01-08T11:21:27.421402+00:00 app[web.1]:     at Module.load (module.js:355:32)
2016-01-08T11:21:27.421403+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2016-01-08T11:21:27.771653+00:00 heroku[web.1]: Starting process with command `node keystone.js`
2016-01-08T11:21:28.405309+00:00 heroku[web.1]: Process exited with status 1
```
who can tell me what's happened? 
i can start the sydjs app locally.
i am using .env locally and i remark NODE_ENV=production. is that the problem on heroku ?
heroku app set NODE_ENV variable = production as default.

i know when i commit the changes and use command "git push heroku master",
heroku will recompile all the dependencies in the package.json
and download the latest backend keystonejs source from github.
how can i change the package.json to fit my works @@

**Comment by morenoh149** [comment] 2016-01-08 14:53
try commenting out this line https://github.com/JedWatson/sydjs-site/blob/63db09b986b76b13836e6583ede5373a25f9aca9/keystone.js#L5 as the sydjs project uses `dotenv` and attempts to load a `.env` file in your project's root directory.

Instead on heroku you rely on [config vars](https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-config-vars) which are slipped into the node process for you.

**Comment by gofighting123** [comment] 2016-01-09 06:32
thanks for reply @morenoh149 , i remark the <code>dotenv</code> line, commit and rebuild on the heroku, the problem still the same,and i found the issue at https://github.com/rackt/react-router/issues/2195#issuecomment-146642372 and https://devcenter.heroku.com/articles/nodejs-support#runtime-behavior
, so i change the config var <code>NODE_ENV = staging</code> and <code>NODE_MODULES_CACHE = false</code> on the heroku.
i still got the same error about can't find the react-router module. > " <

**Comment by gofighting123** [comment] 2016-01-10 06:24
i add the react-router back to dependencies and /client/config.js
then i can start app on heroku,
but admin beckend got error ...
```
2016-01-10T06:15:00.206942+00:00 app[web.1]: 
2016-01-10T06:15:00.207194+00:00 app[web.1]: Error thrown for request: /keystone/users
2016-01-10T06:15:00.207258+00:00 app[web.1]: TypeError: /app/node_modules/keystone/lib/core/../../admin/server/templates/list.jade:30
2016-01-10T06:15:00.207261+00:00 app[web.1]:     28| 			Keystone.showCreateForm = !{serializeJavaScript(showCreateForm)};
2016-01-10T06:15:00.207262+00:00 app[web.1]:     29| 			Keystone.createFormData = !{serializeJavaScript(submitted)};
2016-01-10T06:15:00.207262+00:00 app[web.1]:   > 30| 			Keystone.createFormErrors = !{serializeJavaScript(createErrors || null)};
2016-01-10T06:15:00.207265+00:00 app[web.1]: 2016-01-10T06:15:00.207265+00:00 app[web.1]: 
2016-01-10T06:15:00.207266+00:00 app[web.1]: Serializing native function: now
2016-01-10T06:15:00.207267+00:00 app[web.1]:     at /app/node_modules/keystone/node_modules/serialize-javascript/index.js:77:19
```

**Comment by yn5** [comment] 2016-01-12 19:48
@gofighting123, That error is caused by https://github.com/keystonejs/keystone/issues/2081 and is fixed in the latest version of Keystone.

**Comment by gofighting123** [comment] 2016-01-13 14:16
thanks a lot @@ awesome !!

**Closed** 2016-01-13 17:54 UTC
