### ISSUE TITLE
Edit filter pop-up position.

### ISSUE THREAD

**Issue by mist123** [keystonejs/keystone#1917] opened 2015-12-04 11:52 UTC
I noticed that It is difficult to edit the filter due to the fact that part of the pop-up is outside the browser viewport.
![screenshot 2](https://cloud.githubusercontent.com/assets/12841927/11589078/496ce6bc-9aa7-11e5-9621-50b56d338bf5.png)
Also sometimes it positioned incorrectly on browser resizes.
![screenshot 2](https://cloud.githubusercontent.com/assets/12841927/11589080/4cc2798a-9aa7-11e5-90a4-6b222d4e173f.png)

**Comment by mxstbr** [comment] 2016-04-29 14:31
Duplicate of #1647, we're aware and will fix it soon!

**Closed by mxstbr** 2016-04-29 14:31 UTC
