### ISSUE TITLE
[0.4]: Localization issue on 'date filter'  (0.4.0 - Demo - Galleries List)

### ISSUE THREAD

**Issue by cantuket** [keystonejs/keystone#1966] opened 2015-12-12 04:52 UTC
When I filter the admin Lists by 'Published Date' I always get results 1 day prior to the date Im searching.

If I filter for Dec 9, I get all the Dec 8 items and same results for 'After' filter. If I filter after Dec 8 the Dec 8 items are still included.

I'm in Chicago if that helps.

**Comment by cantuket** [comment] 2015-12-12 05:18
I just realized this may actually be some sort of rounding error for the date fields.

When saving dates in the 'Field Test' model I got the same results when saving the 'date' field (always one day prior), but I would get the correct date when saving the 'date/time' field.

I'm guessing the 'date only' field is rounding to the nearest day?

**Comment by mxstbr** [comment] 2016-04-29 14:50
This is probably a duplicate of #1345!

**Closed by mxstbr** 2016-04-29 14:50 UTC
