### ISSUE TITLE
Boolean default:true value not working in v4.0.0

### ISSUE THREAD

**Issue by Twansparant** [keystonejs/keystone#4737] opened 2018-07-26 08:20 UTC
### Expected behavior

Add a checkbox which is checked by default. Clicking on it should uncheck the box.

### Actual/Current behavior

Clicking on the checked by default box does not uncheck it.

### Steps to reproduce the actual/current behavior

Add a model with a *Boolean* field with default value set to `true`:
```
import keystone from 'keystone';
const Types = keystone.Field.Types;
const Page = new keystone.List('Page');

Page.add({
	show  : { type: Types.Boolean, label: 'Show this page?', default: true, initial: true }
});
Page.register();
```
Try and uncheck the checkbox.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0
| Node.js          | 9.3.0
| Browser          | Chrome 67

**Comment by stennie** [comment] 2018-09-05 07:33
I can repro the bug for a Boolean field with `default:true`. Note: this doesn't happen for a Boolean field with `default: false`.

@**chrisschaub** Thanks for confirming that this behaviour changed between 4.0.0 RC1 and GA (default works as expected for me in RC1).

I don't see any direct changes for Boolean fields, so this may be an unexpected consequence of [adding semver to dependencies](https://github.com/keystonejs/keystone/commit/1206c09c).

Regards,
Stennie

**Comment by autoboxer** [comment] 2018-10-12 00:06
I traced this back to a change made in fields/types/boolean/BooleanType.js is [this commit](https://github.com/keystonejs/keystone/commit/e3bacafff39d2089fc2ab3cda94c750909f0ce41#diff-db42b200357684f245704688e0ad47bb) about 5 months ago.  It looks like it was confusing logic that was cleaned up in order to get tests working.  @dominikwilkowski, I'm going to dig a little deeper and see if I can answer definitively why it's a breaking change, but I don't want to revert it and cause an issue with tests without checking with you first and finding a best path forward.

**Comment by autoboxer** [comment] 2018-10-14 18:38
So this is strange, the issue went away in my testing.  I'm not sure what to make of it, but @stennie, if you wouldn't mind testing again I'd appreciate hearing what you find.  `default: true` appears to be working while using the current 4.0.0 release version of Keystone.

**Comment by mahnunchik** [comment] 2018-11-19 22:17
Any news? I can't uncheck checkboxes.

**Comment by jahbini** [comment] 2018-11-27 15:46
I have noticed a similar issue with Type Integer with default set to 1 -- Keystone refuses to let me set it to zero.

**Comment by autoboxer** [comment] 2019-01-02 15:47
copying comments from @MadMadlan's duplicate issue #4877:

>We have a field that type is boolean and its default value is true.
>On admin panel (list view) everything is ok, problem is with item view.
>On item view field even when its value is false (unchecked) seems to be marked as true. It is also impossible to uncheck this field.
>I tested this on keystone 4.0.0 and keystone 4.0.0-beta.4. On 4.0.0-beta4 it is ok problem is with version 4.0.0

**Comment by ttsirkia** [comment] 2019-01-17 21:42
Hmm. Just wondering if the cause could be here: https://github.com/ttsirkia/keystone/blob/master/admin/client/App/screens/Item/components/EditForm.js#L87 That was added in #4698 as explained in the description.

**Comment by ttsirkia** [comment] 2019-01-17 21:46
This 
```
props.value = this.state.values[field.path] === undefined ? field.defaultValue : this.state.values[field.path];
```
may resolve the problem but I can't test it now.

**Comment by ttsirkia** [comment] 2019-02-19 20:21
I confirm that that the code suggestion above for `EditForm` will fix the issue.

**Comment by zhdanouskikh** [comment] 2019-03-04 12:13
Guys, this issue was submitted on July 26. It's still reproduced and that's a problem for some releases.
Will it be fixed in nearest future?

**Comment by ttsirkia** [comment] 2019-03-04 13:40
I haven't made PR because haven't had time to see how to make proper unit tests. If a PR is accepted without them, I'm happy to submit it.

**Comment by Vultraz** [comment] 2019-03-05 02:12
Issue happens for me too.

**Comment by jbfolkerts** [comment] 2019-05-26 22:17
Kinda disappointed that this didn't make the cut for 4.1.0.  In the meantime, turning off "default: true"

**Comment by autoboxer** [comment] 2019-05-27 02:54
@jbfolkerts, 4.1.0 was about bringing Keystone dependencies up to date, which was an unfortunately difficult process.  A group of us who have recently started to actively maintain the repo are aware of the issue and will be working to fix it in one of the upcoming releases.  Issues with field types not working correctly are high on the list.  If you're interested in being a part of the discussion, feel free to join the Keystone Slack, specifically the v4-maintenance channel.

**Comment by JedWatson** [comment] 2019-05-27 11:44
In addition to what @autoboxer said, for 4.1.0 we were mostly focused on landing PRs that had come in (or been merged) and making sure we got them released. We'll start looking at important issues next.

If you're not sure how to add tests but want to open a PR for this anyway, that would help move this along and we can work out what to do from a testing standpoint when it's being reviewed 👍

**Comment by ttsirkia** [comment] 2019-05-27 18:45
Made a PR that will fix the issue.

**Closed** 2019-06-23 11:20 UTC
Labels: 4.x candidate, bug
