### ISSUE TITLE
using webpack for server side code, doesn't work

### ISSUE THREAD

**Issue by sarkistlt** [keystonejs/keystone#4293] opened 2017-05-15 17:23 UTC
I'm trying to bundle server side code for 2 reason, I want to be able freely use es6 + type checking with TypeScript or Flow. In both cases I need to compile code to vanila js.

I'm using keystone.js as entrance to app, so bundle creates with no error, but when I'm trying to run it, it shows errors like  

```cli
Error: Cannot find module 'routes/views/account/contact.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
...
```

Error comes from `dispatchImporter` function in keystone module, I guess because keystone scan file system for `models` and `routes` import what I think not the best solution.

Is it any way to avoid this problems? My webpack config file below:

```js
const webpack = require('webpack');
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const nodeExternals = require('webpack-node-externals');
const FlowBabelWebpackPlugin = require('flow-babel-webpack-plugin');

const webpackConfig = [];

const { NODE_ENV = 'development' } = process.env;
const isDev = NODE_ENV !== 'production';

const server = {
  entry: {
    index: [path.resolve(__dirname, './keystone.js')],
  },
  output: {
    path: path.resolve(__dirname, './dist/server/'),
    filename: '[name].js',
  },
  target: 'node',
  node: {
    __dirname: true,
    __filename: true,
  },
  externals: [nodeExternals()],
  resolve: {
    extensions: ['.js', '.jsx'],
    modules: ['node_modules'],
  },
  watch: isDev,
  watchOptions: {
    aggregateTimeout: 100,
  },
  devtool: false,
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [
          { loader: 'babel-loader' },
        ],
        exclude: /node_modules/,
      },
    ],
  },
  plugins: [
    new webpack.IgnorePlugin(/\.(css|less|sass|scss)$/),
    new CleanWebpackPlugin(['./dist/server/'], {
      root: path.resolve(__dirname),
      verbose: true,
    }),
  ],
};

if (!isDev) {
  server.plugins = [
    ...server.plugins,
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false,
        drop_console: true,
        unsafe: true,
      },
    }),
  ];
} else {
  server.plugins = [
    ...server.plugins,
    new FlowBabelWebpackPlugin(),
  ];
}

webpackConfig.push(server);

module.exports = webpackConfig;
```

**Comment by export-mike** [comment] 2017-05-16 00:45
Duplicate of closed issue: https://github.com/keystonejs/keystone/issues/4234

**Comment by export-mike** [comment] 2017-05-16 00:45
Feel free to discuss your use case in https://github.com/keystonejs/keystone/issues/4234

**Closed by export-mike** 2017-05-16 00:45 UTC
