### ISSUE TITLE
Errors returned by schema.pre('remove') middleware don't display in the Admin UI

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#536] opened 2014-08-12 12:27 UTC
As reported by David Vermeir in the Google Group:

When you try to delete an item but throw an error in a 'remove' hook it doesn't show up in the flashMessages in the detail view, or in the alert box in the list view.

Test case:

```
/*
* Stop deletion of challenge if already active
* */
Challenge.schema.pre('remove', function(next) {
    if(this.status === 1) { return next(new Error("You can't remove a challenge once it's been activated!")); }
    keystone.list('UserChallenge').model.findOne({challenge: this._id}).exec(function(err, userChallenge) {
        if(userChallenge) { return next(new Error("You can't remove a challenge that's in use by a player!")); }
        next();
    });
});
```

Return an error in the next() callback usually works for 'save' hooks but not for 'remove'.

In the detail view it shows the following error in the flash messages section:

> There was an error deleting Challenge (logged to console)

In the list view it shows the following error in the alert popup:

> There was an error deleting the challenge. ( error: database error)

So it's successfully stopping the 'remove' but not showing the errors I throw.

**Comment by morenoh149** [comment] 2015-08-06 05:12
@ianbjorndilling @JedWatson was this solved?

**Comment by larsha** [comment] 2016-02-23 11:07
@morenoh149 @JedWatson I'm still having issues with this, I have a pre-save hook checking for duplicate e-mail adresses, something like this:

`User.schema.pre('save', function(next) {
  User.model.findOne({ 'email': this.email }).exec()
    .then((user) => {
      if (user) {
        return next(new Error('E-mail already exists.'));
      }

      return next();
    })
    .catch((err) => {
      next(new Error(err));
    });
});`

The error message don't show up in the admin ui when creating a new user. Am I approaching this the wrong way?

**Comment by creynders** [comment] 2016-02-24 08:10
@larsha That should work. I do it all the time in my projects. Could you post a bare-bones example that reproduces this behaviour?

**Comment by larsha** [comment] 2016-02-24 08:55
Hi @creynders, here's an example of the code:


```javascript
User.schema.pre('save', function(next) {
  User.model.findOne({ 'email': this.email }).exec()
    .then((user) => {
      if (user) {
        return next(new Error('E-mail already exists on another user.'));
      }

      return next();
    })
    .catch((err) => {
      next(new Error(err));
    });
});
```

Here's a screenshot of the admin ui part when no flash error shows after hitting create with an e-mail adress already registered. 
![skarmavbild 2016-02-24 kl 09 48 15](https://cloud.githubusercontent.com/assets/1212552/13280135/869de3ea-dadc-11e5-8f08-d656c0246ddd.png)

Although the error shows up in the console as mentioned: `Error saving changes to User 56cd6e4a71770fe8624a3d38:
[Error: E-mail already exists on another user.]`

**Comment by creynders** [comment] 2016-02-24 09:44
Is this 0.3? or 0.4? Come to think of it, I don't think I've got any custom validation on `initial` fields, maybe the bug's only with them. I'll try to verify it asap.

**Comment by larsha** [comment] 2016-02-24 09:45
It's 0.3, that would be helpful, thanks @creynders !

**Comment by gaoyan10** [comment] 2016-02-26 16:34
I have got the same error, with keystone 0.3.16. The error shows in the console, but the flash message not show.

**Comment by creynders** [comment] 2016-02-26 18:55
I can confirm the bug only happens when creating items, not when editing. Don't know whether it applies to 0.4 too. BTW @larsha this would always fail when trying to save an already existing user, since the query will return the user you're editing.

**Comment by larsha** [comment] 2016-02-26 19:07
Thanks @creynders, some more logic around that one I guess, maybe exclude the user by id should solve that problem?

**Comment by creynders** [comment] 2016-04-29 09:51
fixed in #2566 for v0.4.

**Closed by creynders** 2016-04-29 09:51 UTC
Labels: bug

**Comment by VinayaSathyanarayana** [comment] 2017-08-17 16:19
Any update on this @creynders  - Not working in 4.0.0-beta.5

**Comment by langovoi** [comment] 2017-08-19 15:13
Any news, guys?

**Comment by Mukarrim** [comment] 2019-04-24 13:19
> Thanks @creynders, some more logic around that one I guess, maybe exclude that user by it's id should solve that problem?
> 
> **_Edit:**_
> Solved that issue like this:
> `User.model.findOne({ 'email': this.email, '_id': { '$ne': this._id } }).exec()`

thanks man for the 'id' part saved life :)
