### ISSUE TITLE
`keystone build` hangs

### ISSUE THREAD

**Issue by abhi-markan** [keystonejs/keystone#8802] opened 2023-09-09 12:57 UTC
* With following `dependency` and `devDependency` causing npm `ERESOLVE` error will simply hangs `keystone build` during ` (Static)  automatically rendered as static HTML (uses no initial props)` phase.

Would expect build process to finish as normal.

Build process simply hangs, with no verbose.

![image](https://github.com/keystonejs/keystone/assets/32125108/650c62d6-0c64-40d7-8ec4-53708eafbd79)

Following versions are being used for re-produce the issue:
* Node: 18.15.0
* NPM: 9.8.1
* OS:  Ubuntu 20.04 LTS

With following dependencies, one can re-produce the issue:
* Use following your `package.json`
```javascript
  "dependencies": {
    "@babel/core": "^7.22.17",
    "@babel/plugin-transform-runtime": "^7.22.15",
    "@babel/preset-env": "^7.22.15",
    "@babel/preset-typescript": "^7.22.15",
    "@graphql-tools/schema": "^10.0.0",
    "@keystone-6/auth": "^7.0.2",
    "@keystone-6/core": "^5.5.1",
    "@keystone-6/fields-document": "^8.0.1",
    "@types/express": "^4.17.17",
    "axios": "^1.5.0",
    "axios-mock-adapter": "^1.21.5",
    "date-fns": "^2.30.0",
    "dotenv": "16.3.1",
    "exceljs": "^4.3.0",
    "express-rate-limit": "^6.11.0",
    "jsonwebtoken": "^9.0.2",
    "notifications-node-client": "^7.0.3",
    "otplib": "^12.0.1",
    "typescript": "^5.2.2"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-proposal-object-rest-spread": "^7.20.7",
    "@types/jest": "^29.5.4",
    "@types/jsonwebtoken": "^9.0.2",
    "@typescript-eslint/eslint-plugin": "^6.6.0",
    "@typescript-eslint/parser": "^6.6.0",
    "babel-jest": "^29.6.4",
    "eslint": "^8.49.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.1.0",
    "eslint-config-airbnb-typescript-prettier": "^5.0.0",
    "eslint-config-prettier": "8.10.0",
    "eslint-import-resolver-typescript": "^3.6.0",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-prettier": "5.0.0",
    "jest": "^29.6.4",
    "prettier": "^3.0.3",
    "ts-jest": "^29.1.1"
  }
```
* Run `npm i --legacy-peer-deps` to install the packages with missing dependencies.
* Run `npx keystone build`
* One can expect the build process to never finish.

## Resolution
Ensure no error pertaining to peer dependency resolution does not exist, after which the build process will finish as expected.

**Comment by gautamsi** [comment] 2023-09-09 22:34
#8788  should solve with next release.

**Comment by dcousens** [comment] 2023-09-10 23:57
Duplicate of https://github.com/keystonejs/keystone/issues/8760#issuecomment-1712775494

**Closed by dcousens** 2023-09-10 23:57 UTC
