### ISSUE TITLE
context.prisma returns undefined

### ISSUE THREAD

**Issue by sirbully** [keystonejs/keystone#5398] opened 2021-04-07 11:05 UTC
# Bug report

I want to do data seeding. According to [docs](https://next.keystonejs.com/apis/config#db):
> They (database adapters) also all have an optional `onConnect` async function, which takes a `KeystoneContext` object, and lets perform any actions you might need at startup, such as data seeding.

## Describe the bug

`context.prisma` is returning `undefined`. For now, I'm using the deprecated `context.keystone.adapter` in order to perform data seeding.

## To Reproduce

1. Set up database using Config API like so:
    ```
    config({
        ...
        db: {
            adapter: 'prisma_postgresql',
            url: databaseURL,
            onConnect: async (context) => {
                console.log(context.prisma)
            },
        },
        ...
    })
    ```
2. Console logs undefined for `context.prisma`

## Expected behaviour

I expect `context.prisma` to be a Prisma Client as stated in your [docs](https://next.keystonejs.com/apis/context#database-access).
> The `KeystoneContext` object exposes the underlying database driver directly via `context.prisma`, which is be a Prisma Client object.

## Screenshots

Short snippet of console logging the `KeystoneContext` object.
<img width="181" alt="Screen Shot 2021-04-07 at 7 02 16 PM" src="https://user-images.githubusercontent.com/29673385/113856419-c7bedc80-97d3-11eb-8ac2-8276647cbe43.png">

What I'm doing right now for data seeding
<img width="386" alt="Screen Shot 2021-04-07 at 7 01 56 PM" src="https://user-images.githubusercontent.com/29673385/113856527-f341c700-97d3-11eb-8b6f-33b620ba2118.png">

The Prisma Client found inside the `context.keystone.adapter` object.
<img width="349" alt="Screen Shot 2021-04-07 at 7 07 33 PM" src="https://user-images.githubusercontent.com/29673385/113857033-9a266300-97d4-11eb-9b74-e2a6074f5c5a.png">

## System information

- OS: macOS
- Browser (if applies): Brave
- IDE: VS Code

**Comment by ashhitch** [comment] 2021-04-07 13:29
I have been using `context.keystone.adapter.prisma;`

The `keystone` property is marked as deprecated so, I'm assuming there is a better way.

**Comment by JedWatson** [comment] 2021-04-08 23:22
@sirbully could you confirm the versions of keystone packages you're seeing this happen with?

**Comment by sirbully** [comment] 2021-04-08 23:31
> @sirbully could you confirm the versions of keystone packages you're seeing this happen with?

@JedWatson I'm using version 14 of @keystone-next/keystone

**Comment by timleslie** [comment] 2021-04-08 23:40
I can confirm that this is a bug in the latest code in the repo. The problem is that the `context` object passed in here is created before the `prisma` object is available (this object is created during the `connect` phase). There is a trivial fix that I'll ship in the next release. For now, using `context.keystone.adapter.prisma` is fine as a workaround. Alternately, in your `onConnect()` function you can do:

```
context = context.sudo()
```

and this will set up `context.prisma` correctly.

**Closed** 2021-04-09 02:59 UTC
