### ISSUE TITLE
4.0 Beta 5 - User Password saved as plain text

### ISSUE THREAD

**Issue by x-dev** [keystonejs/keystone#4023] opened 2017-02-21 07:47 UTC
### Steps to reproduce the behavior
**If new installation**
Create new user object following regular installation procedure by creating an Update record to generate default user

**If upgrading from Beta 0.4**
Create new  or update existing user object, enter desired password and select save. Logout of current admin session and attempt to login with user and password created in previous step

### Expected behavior
Password should be saved as hashed password, user should be able to login with password entered when creating new or updating existing

### Actual behavior
Password is saved as plain text, user cannot login

**Comment by Noviny** [comment] 2017-02-22 04:38
Hi @x-dev, just tried to replicate this, and am still getting hashed passwords. Can you give me any other information on how you are creating the user? Is this just through the admin UI?

**Comment by x-dev** [comment] 2017-02-22 13:11
Hey @Noviny, 

This occurred for me in 2 scenarios:

- using the default user seeding method with an update file
- changing an existing user's password which resulted it to be saved as plain text

I'm not sure what's going on but all of the sudden I can't seem to replicate it. Initially I thought it was an issue running the environment in Heroku but I was experiencing the issue locally as well. 

I'll close this for now as it seems to have resolved itself - thanks!

**Comment by x-dev** [comment] 2017-02-23 18:42
@Noviny,

I'm experiencing this issue again -

This is definitely occurring with v4 Beta 5. Essentially it will work as intended, but then start saving passwords as plain text. I removed the node_modules directory and ran npm install again and that seemed cause the admin to work correctly again. 

Do you have any suggestions as to where I should look to help track down this bug?

**Comment by Noviny** [comment] 2017-02-23 23:58
@x-dev Can you provide me with information on your user model setup?

We encountered a similar issue on the keystone demo site, which was resolved [here](https://github.com/keystonejs/keystone-demo/commit/880eb37003655e4e095437dd518c3799d4bf27fe) however that was because we were protecting the password field, which blocked the hashing of the password.

**Comment by x-dev** [comment] 2017-02-24 02:15
@Noviny,

It's the standard user model that ships as part of the Generator. 

`
var keystone = require('keystone');
var Types = keystone.Field.Types;

/**
 * User Model
 * ==========
 */
var User = new keystone.List('User');

User.add({
	name: { type: Types.Name, required: true, index: true },
	email: { type: Types.Email, initial: true, required: true, index: true },
	password: { type: Types.Password, initial: true, required: true },
}, 'Permissions', {
	isAdmin: { type: Boolean, label: 'Can access Keystone', index: true },
});

// Provide access to Keystone
User.schema.virtual('canAccessKeystone').get(function () {
	return this.isAdmin;
});


/**
 * Relationships
 */
//User.relationship({ ref: 'Post', path: 'posts', refPath: 'author' });


/**
 * Registration
 */
User.defaultColumns = 'name, email, isAdmin';
User.register();
`

**Comment by bassjacob** [comment] 2017-02-24 04:52
@x-dev can you confirm the commands you're running to hit this issue?

Are you seeing it when using the admin ui? or only programmatically?

**Comment by x-dev** [comment] 2017-02-24 05:01
@bassjacob,

When I reopened the issue it was using the Admin UI. Initially however it was either method that would produce the same result. 

If it helps anyone, clearing out the node_modules then running install again seems to resolve it temporarily. Is there something Keystone might be doing on initial boot that would affect the behavior of the password from saving correctly after a period of time?

**Comment by Noviny** [comment] 2017-02-26 22:28
Hey x-dev, does what people are experincing in #4020 look related to what you are experiencing?

**Comment by x-dev** [comment] 2017-02-26 23:49
@Noviny,
Yes, I would say so. What is described in #4020 is essentially what I had
experienced with the update file process

**Comment by x-dev** [comment] 2017-02-26 23:50
@Noviny,
Yes, I would say so. What is described in #4020 is essentially what I had experienced with the update file process

**Comment by Noviny** [comment] 2017-02-28 01:41
@x-dev Couple of other questions, where is this being hosted, can you provide your keystone.js file (I am assuming it's the standard), and just wanted to check what version of keystone is specified in the package.json

**Comment by x-dev** [comment] 2017-02-28 01:56
@Noviny as request:
**keystone.js**

require('dotenv').config({silent:true});

//
const fs = require('fs');
const path = require('path');

// Require keystone
var keystone = require('keystone');
var handlebars = require('express-handlebars');
var morgan = require('morgan')


// Initialise Keystone with your project's configuration.
// See http://keystonejs.com/guide/config for available options
// and documentation.

keystone.init({
	'name': 'Client Name',
	'brand': 'Client Name',

	'sass': 'public',
	'static': ['public'],
	'favicon': 'public/favicon.ico',
	'views': 'templates/views',
	'view engine': 'html',

	'custom engine': handlebars.create({
		layoutsDir: 'templates/views/layouts',
		partialsDir: 'templates/views/partials',
		defaultLayout: 'default',
		helpers: new require('./templates/views/helpers')(),
		extname: '.html',
	}).engine,

	'auto update': true,
	'session': true,
	'session store': 'mongo',
	'auth': true,
	'user model': 'User',
	'mongo': process.env.MONGODB_URI || 'mongodb://localhost/clientdb',
	'cookie secret': process.env.COOKIE_SECRET || 'ArandomStringOfText123465',
	

	'wysiwyg images': true,
	'wysiwyg cloudinary images': true,

	'wysiwyg menubar': true,
	'wysiwyg additional plugins': 'table, visualblocks',
	'wysiwyg additional buttons': 'grid',

	'wysiwyg additional options': {
		'external_plugins': {
			'tiny_grid_scripts': '/js/lib/tinymce/plugins/tinygrid/js/scripts.js',
			'uploadimage': '/js/lib/tinymce/plugins/uploadimage/plugin.min.js'
		},
		'link_list': '/api/page/list',
		'convert_urls': false
	}
});

// Load Models
keystone.import('models');

// Setup common locals for your templates. The following are required for the
// bundled templates and layouts. Any runtime locals (that should be set uniquely
// for each request) should be added to ./routes/middleware.js
keystone.set('locals', {
	_: require('lodash'),
	env: keystone.get('env'),
	utils: keystone.utils,
	editable: keystone.content.editable,
});


// Load your project's Routes
keystone.set('routes', require('./routes'));

// Switch Keystone Email defaults to handlebars
//keystone.Email.defaults.templateExt = 'hbs';
//keystone.Email.defaults.templateEngine = require('handlebars');	

// Configure the navigation bar in Keystone's Admin UI
keystone.set('nav', {
	posts: ['posts', 'post-categories'],
	galleries: 'galleries',
	enquiries: ['Enquiry'],
	users: 'User'
});

//keystone.set('embedly api key', process.env.EMBEDLY_API_KEY);
// Initialize Cloudinary
keystone.set('cloudinary config', { cloud_name: process.env.CLOUDINARY_CLOUD_NAME, api_key: process.env.CLOUDINARY_API_KEY, api_secret: process.env.CLOUDINARY_API_SECRET });

// optional, will prefix all built-in tags with 'keystone_'
keystone.set('cloudinary prefix', 'clientname');

// optional, will prefix each image public_id with [{prefix}]/{list.path}/{field.path}/
keystone.set('cloudinary folders', true);

// optional, will force cloudinary to serve images over https
keystone.set('cloudinary secure', true);


// Start Keystone to connect to your database and initialise the web server
keystone.start({
	onStart: () => {
		console.log('Keystone Started')
	},
	onMount: () => {
		console.log('Keystone mounted')
	}
});

**package.json**

{
  "name": "clientname.com",
  "version": "1.0.0",
  "description": "Marketing site for Client Name",
  "main": "index.js",
  "scripts": {
    "postinstall": "./node_modules/bower/bin/bower install"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/clientname.git"
  },
  "author": "Company Name",
  "license": "ISC",
  "homepage": "https://github.com/clientname#readme",
  "dependencies": {
    "bootstrap-material-design": "^0.5.10",
    "bootstrap-sass": "^3.3.7",
    "bower": "^1.8.0",
    "connect-mongo": "^1.3.2",
    "dotenv": "^2.0.0",
    "express-handlebars": "^3.0.0",
    "handlebars": "^4.0.6",
    "hbs": "^4.0.1",
    "keystone": "^4.0.0-beta.5",
    "keystone-email": "^1.0.5",
    "keystone-storage-adapter-s3": "^1.1.1",
    "lodash": "^4.17.2",
    "moment": "^2.17.1",
    "node-sass": "^4.0.0",
    "node-sass-middleware": "^0.10.0",
    "underscore": "^1.8.3"
  },
  "engines": {
    "node": "6.9.2"
  },
  "devDependencies": {
    "del": "^2.2.2",
    "event-stream": "^3.3.4",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-if": "^2.0.2",
    "gulp-load-plugins": "^1.4.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-sass": "^3.0.0",
    "require-dir": "^0.3.1",
    "run-sequence": "^1.2.2",
    "yargs": "^6.5.0"
  }
}

**Comment by Noviny** [comment] 2017-03-04 14:58
Hi @x-dev, I haven't been able to find anything that looks like it would be causing this, nor anything in your code that makes it obvious. Are you experiencing this locally as well as on heroku?

**Comment by x-dev** [comment] 2017-03-04 15:32
Yes, locally and heroku. 

Unfortunately it's not consistent. For the time being I am forcing heroku to not cache dependencies between builds and if it happens locally I just clear out my node modules and run npm install.

So far this seems to prevent the behavior from reoccurring

**Comment by Noviny** [comment] 2017-03-04 15:53
If it's happening locally, would it be possible for you to privately share the codebase so I can try and reproduce it?

**Comment by x-dev** [comment] 2017-03-07 22:50
@Noviny I have been trying to reproduce this and can't seem to do it - I wanted to send you the complete installation for debug purposes

**Comment by Noviny** [comment] 2017-03-07 22:59
If you send a link to ben@thinkmill.com.au, I'll have a look.

To be clear, you can't reproduce this locally or at all?

**Comment by Noviny** [comment] 2017-03-09 05:01
I'm closing this as a specific user issue, but will keep following it up.

**Closed by Noviny** 2017-03-09 05:01 UTC
