### ISSUE TITLE
Heroku Deployment Broken on 4.0.0-beta.4 (Node-sass & Node 6)

### ISSUE THREAD

**Issue by peterpme** [keystonejs/keystone#3835] opened 2017-01-02 23:17 UTC
Hey everybody, thanks for an awesome project that makes my life easier every day!

I've run into an issue with deploying to Heroku. I thought I solved this by adding a `postinstall` under scripts with `npm rebuild node-sass` but unfortunately that started breaking on me as well.

- Node 6
- Heroku deployment

Here is the issue: 
```
2017-01-02T23:14:02.212355+00:00 app[web.1]: Error: ENOENT: no such file or directory, scandir '/app/node_modules/node-sass-middleware/node_modules/node-sass/vendor'
2017-01-02T23:14:02.212363+00:00 app[web.1]:     at Error (native)
2017-01-02T23:14:02.212364+00:00 app[web.1]:     at Object.fs.readdirSync (fs.js:951:18)
2017-01-02T23:14:02.212365+00:00 app[web.1]:     at Object.getInstalledBinaries (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/extensions.js:121:13)
2017-01-02T23:14:02.212366+00:00 app[web.1]:     at foundBinariesList (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:20:15)
2017-01-02T23:14:02.212367+00:00 app[web.1]:     at foundBinaries (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:15:5)
2017-01-02T23:14:02.212368+00:00 app[web.1]:     at Object.module.exports.missingBinary (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/errors.js:45:5)
2017-01-02T23:14:02.212369+00:00 app[web.1]:     at module.exports (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/binding.js:15:30)
2017-01-02T23:14:02.212370+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/node_modules/node-sass/lib/index.js:14:35)
2017-01-02T23:14:02.212371+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-02T23:14:02.212372+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-02T23:14:02.212372+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-02T23:14:02.212373+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-01-02T23:14:02.212374+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-01-02T23:14:02.212375+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-01-02T23:14:02.212375+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-02T23:14:02.212377+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-sass-middleware/middleware.js:3:12)
2017-01-02T23:14:02.352246+00:00 heroku[web.1]: Process exited with status 1
2017-01-02T23:14:02.365709+00:00 heroku[web.1]: State changed from starting to crashed
```

Any help would be greatly appreciated. You rock!

**Comment by bassjacob** [comment] 2017-01-02 23:22
Hi @peterpme,

Is there a codebase with a reproducible error I can take a look at?

As an aside, what was happening that required rebuilding node-sass on deploy?

**Comment by peterpme** [comment] 2017-01-02 23:23
Hey @bassjacob, thank you for the quick response!

`postinstall` - the same issue was taking place beforehand. Postinstall seemed to have fixed this before. Unfortunately this is no longer the case. The ony way I can get this working is if I bump the node version up / down `6.7`, `6.8`

Code base - a base keystone build with `node 6` I believe. If you give me a few minutes I can create one for ya

Thanks again, you rock!

**Comment by peterpme** [comment] 2017-01-02 23:33
https://github.com/peterpme/keystone-node-sass-heroku-issue-repo

**Comment by bassjacob** [comment] 2017-01-02 23:39
great, thank you. I'll take a look

**Comment by bassjacob** [comment] 2017-01-02 23:55
I was able to deploy that repo to heroku with no problems, and running `npm rebuild node-sass` didn't cause any issues.

This looks like a node-sass issue rather than a keystone issue. Maybe something like https://github.com/sass/node-sass/issues/1579 ?

I'm going to close this issue since it doesn't seem related to keystone, but please reopen if you think it's directly related to keystone.

**Closed by bassjacob** 2017-01-02 23:55 UTC
