### ISSUE TITLE
Initial Schema

### ISSUE THREAD

**Issue by bogdanaks** [keystonejs/keystone#6517] opened 2021-09-09 13:47 UTC
I have a pre-existing postgreSQL database

I would like to use keystone to interact with this base
When describing a lists for my tables, keystone wants to delete my current tables and create new ones

Is it possible to connect to an already created database without clearing it?
I also tried to create a migration through a Prism, but nothing came of it, every time I run the cyston, it writes that the scheme needs to be updated and updates it

![image](https://user-images.githubusercontent.com/36708313/132697645-d61d48ec-bbe7-474d-ab96-627ab43f4b59.png)

**Comment by bogdanaks** [comment] 2021-09-09 14:01
I also using
$ keystone-next prisma db pull
$ keystone-next migrate dev --name initial-migration --create-only
But the second command returns this to me
![image](https://user-images.githubusercontent.com/36708313/132700253-9abb2e6f-0f05-4ac1-abfb-2bb6fb829658.png)

**Comment by bladey** [comment] 2021-09-10 01:08
Hey @bogdanaks, thanks for raising this!

This is not always possible, depending on what you need from your database layer.

Keystone is designed with the fundamental assumption that it will own both the Prisma schema, and from there the database schema as well.

Prisma will attempt to bring your database into sync with the schema by dropping any tables which are not defined in your Prisma schema.

Please let me know if you have any further questions!

**Comment by bogdanaks** [comment] 2021-09-10 10:00
Hi @bladey 
Do I understand correctly that in any case I will have to lose all data in my database?

**Comment by seductorAmadeus** [comment] 2021-09-19 07:26
Hi @bladey 
Does this mean that I cannot use an already prepared Prisma database schema with applied migrations, which is located in another project? Does this mean that I have to design the schema of the whole database from scratch based on the constructions of keystonejs?
I could not find any way how to apply the existing Prisma schema.

**Comment by SpekalsG3** [comment] 2021-12-22 12:22
Hi @bladey

Well, that's a bummer. Keystone6 looks great but this decision is rather questionable, I would say. I understand that Prisma is not under your control but intent to use keystone for an existing database is a good reasoning to consider other ways to work with database.

I guess the arising question is Would you consider using another orm or self written sql request generation in the near future?

**Comment by bladey** [comment] 2021-12-22 23:35
Hi @bogdanaks, @seductorAmadeus, and @SpekalsG3 - thanks for the feedback, and apologies for the delay in responding.

I'll run this by the team and get a response back as soon as I can.

**Comment by satinjeet** [comment] 2022-02-10 22:36
This is a great use case, I am also planning to use Keystone as a UI and primary interface for managing a database that is working with a headless API.
If there would be a way to ignore or skip on the models that you do not want to manage rather than having the tables dropped, it would be super useful, simply because this is a scalable solution that I am looking forward to using in multiple places.

**Comment by dcousens** [comment] 2022-02-15 05:34
I think this is a duplicate of https://github.com/keystonejs/keystone/discussions/7233 - please follow up discussion there.

**Closed by dcousens** 2022-02-15 05:34 UTC
Labels: :earth_asia: i/community
