### ISSUE TITLE
Relationship many not saving on mongoose

### ISSUE THREAD

**Issue by ashinzekene** [keystonejs/keystone#1816] opened 2019-10-23 12:43 UTC
# Bug report

field with relationship many is not being set in create and update with mongoose adapter

## Describe the bug
This does not work
```js
subCategories: {
  type: Relationship,
  ref: 'FAQCategory',
  many: true,
  schemaDoc: 'Categories under this category',
}
```
while
```js
subCategories: {
  type: Relationship,
  ref: 'FAQCategory',
  schemaDoc: 'Categories under this category',
}
```
this works.

**Request**
```json
{"operationName":"update","variables":{"id":"5daedfe6dcd3f7006ebac7e5","data":{"subCategories":{"disconnectAll":true,"connect":[{"id":"5daedfdedcd3f7006ebac7e4"},{"id":"5daf2f9965880c00ab85c9e1"}]}}},"query":"mutation update($id: ID!, $data: FAQCategoryUpdateInput) {
  updateFAQCategory(id: $id, data: $data) {
    id
    __typename
  }
}
"}
```
**Response**
```
{
  "data": {
    "updateFAQCategory": { "id": "5daedfe6dcd3f7006ebac7e5", "__typename": "FAQCategory" }
  }
}
```

**Comment by MadeByMike** [comment] 2019-10-23 22:24
@ashinzekene could you share the list for `FAQCategory` so that I can try and reproduce?

**Comment by ashinzekene** [comment] 2019-10-24 09:55
Here it is @MadeByMike 


```js
keystone.createList('FAQCategory', {
  labelField: 'title',
  schemaDoc: 'FAQ Categories',
  fields: {
    title: {
      type: Text,
      required: true,
    },
    meta: {
      type: Text,
      required: true,
      schemaDoc: 'Meta data',
    },
    subCategories: {
      type: Relationship,
      ref: 'FAQCategory',
      many: true,
      schemaDoc: 'Categories under this category',
    },
  },
})
```

**Comment by singhArmani** [comment] 2020-01-29 04:09
@ashinzekene: I was able to get it working using **MongooseAdapter** for `many:true` relationship. Also, the update query was working as intended. 

@timleslie: On the contrary, with **KnexAdapter**, the Keystone app was failing to start up when trying to create a list having a many relations with self. 

```js
keystone.createList('FAQCategory', {
  labelField: 'title',
  schemaDoc: 'FAQ Categories',
  fields: {
    title: {
      type: Text,
      required: true,
    },
    meta: {
      type: Text,
      required: true,
      schemaDoc: 'Meta data',
    },
    subCategories: {
      type: Relationship,
      ref: 'FAQCategory',
      many: true,
      schemaDoc: 'Categories under this category',
    },
  },
});
```
Running `yarn dev` gives the following error while trying to connect to database: 

```js
Error: create table "public"."FAQCategory_subCategories" ("FAQCategory_id" integer not null, "FAQCategory_id" integer not null) - column "FAQCategory_id" specified more than once
 ...
  errors: {
    KnexAdapter: error: column "FAQCategory_id" specified more than once
   ...
  }
```
Additionally, I was able to spin the app without any error by removing the `many:true` relationship.

**Comment by singhArmani** [comment] 2020-01-29 05:21
Closing this issue as it couldn't be reproduce with the MongooseAdapter as mentioned. The KnexAdatper issue can be traced here #2297.

**Closed by singhArmani** 2020-01-29 05:21 UTC
Labels: bug, needs-clarification

**Comment by mxia** [comment] 2020-05-06 00:29
I'm experiencing this issue as well with MongooseAdapter. Here is my JS file:

```
const { Checkbox, Integer, Relationship, Text } = require("@keystonejs/fields");
const { atTracking } = require("@keystonejs/list-plugins");

module.exports = {
  fields: {
    name: {
      type: Text,
      isRequired: true
    },
    content: {
      type: Relationship,
      ref: "Subtopic",
      many: true
    },
    mostPopular: {
      type: Relationship,
      ref: "Subtopic",
      access: {
        read: true,
        create: false,
        update: false
      }
    },
    categories: {
      type: Relationship,
      ref: "Category",
      label: "Subcategories",
      many: true
    },
    order: {
      type: Integer,
      defaultValue: 0
    },
    enable: {
      type: Checkbox,
      defaultValue: false
    }
  },
  plugins: [atTracking()]
};
```
The `Subtopic` is another model we defined. In admin UI, I'm not able to see the values for `content` and `categories` that already exist in the MongoDB, and when I updated and saved from admin UI, they're reflected correctly in the UI, but the values are not updated in the actual DB. It's as if the fields are not connected between Mongo and admin UI when `many: true` is defined.

**Comment by mxia** [comment] 2020-05-06 05:48
@singhArmani I'm seeing the same issue with field not being saved to Mongoose when it has `many: true`. I narrowed it down and reproduced it by simply adding the following to index.js of the `ToDo` sample project:

```
keystone.createList('TestUser', {
  fields: {
    name: {
      type: Text
    },
    todos: {
      type: Relationship,
      ref: 'Todo',
      many: true
    }
  }
});
```

When I created a new TestUser from the admin UI and added a few Todos to its `todos` field, the admin UI shows the relationship fine, but when I queried from mongo shell, the TestUser object contains no `todos` attribute:

```
> db.testusers.find()
{ "_id" : ObjectId("5eb24e6c972b2ecc30716398"), "name" : "user 1", "__v" : 0 }
```
