### ISSUE TITLE
Timestamps appear differently in Admin UI

### ISSUE THREAD

**Issue by ddaddy** [keystonejs/keystone#3044] opened 2016-06-15 21:48 UTC
I have a user field set to DateTime like this
`createdAt: { type: Types.Datetime, default: Date.now },`

and when viewed in the admin User list a record appears like this:
<img width="204" alt="screen shot 2016-06-15 at 22 43 45" src="https://cloud.githubusercontent.com/assets/1425808/16098475/0ed663ce-334b-11e6-8172-b3642600cc7b.png">

yet when I click the user, it shows a different time like this:
<img width="621" alt="screen shot 2016-06-15 at 22 43 58" src="https://cloud.githubusercontent.com/assets/1425808/16098483/18ae622a-334b-11e6-910a-915dcd8f2b10.png">

The actual timestamp in the db is:
`"createdAt" : ISODate("2016-06-15T23:26:32Z"),`

**Comment by jstockwin** [comment] 2016-06-16 12:13
I think this may be a duplicate of #1487 and/or #1345. Perhaps it was fixed in master but not 0.3?

**Comment by ddaddy** [comment] 2016-06-16 12:20
Yes they look the same. And although marked Critical, it's still not fixed in 3.19

**Comment by ddaddy** [comment] 2016-06-19 15:25
And just to confirm, it also saves a new time in the field when any changes are made to the record, which is a serious bug.

**Comment by mxstbr** [comment] 2016-06-20 12:48
> Perhaps it was fixed in master but not 0.3?

@JedWatson will know more about that, any input here?

**Comment by JedWatson** [comment] 2016-06-26 11:31
I _swear_ we've fixed this one before. Really need to work out how to set up some unit tests that test for the server and client being in different timezones, I suspect this came back with a PR or something. It's _way_ to easy to miss for such a critical bug.

@mxstbr no input other than that we need to get on this and patch 0.3 with a fix

**Comment by ddaddy** [comment] 2016-07-15 09:35
Did a patch for this ever get done?
Whenever I make changes to an object via the admin panel, it always fires my code that checks for a date field being new, even when it hasn't been changed, because the admin panel changes the current saved time by an hour.

**Comment by ttsirkia** [comment] 2016-07-24 22:56
It was fixed in #2894 but only for 0.4. There are two open (possibly outdated) pull requests for 0.3 that were never merged.

**Comment by dijs** [comment] 2016-08-04 12:47
I am also seeing inconsistencies in datetimes before and after saving. It would be amazing to get a fix.

Currently we are having to save our time's correctly by adding 5 hours to them...

**Comment by dijs** [comment] 2016-08-15 23:25
Any progress here?

**Comment by mxstbr** [comment] 2016-08-16 02:55
Sorry, we're very very focussed on getting v4 finished at the moment, (beta release this/next week hopefully) so no progress so far.

**Comment by mollfrey** [comment] 2016-08-30 19:53
Argh.  Just ran into this.  Running v0.3.x
Any hope for a merge soon?

**Comment by waltonryan** [comment] 2016-11-02 19:10
Ran into this issue as well. Any temporary fix we could do on our side before the PRs are merged?

**Comment by valeriy-devpronet** [comment] 2016-11-03 19:26
This is not funny, timezone issue is the critical bug. I do not understand why stable version did not get this fix yet, but unstable version 0.4 has that? 
Every time I'm saving item with Date it shifts to +2h. I can't handle that at all, hooks in mongoose did not catch that Date was set up by user. Any work around?

**Comment by dijs** [comment] 2017-08-19 09:33
Any updates on timezone issues yet?

**Comment by Noviny** [comment] 2017-09-22 14:59
I talked about this in #3012. The resolution is we are releasing one final version of 3 that resolves this, though note we will not be supporting 3 after this final patch. We recommend upgrading, for which you can find a guide [here](http://keystonejs.netlify.com/guides/v-0-3-to-v-4-0-upgrade-guide)

**Closed by Noviny** 2017-09-22 14:59 UTC
Labels: bug
