### ISSUE TITLE
4.0.0-beta5: WYSIWYG cloudinary images config breaks text editor

### ISSUE THREAD

**Issue by bplmp** [keystonejs/keystone#4228] opened 2017-04-20 18:18 UTC
### Expected behavior
Upon adding `'wysiwyg cloudinary images': true` to `keystone.js` configs, it should load a plugin for uploading Cloudinary Images on the WYSIWYG editor.

### Actual/Current behavior
The WYSIWYG editor doesn't load, and the server throws this error: `GET /keystone/js/lib/tinymce/plugins/uploadimage/plugin.min.js 404 18.162 ms`

**Comment by bplmp** [comment] 2017-04-20 19:19
Maybe this commit was what caused it: https://github.com/keystonejs/keystone/commit/940b77fdae26a2f70d8c30f1b4ca638be4bad839

It removed the `uploadimage` plugin from the `/js/lib/tinymce/plugins/` folder.

**Comment by rguillet** [comment] 2017-04-21 13:08
Duplicate with https://github.com/keystonejs/keystone/issues/3529

(They provide a temporary fix)

**Comment by stennie** [comment] 2018-06-24 08:03
Closing as duplicate of #3529

**Closed by stennie** 2018-06-24 08:03 UTC
Labels: 4.0-release-candidate, bug
