### ISSUE TITLE
ETA on 4.0 release

### ISSUE THREAD

**Issue by nodesocket** [keystonejs/keystone#3838] opened 2017-01-04 06:21 UTC
I just stumbled across Keystone and it looks like a perfect fit for my consultancy business. I'd like to know though if there is an eta on releasing **Keystone 4.0** in production? I'd like to start on 4.0, but if there is still lots of work left, I should probably stick with the latest stable version.

**Comment by bassjacob** [comment] 2017-01-04 07:09
Hi @nodesocket,

That's great to hear. We think it's a great fit as well. There isn't a concrete ETA for 4.0, but we're focusing on the remaining issues and hoping to have it out soon. The only pieces left are some minor issues, updating the documentation and some demos.

4.0 is in beta now, and stable enough that we're using it in production on a few projects. Are there any issues or features in the 4.0 pipeline that you need before you'd consider using it?

**Comment by nodesocket** [comment] 2017-01-04 20:55
@bassjacob thanks for the reply. In terms of features missing from 4.0 I don't think that will be the case. Mostly just interested in stability and getting started, documentation.

**Comment by simonwidjaja** [comment] 2017-01-17 07:48
Is there a solid demo project we can use to start digging into 4.0? @bassjacob you said that you have some 4.0 projects in production already. Are they open? Without proper documentation a demo project would be the perfect starting point. (SydJS did a perfect job for me when I started with keystone...)

**Comment by nodesocket** [comment] 2017-01-23 01:27
Does the getting started guide (http://keystonejs.com/getting-started/) still work for 4.0, or is installation different now?

**Comment by nodesocket** [comment] 2017-01-23 02:04
It appears the getting started guide still installs 3.0. How do I install and get started with 4.0?

Thanks.

**Comment by internetErik** [comment] 2017-01-23 02:54
@nodesocket I got started by looking at the keystone demo site: https://github.com/keystonejs/keystone-demo

**Comment by htor** [comment] 2017-03-21 09:23
@bassjacob 
I don't know know much about developing open source projects like this, but would it be an idea to freeze new feature requests and instead focus on writing docs and stabilising v4 for production? Are there any roadmaps at the moment for what is going into v4 and what is not?

Looks like v4 is sort of done, but there is too much noise around small features.

**Comment by thejameskyle** [comment] 2017-03-22 03:51
v4 has a small number of remaining blockers. We want to make sure we don't make regressions from v3. At the same time documentation remains a focus. We'll be making a push to release as soon as we can.

I'm going to close this because there are specific issues for things that need to get done for v4 (which I'm continuing to organize a bit more).

**Closed by thejameskyle** 2017-03-22 03:51 UTC

**Comment by ghuroo** [comment] 2017-03-24 10:41
If it helps, I am using v4 beta5 in all my production projects, and so far it seems stable enough :)
Ofc there are many features missing, so I have a few workarounds, but it still does the job perfectly 👍
