### ISSUE TITLE
[0.3] validator errors incorrectly parsed

### ISSUE THREAD

**Issue by creynders** [keystonejs/keystone#2586] opened 2016-04-07 09:49 UTC
It isn't entirely clear whether something changed in KS or mongoose, but now if model fails validation the message shown in userland hides the details:

```
There was an error creating the new Post:
Post validation failed
```

Anybody any idea where the change was? Did mongoose start spewing out Errors with a different structure, or?

This is with mongoose v4.4.4.

**Comment by webteckie** [comment] 2016-04-07 10:15
These are the kinds of regressions we're trying to prevent with e2e...you just don't know something broke until some time later...very expensive! :-)

**Comment by creynders** [comment] 2016-04-07 10:25
Tell me about it! ;)

**Comment by creynders** [comment] 2016-04-07 10:42
I'm pretty sure this commit baff5604292ee77d1391d96d2e8474ed3e4a629d probably fixed some validation errors, but introduced a new one.
If you [look at the diff](https://github.com/keystonejs/keystone/commit/baff5604292ee77d1391d96d2e8474ed3e4a629d#diff-1216fa2cb9fb0cbc959b8bdba7272512R154) you can see there used to be two types of errors: "ValidatorError" and "ValidationError" (as it is the case in Mongoose, a ValidationError contains multiple ValidatorErrors in its `errors` prop), however this commit uses only ValidatorError.

**Comment by creynders** [comment] 2016-04-07 10:55
Fixed it in my own fork, be reverting the error names. I have no idea whether this breaks something else, i.e. the bug the original commit was trying to fix in the first place...

**Comment by creynders** [comment] 2016-04-07 11:40
Of course it wasn't as simple as that ... It didn't work by reverting the error names, but I thought it did. Turns out I tested the wrong situation. The buggy situation is the following: when field validation fails with a custom validator for an `initial` field, while all other fields validate... Phew...

**Comment by mxstbr** [comment] 2016-04-29 17:00
Since this is fixed (thanks @creynders), I'll close the issue!

**Closed by mxstbr** 2016-04-29 17:00 UTC
