### ISSUE TITLE
Error on apply updates from file

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#2162] opened 2016-01-26 07:57 UTC
I see these error on first start when apply updates from `/updates` folder:
```
Applying update 1.0.0-users-companies...
TypeError: callback is not a function
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
```
I use [ketstone-test-project](https://github.com/keystonejs/keystone-test-project) 
I think it is because the updates file doesn't contain callback:
```
exports.create = {
	User: [
		{ 'name.first': 'Admin', 'name.last': 'User', email: '...', password: '...', isAdmin: true }
	]
};
```
Maybe after this PR #2147 I need to add callback, but don't know where.
I will try the long-hand version, short version doesn't applies.

**Comment by samkuhn** [comment] 2016-01-28 14:58
I see the same.. on a fresh Ubuntu server with the latest 0.4 version from master. Any luck fixing it w01fgang?

**Comment by samkuhn** [comment] 2016-01-28 15:10
I can confirm that a version from the 24th (2a68e2113e27e5b147bcd382ce1d354a9972c75f) creates the database user ok. So a later commit must have broken the update functionality.

Possibly PR #2147 as w01fgang suspects.. I would investigate but big deadline! :)

**Comment by w01fgang** [comment] 2016-01-28 16:32
This still works
```
'use strict'

let keystone = require('keystone')
let async = require('async')
let User = keystone.list('User')

let admins = [
	{ email: 'admin@email.com', password: 'changeOnStart', name: { first: 'Admin', last: 'User' } },
{ email: 'another@email.com', password: 'changeOnStart', name: { first: 'Another', last: 'Admin' } }
];

function createAdmin(admin, done) {

	var newAdmin = new User.model(admin);
	newAdmin.isAdmin = true;
	newAdmin.save(function(err) {
		if (err) {
			console.error("Error adding admin " + admin.email + " to the database:");
			console.error(err);
		} else {
			console.log("Added admin " + admin.email + " to the database.");
		}
		done(err);
	});

}
```

**Comment by webteckie** [comment] 2016-01-29 03:27
I can also confirm that this is broken very recently (last few days)!  This is a blocker for me as I have fairly complex updates files I constantly run.  If it was a breaking change somewhere please inform what it is that should be changed.

cc: @JedWatson

**Comment by andrewlinfoot** [comment] 2016-01-29 21:54
Yep, was a regression from https://github.com/keystonejs/keystone/pull/2147. Sorry about that. Check out https://github.com/keystonejs/keystone/pull/2196. Should have fixed this. Let me know if I missed anything.

**Comment by webteckie** [comment] 2016-02-07 14:33
@w01fgang i believe this can be close.  Please verify the issue is resolved with latest and close, if so.

**Comment by mxstbr** [comment] 2016-03-15 06:37
I'll close this issue as it appears fixed, if you're still running into this problem feel free to comment/reopen!

**Closed by mxstbr** 2016-03-15 06:37 UTC
