### ISSUE TITLE
Google login for AdminUI

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2824] opened 2020-04-24 13:16 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Our client has asked us if it would be possible to implement Google login for the AdminUI.  I don't know if that is something that we can do apart from Keystone, but if not, perhaps it could be added as a future feature for the AdminUI.

## Describe the solution you'd like

See above

## Describe alternatives you've considered

Writing it ourselves.  Is this possible?  How might we do so?

**Comment by MadeByMike** [comment] 2020-06-03 06:02
Duplicate of #2334

**Closed by MadeByMike** 2020-06-03 06:02 UTC
