### ISSUE TITLE
Select options can't include - 

### ISSUE THREAD

**Issue by dilignt** [keystonejs/keystone#2349] opened 2020-02-07 11:09 UTC
# Bug report

## Describe the bug

With the Select field type, if the options list contains a - sign the app fails with 

`'Syntax Error: Invalid number, expected digit but got: "l".'  
`

where l is the first letter after the - sign in the option

## To Reproduce

Create a Select field in a list with options that have a minus sign in them e.g

```
module.exports = {
    fields: {
        type: { type: Text },
        direction: { type: Select, options: ['vertical', 'horizontal'] },
        orient: { type: Select, options: ['left', 'right', 'top', 'bottom', 'top-left', 'top-right', 'bottom-left', 'bottom-right', 'none']}
    }
};
```

## Expected behaviour

Should start keystone and provide the options, but I need to comment out `orient` above for it to work

## System information

- OS:  Windows 10, node version 13.5.0

**Comment by MadeByMike** [comment] 2020-02-12 21:17
This is definitely an issue but is a duplicate of #1768

**Comment by MadeByMike** [comment] 2020-02-12 21:18
Thanks for reporting, this additional information will help and lets us know it's effecting more people.

**Closed by MadeByMike** 2020-02-12 21:17 UTC
