### ISSUE TITLE
TinyMCE Error: remove is not a function

### ISSUE THREAD

**Issue by pavethiran** [keystonejs/keystone#3844] opened 2017-01-05 15:52 UTC
### Steps to reproduce the behavior
Use Types.HTML in a List.

### Expected behavior
No Error on change

### Actual behavior
Error on every change on the page

**Comment by JedWatson** [comment] 2017-01-10 06:14
As per my comment on #3845 I can't replicate this

**Comment by thejameskyle** [comment] 2017-03-24 20:19
Closing since this has sat for awhile without reproduction.

**Closed by thejameskyle** 2017-03-24 20:19 UTC
Labels: needs reproduction
