### ISSUE TITLE
Not able to save the document

### ISSUE THREAD

**Issue by tusharmath** [keystonejs/keystone#1413] opened 2015-05-19 06:18 UTC
If a collection has an attribute, whose type is changed. For instance from `string` to `number` I am not able to save that document even after updating the content to a value of number type.

**Comment by morenoh149** [comment] 2015-05-19 18:54
So you have a fieldType of one type. And you're trying to store data of a different type?

**Comment by tusharmath** [comment] 2015-05-19 20:52
No I am trying to save the data of the same type, but if the data loaded is of a different type then I am neither able to edit it or save the changes. For example: Say the type is `number`  but the data inside mongodb is `string` (assume insertion was done without referring to Keystone's collections), then that whole document can not be edited/saved.

**Comment by morenoh149** [comment] 2015-05-19 20:56
Sounds like we need some casting.

**Comment by dcousens** [comment] 2015-05-20 02:14
@tusharmath could you provide a code example?

**Comment by tusharmath** [comment] 2015-05-20 14:26
I have a collection doctor, which is designed to be look like this.

```js
{
  name: {type: Types.String},
  experience: {type: Types.String}
}
```

Next, I upload the following json
```json
{
"name": "Doc1",
"experience": "XXYYSS"
}
```
All cool till now.

Now, I change the model as follows
```js
{
  name: {type: Types.String},
  experience: {type: Types.Number}
}
```
And try to edit the saved document. And I am not able to edit, no matter what value I set for experience.

**Comment by morenoh149** [comment] 2015-05-20 20:00
@tusharmath maybe you're asking too much from keystone. How about you keep the `String` fieldtype and perform the casting in your application code. You data model shouldn't be mutating like this IMO.

**Comment by tusharmath** [comment] 2015-05-20 20:05
The ideal behaviour should be to atleast let the user edit the content so that he can converit it into `number`. At the moment the text field remains empty and no matter what value I put in, it's ignored.

I understand that one can fix it from the application code, but one should also be able to edit the data and fix.

**Comment by morenoh149** [comment] 2015-05-20 20:28
Correct me if I'm wrong, but the locking was caused by changing the data model after the fact. How about you don't do that from now on.

Now on to editing your information now. Maybe we can discuss on gitter.

**Comment by tusharmath** [comment] 2015-05-21 06:33
@morenoh149 Sure. Let me know when we can talk. What I am really trying to say is that data, sometimes is imported using some other methodology (python script for instance) and gets screwed up at the time of import. I should still be able to edit from the ui and change.

**Comment by creynders** [comment] 2015-05-21 07:58
@tusharmath it's not keystone that's exploding, but mongoose/mongodb. And it's rather impossible to foresee potential data import screwups. Data validation should happen before import, not after.

Closing this, since it's not a real issue.

**Closed by creynders** 2015-05-21 07:58 UTC
Labels: bug

**Comment by tylkomat** [comment] 2015-05-21 08:01
In your case you should use the update functionality of keystonejs to alter the data in the database. But for this you can not rely on mongoose which is the problem why it breaks, but have to use play mongodb queries to alter your data. 

I didn't test it. But I would select the data via mogodb query and then create a new model with the updated values and save it.
