### ISSUE TITLE
custom-field-view example not running correctly

### ISSUE THREAD

**Issue by xenobytezero** [keystonejs/keystone#7246] opened 2022-01-31 00:27 UTC
# To Repro

With NodeJS v16.13.2

1. Checkout Keystone source (29c6a45fd5fef8ea27f5d051b4fb5d660492aad5)
2. `cd examples\custom-field-view`
3. `npm install`
4. `npm run dev`

# Log

```
✨ Starting Keystone
⭐️ Dev Server Starting on http://localhost:3000
⭐️ GraphQL API Starting on http://localhost:3000/api/graphql
✨ Generating GraphQL and Prisma schemas
✨ sqlite database "keystone-example.db" created at file:./keystone-example.db
✨ Your database is now in sync with your schema. Done in 815ms
✨ Connecting to the database
✨ Creating server
✅ GraphQL API ready
✨ Generating Admin UI code
✨ Preparing Admin UI app
event - compiled client and server successfully in 7.4s (1307 modules)
✅ Admin UI ready
wait  - compiling /api/__keystone_api_build...
event - compiled client and server successfully in 436 ms (1322 modules)
wait  - compiling...
error - ./pages/_app.js:10:0
Module not found: Can't resolve '../../fields/related-links/components'
   8 | import * as view5 from "../../../node_modules/@keystone-6/core/fields/types/timestamp/views";
   9 | import * as view6 from "../../../node_modules/@keystone-6/core/fields/types/json/views";
> 10 | import * as view7 from "../../fields/related-links/components";
  11 | 
  12 | var adminConfig = {};
  13 | 

https://nextjs.org/docs/messages/module-not-found
```

First noticed this in my own app, can reproduce in the core example.

**Comment by Noviny** [comment] 2022-01-31 23:28
Hi @xenobytezero 

The reproduction you have given I would expect to fail. Keystone as a project is set up as a monorepo, and our examples run from within the repo require doing the monorepo install.

```
yarn fresh
cd examples/custom-field-view
yarn dev
```

I'm guessing by your `\` you are on a windows machine?

**Comment by xenobytezero** [comment] 2022-02-01 00:35
Tried as you suggested with the following from the checkout root
```
npm install
cd examples/custom-field-view
npm run dev
```
... and your right, did not get the issue. Is there some extra step I'm missing between the `keystone-next`  -> `keystone-6` upgrade that I am missing? My custom view was working fine before then?

Also yes I am on Windows.

**Comment by xenobytezero** [comment] 2022-02-01 02:16
Can confirm that replacing `require.resolve` with `path.join(process.cwd(), ...)` fixes the issue.

Something is happening with the `require.resolve` with HMR that is breaking things.

**Comment by yoiang** [comment] 2022-02-01 15:39
@xenobytezero , your ask to replace `require.resolve` with `path.join(process.cwd(), ...)` did resolve the issue for me with a custom component within my repo I made based off of the example, thank you!

**Comment by JMLX42** [comment] 2022-02-13 08:37
>  So the qustion back to you guys: Did you devlop your KeystoneJS project on Windows, Linux or MacOS?

I'm using Ubuntu 21.10 and `require.resolve` does not work but computing the path (ex: `path.join(process.cwd(), ...)`) works.

**Comment by bastiW** [comment] 2022-03-03 18:54
I was trying out the custom field stars from the exmple. When I was running the example it works with `require.resolve('./views')` but in my own project it only worked with
```ts
      views: path.join(process.cwd(), '/stars-field/views.tsx') ,

```

**Comment by dcousens** [comment] 2022-03-07 02:21
This should be fixed in https://github.com/keystonejs/keystone/pull/7289/files#diff-cee06c96694bb496de98273ea768f0d573fae72aa1ecb4bd06baab53c004c533R43

**Closed by dcousens** 2022-03-07 02:21 UTC
Labels: :earth_asia: i/community

**Comment by WenLonG12345** [comment] 2022-07-31 15:56
> I was trying out the custom field stars from the exmple. When I was running the example it works with `require.resolve('./views')` but in my own project (almost plain created through npx) it only worked with
> 
> ```ts
>       views: path.join(process.cwd(), '/stars-field/views.tsx') ,
> ```

Thanks god! this works for me!
