### ISSUE TITLE
Quickstart "yarn create keystone-app" failing

### ISSUE THREAD

**Issue by kierangilliam** [keystonejs/keystone#2170] opened 2019-12-30 19:57 UTC
# Bug report

```
Kierans-MBP:AT kierangill$ yarn create keystone-app my-app
yarn create v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-keystone-app@1.4.0" with binaries:
      - create-keystone-app
[############################################################] 60/60(node:39667) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Colorize (/Users/kierangill/.config/yarn/global/node_modules/cfonts/lib/index.js:328:69)
    at AddLetterSpacing (/Users/kierangill/.config/yarn/global/node_modules/cfonts/lib/index.js:412:17)
    at Render (/Users/kierangill/.config/yarn/global/node_modules/cfonts/lib/index.js:788:14)
    at Object.Say [as say] (/Users/kierangill/.config/yarn/global/node_modules/cfonts/lib/index.js:884:15)
    at showWelcomeMessage (/Users/kierangill/.config/yarn/global/node_modules/create-keystone-app/lib/show-welcome-message.js:4:10)
    at /Users/kierangill/.config/yarn/global/node_modules/create-keystone-app/bin/cli.js:14:3
    at Object.<anonymous> (/Users/kierangill/.config/yarn/global/node_modules/create-keystone-app/bin/cli.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:39667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.65s.
```

## Describe the bug

`npm init keystone-app my-app` and`yarn create keystone-app my-app` fail with error `UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined`

## Expected behaviour

Template to be created.

## System information

MacOS Catalina: 10.15.2 (19C57)
Brew: 2.2
Node: 10.2.1 OR 12.13.1
NVM: 0.34.0
Mongo Community: 4.2

**Comment by krthr** [comment] 2019-12-30 22:05
Same in npm

**Comment by theGiantOtter** [comment] 2019-12-31 02:27
#2164

**Comment by ataiana** [comment] 2020-01-01 18:55
same here

**Comment by jstilwell** [comment] 2020-01-01 20:21
same

**Comment by dominikwilkowski** [comment] 2020-01-08 19:55
Closing as duplicate of #2164

**Closed by dominikwilkowski** 2020-01-08 19:55 UTC
