### ISSUE TITLE
Create form exceeds screen height, has no scroll when too many fields have initial: true

### ISSUE THREAD

**Issue by steevsachs** [keystonejs/keystone#4025] opened 2017-02-21 19:09 UTC
### Steps to reproduce the behavior
Create a Keystone List with a high number of fields (~20) with the property `initial` set to `true`.
Access the Keystone admin interface.  
Attempt to create a new document of that List type.  

### Expected behavior
A lightbox will pop up including a righthand scroll bar allowing access to all initial fields and the Create and Cancel buttons.

### Actual behavior
The resulting create lightbox exceeds screen height but includes no scroll.
![image](https://cloud.githubusercontent.com/assets/1848220/23180400/51541bc4-f83f-11e6-967e-de20d3c2c3ff.png)

**Comment by VinayaSathyanarayana** [comment] 2017-05-27 09:52
Faced the same issue ...

**Comment by androidfanatic** [comment] 2017-12-28 07:23
+1 Facing similar issue. I'd like it if there was an option to render create forms on another page instead of inside a modal.

**Comment by morenoh149** [comment] 2018-01-26 06:14
closing as duplicate of https://github.com/keystonejs/keystone/issues/3822

**Closed by morenoh149** 2018-01-26 06:14 UTC
