### ISSUE TITLE
Boolean set to false if set as hidden! Serious Bug.

### ISSUE THREAD

**Issue by ddaddy** [keystonejs/keystone#2999] opened 2016-06-06 14:22 UTC
I have several Boolean fields in the Users model.
If any are set to be hidden and you edit a User and tick/untick a checkbox, all hidden Boolean's are set to false!

Obviously this is a serious bug, as if you have `isAdmin` set as hidden then it locks the user out of the Admin control panel completely.

**Comment by jstockwin** [comment] 2016-06-06 14:29
@ddaddy This looks like a duplicate of #2946 to me?

**Comment by ddaddy** [comment] 2016-06-06 14:53
Ah yes, it seems so.
Sorry about that. I had my admin access removed because of this bug so rushed straight here to tell everyone.

**Comment by jstockwin** [comment] 2016-06-06 14:56
In that case I'll close this issue, but feel free to try and bump #2946. I'm afraid I'm too busy with other things to have a look, but hopefully someone will get round to it.

**Closed by jstockwin** 2016-06-06 14:56 UTC
