### ISSUE TITLE
0.3.7: AdminUI broken

### ISSUE THREAD

**Issue by wmaurer** [keystonejs/keystone#1334] opened 2015-04-23 13:19 UTC
I've been developing against 0.3.5, and when deploying I found the Admin UI broken.

So I've installed 0.3.7 locally using keystone-generator, and the Admin UI is also not working. For example, when I click on a User, I get presented the following page:
![image](https://cloud.githubusercontent.com/assets/2899448/7297784/6ca1308a-e9cb-11e4-97a0-704db8671f48.png)

I see in the release notes the following:

- changed; switched from pre-built admin scripts to pre-built browserify packages and on-demand admin UI scripts w/ browserify-middleware

I have no idea about browserify, and I can't find any documentation to hint at what I need to change.
What do I need to do to get things working again, please?

Cheers

**Comment by GlennGeenen** [comment] 2015-04-23 13:41
I experience the same issue. Node log says:

Note: The code generator has deoptimised the styling of "/node_modules/moment/moment.js" as it exceeds the max of "100KB".

I also get a javascript error in my console:
Uncaught Error: Cannot find module '/node_modules\keystone\node_modules\bytes/lib/byte-convert.js'

**Comment by creynders** [comment] 2015-04-23 13:48
I think all of this is related to/duplicate of #1332. Closing this for now, if it turns out to be unrelated, we'll re-open.

**Closed by creynders** 2015-04-23 13:48 UTC

**Comment by JedWatson** [comment] 2015-04-23 13:52
@wmaurer @GlennGeenen apologies for the inconvenience, this was a problem in an upstream package that broke the browserify build; I've deployed a comprehensive fix and published it as `v0.3.8` so if you update everything should work again.

**Comment by wmaurer** [comment] 2015-04-23 13:56
@JedWatson wow, thanks for the quick response! Everything works again now.

**Comment by JedWatson** [comment] 2015-04-23 13:58
No problem, I don't like it when Keystone is broken! Glad it's fixed for you :)

I submitted a PR to `bytes` to address the core issue, check out visionmedia/bytes.js#21 if you're interested.
