### ISSUE TITLE
Signing in, out creates new session

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2417] opened 2016-03-14 14:20 UTC
We're working on an e-commerce site powered by Keystone and have just run into a major problem.  We have a shopping cart that is tied to the session but it's not surviving user login state changes.  This is bad because the user cart is wiped out with the session being reset.  Is there something we can do to work around this?

**Comment by creynders** [comment] 2016-03-14 16:38
I'm certainly no e-commerce expert, but isn't that the expected behaviour? Otherwise it wouldn't be session-tied. I think you want a user-tied shopping cart e.g. Amazon?

**Comment by emaddoma** [comment] 2016-03-14 21:13
While I don't believe there is a one-size-fits-all e-commerce experience, I would argue it's not necessary to regenerate the entire session with authentication changes.  We ended up writing our own routes/views to get around the Keystone behavior.

**Comment by mxstbr** [comment] 2016-03-15 04:53
> We ended up writing our own routes/views to get around the Keystone behavior.

I'll close this issue since this seems to be a very specialised requirement that can be implemented. Let us know if you think this is a bug or a feature we should support and we'll take another look!

**Closed by mxstbr** 2016-03-15 04:53 UTC
Labels: question
