### ISSUE TITLE
Admin UI: Support passport auth

### ISSUE THREAD

**Issue by zenflow** [keystonejs/keystone#2658] opened 2020-04-05 07:36 UTC
# Feature request

## Description

Currently only password auth is supported in the Admin UI:

> [...] only password auth is currently supported in the admin UI
@molomby https://github.com/keystonejs/keystone/issues/2581#issuecomment-607566838

It would be great to be able to also use **passport** auth with the Admin UI.

Here is some discussion of this issue in a *related* issue: https://github.com/keystonejs/keystone/issues/2581#issuecomment-607040710

## Proposed solution

See #2657 , specifically these commits https://github.com/keystonejs/keystone/pull/2657/files/a30f2547b21335f48dc564ee4a75914dc80c84e6..f06410ac7c533a14158b03aeacc98ff6daa7bfed

**Comment by pahaz** [comment] 2020-04-17 13:00
Related issue: https://github.com/keystonejs/keystone/issues/2334

**Comment by MadeByMike** [comment] 2020-06-03 01:36
Marking this as a duplicate of #2334

**Closed by MadeByMike** 2020-06-03 01:36 UTC
