### ISSUE TITLE
Get ObjectID by using key

### ISSUE THREAD

**Issue by BillGR17** [keystonejs/keystone#3814] opened 2016-12-20 21:19 UTC
I want to get the ObjectID from a category by using slug path (key)

this is the model (its the default from keystone generator)

```
var keystone = require('keystone');

/**
 * PostCategory Model
 * ==================
 */

var PostCategory = new keystone.List('PostCategory', {
    autokey: { from: 'name', path: 'key', unique: true },
});

PostCategory.add({
    name: { type: String, required: true },
});

PostCategory.relationship({ ref: 'Post', path: 'categories' });

PostCategory.register();
```

Heres what i get from mongoshell

db.getCollection('postcategories').find({"key":"test"})

```
{
    "_id" : ObjectId("5853a502455e60d5282d9325"),
    "key" : "test",
    "name" : "test",
    "__v" : 0
}
```

This is just to find if the key works
but when i use this on routes

```
var gc = "test";
var c = keystone.list('PostCategory').model.find().where('key').equals(gc);
 c.key = gc;
console.log(gc ,c.id);
```

The log says test undefined.
i tried to use postcategories as well but it says keystone doesnt recognize it

**Comment by AurelioDeRosa** [comment] 2016-12-20 22:50
The reason should be that `find()` returns a [Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise), so the operation is ran asynchronously. Therefore, at the moment you log the value, it's still `undefined`.

**Comment by BillGR17** [comment] 2016-12-21 08:02
is there a good example about that? coz that is new to me...

**Comment by BillGR17** [comment] 2016-12-21 09:57
ops i made a mistake on my post i forgot to add the test in quotes i changed it now

**Comment by jstockwin** [comment] 2016-12-21 10:05
@BillGR17 There are examples of the promises on the keystone demo site, for example [here](https://github.com/keystonejs/keystone-demo/blob/master/routes/views/blog.js#L22). 

I think what you want is something like:

```
var gc = "test";
var c = keystone.list('PostCategory').model.find().where('key').equals(gc).exec(function (err, results) {
    if (err) {
        console.log(err);
    } else {
        console.log(results);
    }
});
```
Also, I'm not sure here but if `find({"key":"test"})` works in mongoshell, it might also work in mongoose, so have you tried `keystone.list('PostCategory').model.find({"key":"test"}).exec(...)`?

**Comment by AurelioDeRosa** [comment] 2016-12-21 10:09
This is an example:

```js
keystone
   .list('PostCategory')
   .model
   .find()
   .where('key')
   .equals(gc)
   .then(function(category) {
      console.log(category.id);
   });
```

I think this issue can be closed as it isn't a problem with Keystone.

**Comment by jstockwin** [comment] 2016-12-21 10:28
Agreed, @BillGR17 I've summarised all the above on your [StackOverflow post](https://stackoverflow.com/questions/41243631/keystonejs-get-objectid-from-another-value/41260535) and I'll close this. 

@AurelioDeRosa I've just shamelessly copied and pasted what you said here over there, I hope that's okay with you!

**Closed by jstockwin** 2016-12-21 10:28 UTC

**Comment by AurelioDeRosa** [comment] 2016-12-21 10:34
Absolutely fine @jstockwin.

**Comment by BillGR17** [comment] 2016-12-21 11:57
@jstockwin example works but i don't know how to get the id from there
@AurelioDeRosa example gives me this error 
Sorry, an error occurred loading the page (500)
keystone.list(...).model.find(...).where(...).equals(...).then is not a function

**Comment by jstockwin** [comment] 2016-12-21 11:58
@BillGR17 What does the `console.log(results)` output? If it's found anything, there should be an id in there?

**Comment by BillGR17** [comment] 2016-12-21 12:08
@jstockwin yea the results have the id but i want to get the id and use it on a new variable (i don't want to do it manually because there will be multiple keys and ids i used test here just for a example)

**Comment by jstockwin** [comment] 2016-12-21 12:10
So, instead of `console.log(results)` do `var something = results._id`?

**Comment by BillGR17** [comment] 2016-12-21 12:16
```
var c = keystone.list('PostCategory').model.find().where('key').equals(gc).exec(function (err, results) {
    if (err) {
        console.log(err);
    } else {
			var gcid = results._id;
        console.log(gcid,results);
    }
});
```
Heres the console log
undefined [ { _id: 5857b80a7cf9b55946a5cadf,
    key: '8emata-panelladikwn-hmerhsiwn',
    name: 'Θέματα Πανελλαδικών Ημερησίων',
    __v: 0 } ]

**Comment by jstockwin** [comment] 2016-12-21 12:18
Okay, so the issue is it's returning an array (hence why it's in square brackets). 

This is because `find` could find MULTIPLE entries. 

If you only want on, you should use `findOne()` instead of find. This might solve the problem as I doubt findOne will return an array, but if it does you just need to do `var gcid = results[0]._id` (which will work with your above code snippet).

**Comment by BillGR17** [comment] 2016-12-21 12:20
yes thats it everything works now thnx for the help!!!
