### ISSUE TITLE
Update Multer

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone#1563] opened 2015-07-31 15:58 UTC
[Multer](https://github.com/expressjs/multer) has been updated with breaking changes to the API. We need to review the changes and update the implementation in `lib/core/mount.js` accordingly.

**Comment by JedWatson** [comment] 2015-10-05 06:14
So this is going to be much simpler is expressjs/multer#229 is merged, otherwise we'll have to change the public API significantly for application routes and pre-generate Admin UI routes that accept white-listed field names. Fingers crossed.

**Comment by mxstbr** [comment] 2016-04-29 13:01
This can be closed

**Comment by JedWatson** [comment] 2016-04-29 13:14
@mxstbr actually... multer is still pinned to an old version, this is still an active concern. Just lower priority than other issues in 0.4

**Comment by bassjacob** [comment] 2016-12-16 22:57
I've picked this up at https://github.com/keystonejs/keystone/pull/3794 and will make the changes there.

**Comment by jstockwin** [comment] 2016-12-22 09:01
> So this is going to be much simpler is expressjs/multer#229 is merged

This has been merged and released into 1.1.0, if this helps anything? cc/@bassjacob @JedWatson

**Comment by bassjacob** [comment] 2016-12-22 10:54
yep, the .any change should make this an out of the box fix. I'm going to have a look into their security recommendations and timebox that before just shipping to .any change.

**Comment by stennie** [comment] 2018-07-07 01:15
Closing as a duplicate of #4428, which will be addressed in Keystone `4.0.0-rc.2`.

**Closed by stennie** 2018-07-07 01:15 UTC
Labels: enhancement
