### ISSUE TITLE
dateTime & calendardDay fields have no date picker

### ISSUE THREAD

**Issue by sinbargit** [keystonejs/keystone#2185] opened 2020-01-05 08:15 UTC
# Bug report

As the doc descripte : 
> select  Generates a drop-down menu that allows the user to select a value from a list
> auto  Will generate a select if the range is 50 or less, otherwise will generate an input

But after I set the config below, there is still just a input component
```
posted: {
            type: DateTime, format: 'DD/MM/YYYY h:mm A',
            yearRangeFrom: 2020,
            yearRangeTo: 2030,
            yearPickerType: 'select',
        },
```
The screenshot is 
![ss](https://user-images.githubusercontent.com/16011848/71777080-4bd55380-2fd6-11ea-9afb-73f38df71a3e.png)

**Comment by wesbos** [comment] 2020-01-08 19:23
I asked them about this and apparently it's supposed to just be a text input. Would love if this used a date input

**Comment by sinbargit** [comment] 2020-01-09 02:56
> I asked them about this and apparently it's supposed to just be a text input. Would love if this used a date input

I am confused. Why the document said:

> select Generates a drop-down menu that allows the user to select a value from a list
> auto Will generate a select if the range is 50 or less, otherwise will generate an input

What's that mean?

**Comment by AllanFerencz** [comment] 2020-02-17 00:51
I'm also not sure what the documentation is referring to here 🤔

**Comment by MadeByMike** [comment] 2020-06-03 07:02
I'll look at the docs but until then I wanted to give an update: We're actively working on https://github.com/keystonejs/keystone/pull/2922 which includes a better date-picker option.

We'd love reviews comments and contributions to that PR.

**Comment by MadeByMike** [comment] 2020-06-03 07:11
Realising now this is also a duplicate of #215 - since this is the oldest issue I think it's best captured there. I'll update and cross link all relevant issues but this can mostly be tracked in the PR now.

**Closed by MadeByMike** 2020-06-03 07:11 UTC
