### ISSUE TITLE
Date format has no effect in DateTime field (and no picker)

### ISSUE THREAD

**Issue by ra-external** [keystonejs/keystone#2823] opened 2020-04-24 13:12 UTC
When setting the format for the DateTime field

```
const DATE_FORMAT = 'DD/MM/YYYY hh:mm';
	publishDate: {
				label: 'Select publishing date',
				type: DateTime,
				format: DATE_FORMAT,
				yearPickerType: 'auto'
			},
```

the `format` configuration field has no effect.  That is, the above code results in

![image](https://user-images.githubusercontent.com/60699805/80216213-0187e900-863e-11ea-93f0-1a20a75d4b2b.png)

Other variations of `format` have no effect.

Also, although a picker is indicated as a possibility, there is none (but I think this is a known issue).

**Comment by MadeByMike** [comment] 2020-06-03 01:03
No picker is a known issue. We have a bunch of improvements to do on the date fields and the formatting is one on our list. I'm closing this as a duplicate of #2746 - But this issue is very much on our radar! Thanks .

**Closed by MadeByMike** 2020-06-03 01:03 UTC
