### ISSUE TITLE
delete button on current user profile

### ISSUE THREAD

**Issue by snowkeeper** [keystonejs/keystone#1264] opened 2015-03-29 02:26 UTC
The user currently logged in can not successfully delete themselves.  Should the UI be updated to hide the delete button in this case?

**Comment by creynders** [comment] 2015-03-29 10:07
:+1: Personally I'd go for a disabled button instead. Not sure what other people think.

**Comment by mxstbr** [comment] 2016-04-29 10:35
Duplicate of #265, moved to ProductPains! https://productpains.com/post/keystonejs/can-delete-all-admin-users

**Closed by mxstbr** 2016-04-29 10:35 UTC
