### ISSUE TITLE
Admin sidebar background

### ISSUE THREAD

**Issue by tomWritesCode** [keystonejs/keystone#3034] opened 2020-05-25 01:14 UTC
## Bug report

Admin sidebar has no background

When scrolling horizontal the admin sidebar has no background and text is visible as it scrolls behind

## To Reproduce

1. Go to admin dashboard
2. shrink screen small enough to create side scrolling
3. Scroll sideways

## Expected behaviour

Content should disappear behind the sidebar of the admin dashboard

## Screenshots

![Bug_Screenshot](https://res.cloudinary.com/tomwritescode/image/upload/v1590368308/Screen_Shot_2020-05-25_at_10.53.27_am.png)

![Bug_Gif](https://res.cloudinary.com/tomwritescode/image/upload/v1590368324/Keystone_Bug.gif)

## Additional context

`"@keystonejs/app-admin-ui": "^5.11.1",`

**Comment by timleslie** [comment] 2020-05-25 01:28
@tomWritesCode Are you able to upgrade to the latest version of the `app-admin-ui` package (6.0.2) and verify that the issue is still there?

@Vultraz Could you investigate/fix this if it's still an issue? 🙏

**Comment by Vultraz** [comment] 2020-05-25 01:31
This was fixed in 95babf5da8488f2d7f8ab9f91ff640576462af6d

**Closed** 2020-05-27 01:59 UTC
