### ISSUE TITLE
[AdminUI] CalendarDay: Date picker doesn't work...

### ISSUE THREAD

**Issue by maximelebreton** [keystonejs/keystone#2366] opened 2020-02-14 21:41 UTC
Hello keystone Team,
and thanks for your amazing work.

It's a real pleasure to discover this framework, I'm very excited about it!

I have this strange problem: With the CalendarDay field (and the other date fields), there is **no Date Picker**...
Only a simple text input (So I suppose this is not normal).
And no errors in console...

Any ideas?

![todo](https://user-images.githubusercontent.com/1072425/74569585-06178d80-4f7b-11ea-8fc1-d3ca56896a87.gif)

Versions:
```
    "@keystonejs/adapter-mongoose": "^5.1.3",
    "@keystonejs/app-admin-ui": "^5.3.0",
    "@keystonejs/app-graphql": "^5.0.1",
    "@keystonejs/app-static": "^5.0.0",
    "@keystonejs/fields": "^6.0.0",
    "@keystonejs/keystone": "^5.3.0",
```

Thanks!

**Comment by Vultraz** [comment] 2020-02-14 22:38
That's expected. There's no built-in date picker for CalendarDay yet.

**Comment by maximelebreton** [comment] 2020-02-14 23:18
Oh!
And any plans to implement it?
Or a way to customize it by myself?
It's very problematic for the project Im working on now.

Thanks for your help

**Comment by maximelebreton** [comment] 2020-02-14 23:33
Just adding `type="date"` on the `input` tag would do the job, no?

![date](https://user-images.githubusercontent.com/1072425/74576253-564a1c00-4f8a-11ea-9a7e-8ad54f718e2a.gif)

**Comment by maximelebreton** [comment] 2020-02-14 23:59
https://github.com/keystonejs/keystone/pull/2367

**Comment by Vultraz** [comment] 2020-02-15 11:00
I was working on a date picker impl last year (#1965) but I didn't finish 😬

**Comment by MadeByMike** [comment] 2020-06-03 07:01
This is a duplicate of #2185.

This is an important issue and we are working on it. Please consider contributing to https://github.com/keystonejs/keystone/pull/2922 where we've broken down the work required into a number of smaller tasks.

**Closed by MadeByMike** 2020-06-03 07:01 UTC
