### ISSUE TITLE
Mongoose model 'error' event fired on 'User' with error:  Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by LXF5133** [keystonejs/keystone#4507] opened 2017-11-13 04:25 UTC
### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 
| Node             |

**Comment by w01fgang** [comment] 2017-11-19 22:29
duplicate of #4496

**Closed** 2018-05-27 08:45 UTC
Labels: bug
