### ISSUE TITLE
Relationship "ref" fields are slow to load on the admin ui

### ISSUE THREAD

**Issue by chrisschaub** [keystonejs/keystone#4891] opened 2019-01-29 15:48 UTC
Relationship "ref" fields are slow to load on the admin ui, when viewing a record with rel fields. I can see the spinner on the rel field just spin for like 6-10 seconds and then it stops. And the admin ui is pretty unresponsive until it finishes spinning. I've added indexes on these fields, any thoughts? Using Keystone 4.0 on node 6.x, linux, mongodb.com M30 at AWS, 3.6.9. I have thousands of potential relationships records for this field. It only happens when I have a relation set, like it's trying to table scan to find the value in the list? I would assume it would find it via an index since it's on the _id field?

Could it be this query

refList.model.find().where('_id').in(item.get(field.path)).limit(4).exec(function (err, results) {

in admin/server/api/item/get.js

how about adding a
.lean()

to the query so we just pull back the basic document? I posted this on stackoverflow, but nobody has an ideas, and it seems the query here is not optimal. So logging as a bug because the admin UI becomes totally unresponsive until the slow query finishes which can be 10+ secons.

**Comment by chrisschaub** [comment] 2019-02-01 13:00
Hmmm, I don't see that error, are your models stock? My original issue is not related to this, it has to do with a slow query in the core code.

**Comment by shash7** [comment] 2019-02-02 02:06
Yes its a stock user model. The backend cannot display a single user model for some reason.
Could be unrelated.

**Comment by chrisschaub** [comment] 2019-02-12 21:30
This easy to reproduce if you have thousands of nodes in a relationship field. Would "lean()" work or does the query need to be rewritten?

**Comment by chrisschaub** [comment] 2019-04-01 18:50
Would it be possible to only fire the "load" even when the field is activated? This would make the query be on-demand.

**Comment by autoboxer** [comment] 2019-04-10 21:23
I'm closing this as it's a duplicate of #4797

**Closed by autoboxer** 2019-04-10 21:23 UTC
Labels: 4.1 candidate
