### ISSUE TITLE
Select options hidden under Wysiwyg field

### ISSUE THREAD

**Issue by ashinzekene** [keystonejs/keystone#2196] opened 2020-01-06 11:00 UTC
# Bug report
The select options is hidden under the Wysiwyg field when the Wysiwyg field is directly under it

## Describe the bug

A clear and concise description of the bug.

## To Reproduce

```js
const {
  Text, Relationship, Slug, File, Select,
} = require('@keystone-alpha/fields');
const { Wysiwyg } = require('@keystone-alpha/fields-wysiwyg-tinymce');


module.exports = (keystone) => keystone.createList('Job', {
  labelField: 'title',
  fields: {
    title: {
      type: Text,
      required: true,
    },
    headerImage: {
      type: File,
    },
    isAvailable: {
      label: 'Is Available',
      defaultValue: 'False',
      schemaDoc: 'Whether or not to display this Job publically',
      options: 'True,False',
      type: Select,
    },
    content: {
      type: Wysiwyg,
      required: true,
    },
    location: {
      type: Relationship,
      ref: "Location",
      required: true,
    },
    department: {
      type: Relationship,
      ref: "Department",
      required: true,
    }
  },
});
```

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Open a sample document
2. Click on the select

## Expected behaviour

Select should have a hidden z-index than the Wysiwyg field

## Screenshots
![image](https://user-images.githubusercontent.com/20991583/71814167-e8056600-307b-11ea-9684-61a3f4f63f86.png)

**Comment by Vultraz** [comment] 2020-03-16 13:36
Duplicate of #2451. Fixed in #2490, so this one can be closed.

**Closed** 2020-05-27 02:16 UTC
