### ISSUE TITLE
ReferenceError: navigator is not defined when using @keystone-6/cloudinary

### ISSUE THREAD

**Issue by alsoicode** [keystonejs/keystone#7137] opened 2022-01-02 20:20 UTC
- Install @keystone-6/cloudinary (1.0.0) and cloudinary (1.28.0)

- Keystone should not throw an error during `keystone postinstall`

```
ReferenceError: navigator is not defined
    at Module../src/namespace/cloudinary-core.js (/Users/btaylor/work/node-projects/rdk/node_modules/cloudinary-core/webpack:/cloudinary/src/util/browser.js:7:18)
    at __webpack_require__ (/Users/btaylor/work/node-projects/rdk/node_modules/cloudinary-core/webpack:/cloudinary/webpack/bootstrap:19:1)
    at /Users/btaylor/work/node-projects/rdk/node_modules/cloudinary-core/webpack:/cloudinary/webpack/bootstrap:83:1
    at /Users/btaylor/work/node-projects/rdk/node_modules/cloudinary-core/cloudinary-core.js:104:10
    at webpackUniversalModuleDefinition (/Users/btaylor/work/node-projects/rdk/node_modules/cloudinary-core/webpack:/cloudinary/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/Users/btaylor/work/node-projects/rdk/node_modules/cloudinary-core/webpack:/cloudinary/webpack/universalModuleDefinition:10:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/btaylor/work/node-projects/rdk/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

Node 16.13.0 on OS X (12.1)

**Comment by bladey** [comment] 2022-01-17 04:03
Hey @alsoicode,

I created an fresh project and installed `@keystone-6/cloudinary`, `cloudinary` and I'm not able to reproduce this, could you provide further details?

Thanks!

**Comment by alsoicode** [comment] 2022-01-18 01:44
Thanks for looking into this. Let me find some time to create another project and see if I hit the same issue.

**Comment by bladey** [comment] 2022-01-19 03:09
Thanks @alsoicode, I'll close this for now, let me know how you go and I'll re-open if need be!

**Closed by bladey** 2022-01-19 03:09 UTC
Labels: :earth_asia: i/community, 💬 i/awaiting-response
