### ISSUE TITLE
Uploading an avatar sets the password to null

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone#1076] opened 2019-05-01 14:08 UTC
This behaviour is tested on the demo project of the blog.
**Steps to reproduce:**
1. Run the blog project from `demo-projects`.
2. Open admin panel and add an avatar image to any user.
3. Query `password_is_set` from graphql API or look directly to the mongo database. `password_is_set` will be `false` and the password field will be `null`.
4. Try to click `Set Password` button, fill the password and then hit the `Save` button. File will be uploaded and the password updated.

I found where the `null` comes from:
[Here](https://github.com/keystonejs/keystone-5/blob/master/packages/fields/src/types/Password/Implementation.js#L103) if the password field is empty it becomes `null`

**Comment by timleslie** [comment] 2019-05-01 22:45
Hi @w01fgang, thanks for the detailed bug report. I'll look into this and try to get a fix out ASAP.

**Comment by Vultraz** [comment] 2019-12-12 07:40
I can't reproduce this anymore.

**Comment by bladey** [comment] 2021-03-01 05:32
Hi @w01fgang,

Thank you for taking the time to write about this issue.

In an effort to maintain the KeystoneJS project going forward, we're closing issues related to [Keystone 5](https://github.com/keystonejs/keystone-5) to make way for the next version called [Keystone Next](https://next.keystonejs.com).

The existing **Keystone 5** codebase has been moved to [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) which is now in a 6-12 month active maintenance phase.

You can learn more about the next version which we’re calling **Keystone Next**, which is now [in preview](https://next.keystonejs.com).

If you feel this issue is still relevant and require assistance, please open a new issue in the [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5) repository.

Thank you for your continued support as we push towards this next major new version of KeystoneJS!

**Closed by bladey** 2021-03-01 05:32 UTC
Labels: bug, needs-review
