### ISSUE TITLE
Click `Today` button in AdminUI enters infinite loop

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone#1038] opened 2015-02-11 05:49 UTC
I've been testing out the 0.3.0 branch on a third project. Any one else can confirm clicking the `Today` button in the date picker enters an infinite loop?
![screenshot 2015-02-10 21 45 14](https://cloud.githubusercontent.com/assets/587438/6142620/98737cb2-b16e-11e4-9b00-77620e6b513c.png)
See the lower right corner above. The UI is frozen in the screenshot and crashes chrome.

**Comment by perryao** [comment] 2015-02-11 05:50
Ran into the exact same issue a moment ago. Don't have a fix for it, but figured I'd let everyone know you weren't alone in experiencing this.

**Comment by morenoh149** [comment] 2015-02-11 05:55
is there a way to set a debug flag that will have keystone deliver an unminified `app.js` file? it's just saying `app.js:1` in the console.

**Comment by JohnnyEstilles** [comment] 2015-02-11 08:39
@morenoh149 I've been testing all the fields in the last couple of days and I haven't encountered that problem at all. Do you have any other details?

![image](https://cloud.githubusercontent.com/assets/5514878/6144020/6ee9b5f2-b20c-11e4-8c35-6cbc5dc1c6e1.png)

**Comment by morenoh149** [comment] 2015-02-11 21:47
@JohnnyEstilles you can clone it and run it locally https://github.com/r3dm/keystone-demo trying to update it to 0.3.0. Unless the infinite loop is caused by something I did to the environment.

**Comment by JohnnyEstilles** [comment] 2015-02-12 01:04
Just cloned and tested your demo, and I'm sorry to say I can't replicate your problem. Sorry.

Tried on Windows and OS X ... and in multiple browsers (Safari, Chrome, Firefox and IE) ... and it still works for me. Screenshot below is obviously Chrome on OS X.

![screenshot 2015-02-12 08 59 33](https://cloud.githubusercontent.com/assets/5514878/6159812/d3256e56-b295-11e4-9129-335e3b9cc4ca.png)

**Comment by morenoh149** [comment] 2015-02-12 01:13
maybe it's my environment. Firefox too 
![screenshot 2015-02-11 17 13 21](https://cloud.githubusercontent.com/assets/587438/6159934/54824c6a-b211-11e4-8904-6ac236e8a02c.png)

**Comment by webteckie** [comment] 2015-02-12 01:54
fyi, I cloned @morenoh149 repo and, yeah, there's something wrong with the Today click.  I don't see the logging but the thing does go into an infinite loop.

**Comment by JohnnyEstilles** [comment] 2015-02-12 01:56
@morenoh149 ... @webteckie ... you guys should talk. Maybe you have something in common in your env. I wasn't able to replicate the problem.

**Comment by webteckie** [comment] 2015-02-12 01:59
Maybe someone else should try it out.  If they also have the issue then that may prove something.  I used the very latest 0.3.0; built the app.js locally.

**Comment by lojack** [comment] 2015-02-12 14:22
I ran into this issue separately from @morenoh149. Should be able to dig into this issue today. Currently using vagrant, so I can package up my environment if that helps anyone.

**Comment by gregoj** [comment] 2015-02-12 16:44
I'm on a brand new installation running locally on OS X 10.10 and I'm seeing this issue. First post, first attempt to set a date. Happens during the initial posting phase or during editing of the same existing post.

It's not just isolated to the Today button for me, however. Using the popup date control or even typing in a valid date creates the same apparent freeze/loop.

Happy to help however I can, if there is some testing or debugging I can provide.

**Comment by lojack** [comment] 2015-02-12 17:01
This appears to be occurring because [DateField.js setDate()](https://github.com/keystonejs/keystone/blob/6966718d9ced9ed542527a8c5f4cec0de11c5e1a/fields/types/date/DateField.js#L38) sets the state, which triggers an onChange in [EditForm's handleChange()](https://github.com/keystonejs/keystone/blob/6966718d9ced9ed542527a8c5f4cec0de11c5e1a/admin/src/components/EditForm.js#L31) which also sets the state. Getting rid of the onChange property in DateField.js's renderUI fixes this, but appears to have the side effect of removing date validation.

**Comment by JohnnyEstilles** [comment] 2015-02-13 02:55
@lojack the state being set by `setDate()` on `DateField` is the local component's state, which is different than the state set by `handleChange()` on `EditForm`. If #1061, you didn't remove the `onChange` property of `DateField`. You did remove the `onChange` property of `DateInput`, which relies on `DateField` for validation and to push any changes to the `EditForm` component.

I'm more curious about the "sporadic" nature of the bug. Unless, of course, I'm the only one for which the component works correctly. :-)

**Comment by JohnnyEstilles** [comment] 2015-02-13 03:23
A bit of background information on the `Date` component, for anyone who will attempt to troubleshoot this issue.

- The `state` stored for this component on `EditForm` is an ISO string (which is what we get from/send to the server)
- The `state` stored within `Date` is the date formatted using `inputFormat`
- The two states are required because if the date entered is invalid the local state needs to be whatever invalid date the user entered, but the state pushed to `EditForm` is null (to indicate an invalid date).

Personally, I'm a fan of the use of state-less components whenever possible. In this case, however, there is a distinct difference between the state of the date within the `Date` component and that stored in `EditForm`.

Also, a while ago I refactored some common code between the `Date` and `DateTime` components into a separate `DateInput` component. Something I did not refactor was the date validation methods. The reason I kept it within the `Date` component is because validation was fundamentally different in the `Date` and `DateTime` components. This means that it is necessary for the `DateInput` component to inform it's parent component (whether it's the `Date` or the `DateTime` component) of any changes so that the parent component can perform the appropriate validation.

I hope this little bit of background helps someone point out the source of the bug. I'll keep working to see if I can replicate it so I can help with the troubleshooting efforts. If anyone affected can provide any information that can help me reproduce the issue, it will be greatly appreciated. :-)

**Comment by morenoh149** [comment] 2015-02-13 09:33
I get the following logged in firefox
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.2.min.js:1:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.10.2.min.js:5:0
"Each child in an array should have a unique "key" prop. Check the renderComponent call using <undefined>. See http://fb.me/react-warning-keys for more information." app.js:9:13795
Error: Script terminated by timeout at:
[129]</</r.measure/a@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:10:1
[91]</</h.Mixin.performUpdateIfNecessary@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:7:27529
[91]</</h.Mixin.receiveComponent@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:7:27288
[99]</</a.Mixin.receiveComponent@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:8:19830
[125]</v.Mixin._updateChildren@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:10:1639
[125]</v.Mixin.updateChildren@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:10:1351
[99]</</a.Mixin._updateDOMChildren@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:8:21454
[99]</</a.Mixin.updateComponent<@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:8:20055
[129]</</r.measure/a@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:10:5362
[91]</</h.Mixin.performUpdateIfNecessary@http://r3dmqa.herokuapp.com/keystone/build/js/app.js:7:27529
[91]</</h.Mixin.receiveComponent@h app.js:10:0
```

**Comment by morenoh149** [comment] 2015-02-14 05:36
to everyone following this thread could you confirm this quickfix works for you.
* cd into `node_modules/keystone`
* run `gulp build-scripts` (it may complain about `chalk` module, if so move it from `devDependencies` to regular `dependencies` in keystone's `package.json`)
* retest adminUI

*Note* this doesn't solve deploying to heroku unless you put `node_modules/keystone` under version control.

**Comment by webteckie** [comment] 2015-02-14 11:27
@morenoh149 that's exactly what I did initially and the problem still reproduced for me.

**Comment by dboskovic** [comment] 2015-02-17 23:52
I'm getting a complete crash when trying to select any date from the datepicker. Client reported this issue first and I investigated. Using latest Chrome.

**Comment by lojack** [comment] 2015-02-19 16:15
@JohnnyEstilles What version of NodeJS are you using, and is your development environment in windows or is there some sort of virtualized environment you're using?

**Comment by JohnnyEstilles** [comment] 2015-02-19 16:25
@lojack I'm using node 0.10.35 on both Windows 8 64-bit (not virtualized) and OS X. I develop and test on both.

**Comment by lojack** [comment] 2015-02-19 19:52
I have an update to this. With a Demo site set up, I have a Post created which I had previously set the publish date on, and status is set to Draft. Doing the following steps I encounter slightly different issues:

1. Check out current keystone master branch
2. Start keystone
3. Open post
4. I can edit all of the content freely with no issues
5. Set state to Published
6. I can edit all of the content freely with no issues, except for published date, which makes the browser freeze
7. Run `gulp build-scripts`
8.  Restart keystone 
9. Reload page (since I didn't save, State is now Draft)
10. I can edit all of the content freely with no issues
11. Set state to Published
12. Editing **any** piece of content causes the browser to freeze

On a different piece of content without the published date set, everything works perfectly. I'm also using Chrome in Incognito mode (to eliminate plugins as a source of issues).

Anyone else able to recreate similar results?

**Comment by morenoh149** [comment] 2015-02-19 22:49
@lojack did you try running the grunt task to build app.js on your machine? I honestly think that's the main issue.

**Comment by lojack** [comment] 2015-02-20 16:35
@morenoh149 Yep, rebuilt app.js, and cleared my browser cache. Still running into the same issue.

**Comment by blakev** [comment] 2015-02-24 02:43
I ran into this today, and it's a blocker for me. Is there a resolution, or should I start digging?

Brand new install on Ubuntu 14.10 x64 with Node 0.10.35

**Comment by morenoh149** [comment] 2015-02-24 03:33
@blakev if you know any browserify I could use some help. We're trying to develop a postinstall step where the bundle is generated on the end-user's system. https://github.com/r3dm/keystone/tree/build-postinstall

**Comment by JohnnyEstilles** [comment] 2015-02-24 04:00
@morenoh149 I understand you're trying to pursue your `postinstall` proposed solution for this problem, but I think a better solution would be to implement a pure React component for both the `Date` and the `DateTime` field types (something similar to what I proposed in #1065) and to create a "dynamic build upon startup" solution, like @JedWatson suggested on #1061 (check out his [comment on the subject](https://github.com/keystonejs/keystone/pull/1061#issuecomment-74414829)).

**Comment by webteckie** [comment] 2015-02-24 11:05
I believe that, at least, @lojack and I have also verified that building it locally does not fix the issue.

**Comment by jbfolkerts** [comment] 2015-02-24 13:30
Agree. Post-install 'build-scripts' did not fix this problem for me.  It showed up in Linux Chromium and Firefox latest versions, and Windows as well.

**Comment by gmmeyer** [comment] 2015-02-24 18:15
I'm also getting this error, or a very similar error, in the text editor when wysiwyg is turned off. 

It freezes when I select the field. I get it in both my production(!) machines and my dev machines.

**Comment by gmmeyer** [comment] 2015-02-24 18:48
I also get the same error with the today button. The build-scripts workaround didn't work for me, either.

**Comment by egdelwonk** [comment] 2015-02-25 04:01
Same here. Clicking on a date from the date picker or clicking on "Today" button will cause a complete crash in Chrome or Firefox

**Comment by nicdutil** [comment] 2015-02-26 07:07
Same here. Page freezes when choosing any date using the Date Picker. 
Running ubuntu 14.04 and chrome 40.0.2214.115 (64-bit).

**Comment by JedWatson** [comment] 2015-02-26 11:38
I've made a change to `DateInput` that may fix the problem. Unfortunately, it doesn't happen for me (at all) - I simply cannot reproduce the issue, so I can't be sure.

Would someone who can replicate it test the latest build and let me know please?

**Comment by lojack** [comment] 2015-02-26 14:05
@JedWatson, this does not seem to fix the issue for me

**Comment by egdelwonk** [comment] 2015-02-26 14:17
I'm able to replicate it by doing an npm install, rather than a direct build.












On Thursday, Feb 26, 2015 at 8:05 AM, Robert Clark <notifications@github.com>, wrote:

@JedWatson, this does not seem to fix the issue for me

**Comment by OUPARC** [comment] 2015-02-26 15:02
Hello, I reached this page searching for a resolution to this issue.  I am experiencing this behavior (infinite loop) not just on the Today button, but any autocomplete field (ie. autocomplete on a relationship field, date picker).  I am using a clean yo keystone install with a single custom list model.

Please let me know if I can assist in diagnosing the issue.

**Comment by morenoh149** [comment] 2015-02-26 20:04
I pushed the demo app to heroku. See https://obscure-spire-9336.herokuapp.com/keystone/posts username `demo@keystonejs.com` pass `demo` I can see the error when I click the today button. Source is https://github.com/r3dm/keystone-demo Should help with debugging the issue.

**Comment by stonean** [comment] 2015-02-27 01:56
I've been trying to track this down as well by referencing different keystone commit shas in package.json.  Backed all the way to the following commit before the issue went away. I was looking for "Updating build" commit messages.

https://github.com/keystonejs/keystone/commit/6deddaccfa72069e31d2171c6f5b7644720a60b4

It works there. I'm now going to start working my way back to the commit that broke it.

I have no idea if the build of app.js is needed or not? Will referencing the commit hash without that kind of push just work? I'm new to the JS world and barely have a clue how this works.

**Comment by stonean** [comment] 2015-02-27 02:35
This issue starts on this push:

https://github.com/keystonejs/keystone/commit/55fa373be3aee79e96c562c8eef05acd51910547

Which is a "Updating Build" push. The previous commits work. 

I tested by changing the keystone declaration in package.json to:

`"keystone": "git://github.com/keystonejs/keystone.git#55fa373be3aee79e96c562c8eef05acd51910547",`
 
Then I removed the node_modules directory, reinstalled and tested.

**Comment by BerkeleyTrue** [comment] 2015-02-27 02:39
The only change between the two are the updated dependencies. Looks like some third party library is acting screwy.

**Comment by BerkeleyTrue** [comment] 2015-02-27 03:06
Actually, it looks like the build file was not updated between https://github.com/keystonejs/keystone/commit/83b3396da973a3bc0847a8b550cf137b3452ee8f and the commit mentioned above. The culprit could be somewhere betwixt them.

**Comment by stonean** [comment] 2015-02-27 03:21
Yeah, that's my thought as well. Wish I knew more about this process to help more. I'm not even sure how the build file is created.

**Comment by JedWatson** [comment] 2015-02-27 03:29
The build file is created by browserify + gulp; to build you run `gulp build-scripts`. You'll see what it's doing if you look in `gulpfile.js`

I just committed a bunch of debug for the DateInput that should help. @morenoh149 suggested in Slack that it might be a local issue, which is the first explanation I've heard as to why it works for some people and breaks horribly for others, so my new debugging will hopefully help us trace down what's going on.

Could everybody please post (whether you can reproduce the problem or not) what your locale, date format, browser and OS are?

And could those who *can* reproduce the issue please test against the update I just pushed.

If you open your console you should see several debug messages coming from the DateInput component, which will hopefully track down why it's infinitely looping.

The messages (for me) look something like this:

```
"DateInput [84933] received props. value ("2015-02-27" === "2015-02-01") -- updating state" app.js:1
"DatePicker [84933] selected. value ("2015-02-27" === "2015-02-01") -- firing onChange event" app.js:1
"DateInput [84933] received props. value ("2015-02-27" === "2015-02-27") -- no change" app.js:1
```

(in case you have multiple date pickers in your list, each has an [id] set for debug identification)

Thanks for persisting with this everyone, it's driving me crazy and I wish I could reproduce it so I can actually *fix* it.

**Comment by stonean** [comment] 2015-02-27 03:37
![screenshot 2015-02-26 22 36 23](https://cloud.githubusercontent.com/assets/6162/6407108/fe60a270-be07-11e4-812d-631fd82e883a.png)

**Comment by JedWatson** [comment] 2015-02-27 03:42
Right. So for some reason one of those dates is being converted to a different day. Probably timezone related. WTF.

@stonean what's your timezone?

**Comment by stonean** [comment] 2015-02-27 03:44
@JedWatson EST

**Comment by JedWatson** [comment] 2015-02-27 03:54
Thanks @stonean. I've just pushed another change with one more line of debug; would you mind doing it again please?

**Comment by stonean** [comment] 2015-02-27 04:03
![screenshot 2015-02-26 23 03 04](https://cloud.githubusercontent.com/assets/6162/6407327/ae6e8c38-be0b-11e4-9280-b97f262962b2.png)

**Comment by morenoh149** [comment] 2015-02-27 08:49
I can reproduce in virtualbox. Xubuntu FF PST
![keystonexubuntuffbug](https://cloud.githubusercontent.com/assets/587438/6409566/6a0c2938-be1a-11e4-91e8-3767a925e100.png)

**Comment by JedWatson** [comment] 2015-02-27 10:58
I found the bug. See the issue in Pikaday referenced above. Fix incoming.

**Closed** 2015-02-27 11:01 UTC
Labels: bug

**Comment by lojack** [comment] 2015-02-27 14:12
Nice! Works for me. Good job @JedWatson

**Comment by stonean** [comment] 2015-02-27 15:31
@JedWatson thank you for the additional FYI on how you tracked this down.

**Comment by JedWatson** [comment] 2015-02-28 12:27
@stonean no problem, thought it might be useful :smile:
