### ISSUE TITLE
Impossible to remove last relationship element from input.

### ISSUE THREAD

**Issue by masza** [keystonejs/keystone#4604] opened 2018-03-26 23:17 UTC
### Expected behavior
AdminUI
Possibility to remove all added in past relationships 

### Actual/Current behavior
Impossible to remove last relationship element from field 
`type: Types.Relationship`

### Steps to reproduce the actual/current behavior
When I use AdminUI I can't remove added before elements from field of type relationship. This bug applies to last element of relationships array in input. The same behavior if option "many" is set to true and false. Always after changes (remove last relationship) and save removed element appear in relationship field. 

### Environment

| Keystone   4.0.0-beta.8 | 
| Node 8.9.0 |

**Comment by 1337cookie** [comment] 2018-04-17 09:54
Nobody can verify this issue or help without seeing your code.

**Comment by stennie** [comment] 2018-05-27 08:17
This is a duplicate of #4332. I can reproduce in 4.0.0-beta8.

**Closed by stennie** 2018-05-27 08:17 UTC
Labels: 4.0, bug
