### ISSUE TITLE
Bug with Boolean and default value

### ISSUE THREAD

**Issue by MadMadlen** [keystonejs/keystone#4877] opened 2019-01-02 10:22 UTC
We have a field that type is boolean and its default value is true. 
On admin panel (list view) everything is ok, problem is with item view. 
On item view field even when its value is false (unchecked) seems to be marked as true. It is also impossible to uncheck this field. 
I tested this on keystone 4.0.0 and keystone 4.0.0-beta.4. On 4.0.0-beta4 it is ok problem is with version 4.0.0

### Expected behavior
- boolean field marked as false should not be checked (visible as true) on admin panel (item view)
- it should be possible to change boolean field value to false even when its default value is true

### Actual/Current behavior
- when boolean field has default: true it is visible as checked and it is impossible to uncheck field on admin panel

### Steps to reproduce the actual/current behavior
- setup field that type is boolean, default: true 
- visit item view on admin panel
- try to change field value 

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0
| Node.js          | 8.11.1 
| Browser          | Chrome  71.0.3578.98

**Comment by autoboxer** [comment] 2019-01-02 15:48
closing as this is a duplicate of #4737.  @MadMadlen, your comments have been copied over to that issue.

**Closed by autoboxer** 2019-01-02 15:48 UTC
