### ISSUE TITLE
Use semver semantic for npm.

### ISSUE THREAD

**Issue by Calvein** [keystonejs/keystone#924] opened 2015-01-19 04:54 UTC
The latest version (`0.2.41`) added a couple of functionalities that break (for us) what we had in `0.2.40`. If the versions were following [semver] we wouldn't had have problems since we use the ~, is there any reason why it's not the case ? Just FYI:

> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.

[semver]: http://semver.org/

**Comment by JedWatson** [comment] 2015-01-19 05:25
@Calvein can you provide some more detail about what functionality broke what was in 0.2.40?

I'm familiar with server, we're trying to follow it as best we can with a complex project.

Note semver for pre-1.0.0 versions:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

We try and do better than this, and have generally had a stable API throughout 0.2.x with only a couple of versions in over a year that included accidental regressions.

In the meantime recently we've been working heavily on 0.3.0 which represents our rollup of potentially breaking changes (in particular, rewrite of the Admin UI forms with React, and bundling of Express 4).

Once we've got a stable external API for field types, express integration and Admin UI customisation, we'll release 1.0.0 and version Keystone using the MAJOR / MINOR / PATCH system; until then it is MINOR / PATCH with new backwards-compatible features _and_ fixes in the patch, and potentially breaking changes in the minor.

**Comment by Calvein** [comment] 2015-01-19 06:06
@JedWatson I can't because I had no feedback whatsoever, keystone was just not starting. So we directly rollback to 0.2.40. If there is logs somewhere I'm happy to have a better look at it.
You're right for 0.y.z, it's tricky and I guess that's why `npm init` is 1.0.0 by default now.

**Comment by JedWatson** [comment] 2015-01-19 06:33
@Calvein are you using either mongo or redis for your session management? There was a breaking change published upstream in the connect-mongo package that caused that sort of problem; 0.2.41 fixed Keystone so it's compatible with the new version.

If so, try upgrading your `connect-redis` / `connect-mongo` package as well as Keystone.

Unfortunately that change was published in a way that we can't do anything to protect our users from it and it's caused a lot of trouble...

**Comment by JedWatson** [comment] 2015-01-19 10:51
I'm closing this, with a small rant - I don't assume you meant it, but the whole tone of this issue offends me. Largely because of the assumption semver (or stability) isn't a concern.

I spent _hours_ of my weekend preparing `0.2.41` with fixes for features _I don't even use_ because of reports they are breaking. I'm about to release a big new version, but I don't want to leave `0.2.x` broken for people who may not be able to upgrade easily or quickly. The breakage is happening because of changes (imo, stupid changes) to other packages which Keystone needs to be compatible with.

The fixes involved re-working PRs that would have caused _other regressions_ if I'd just merged them as-is, because I pay attention to _every single thing_ that happens in this project to try and prevent things like this.

Semver wouldn't have saved this issue, because the patch released should have been a simple, backwards compatible fix. I never would have published a major new version over it, because it was the very definition of what a "patch" revision is supposed to be.

I'm sorry if there is an issue with the new version. That's not a good thing. But if you review [the changelog](https://github.com/keystonejs/keystone/blob/master/HISTORY.md) or [commit history](https://github.com/keystonejs/keystone/commits/0.2.x), you'll be able to narrow down the change that broke for you and submit a meaningful bug report.

**Closed by JedWatson** 2015-01-19 10:51 UTC
