### ISSUE TITLE
[v4.0.0-beta.2] initial noedit fields don't work

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#3495] opened 2016-09-17 23:13 UTC
### Steps to reproduce the behavior

Create a model with a field which is both initial and noedit. Create a new item with this field filled in, using the initial create form. 

### Expected behavior

The item should save correctly, with the field populated to the correct value. After this initial input, the field is no longer editable.

### Actual behavior

The field is blank. It's also blank (or in fact, not present at all) in the database, so this is more than just a display issue. 
The field is not editable, which is correct, but also means it's impossible to fix the problem via the edit form.

**Comment by promethe42** [comment] 2016-09-28 06:48
Duplicate of #3473

**Comment by jstockwin** [comment] 2016-09-28 06:58
Very true, thanks. Closing.

**Closed** 2016-09-28 06:58 UTC
