### ISSUE TITLE
Unable to remove uploaded files

### ISSUE THREAD

**Issue by afrozl** [keystonejs/keystone#1382] opened 2015-05-11 00:25 UTC
I've added audio files to the Post model using LocalFiles and the files are uploaded and usable. However, when I try to remove them nothing happens. No errors, the file remains attached to the post and in the local storage. The entry for the audio files is:

        audio: { type: Types.LocalFiles, dest:"public/audio/uploads", prefix: '/audio/uploads', filename: function(item, file) {return item.slug + '.' + file;  } }

Any ideas on where to look for the errors?

**Comment by Gouthamve** [comment] 2015-05-23 17:18
I think it is expected. Only the entry in the db is deleted but not the file itself.

I am not sure if autoCleanup option of Cloudinary applies here as well.

**Comment by mikeblakeney** [comment] 2015-06-22 21:50
@afrozl I ended up making a copy of the model using the post('init') and then using that reference in my pre('save') to determine if I needed to remove the audio file manually or not.  There might be a simpler solution though...


```javascript
Audio.schema.post('init', function(){
	this._original = this.toObject();

});

Audio.schema.pre('validate', function(next){
	if(this.isModified('fileUpload')) {
		console.log(this._original);
                 // determine if we need to remove the file or not
	}

	next();
});
```

Here's my reference from slashdot on the solution: http://stackoverflow.com/questions/18192804/mongoose-get-db-value-in-pre-save-hook

**Comment by AlexYegupov** [comment] 2016-02-26 10:56
seems db entrie isn't deleted either. v0.3.16

**Comment by mxstbr** [comment] 2016-04-29 12:02
Closing this due to age, this is also a duplicate of #162!

**Closed by mxstbr** 2016-04-29 12:02 UTC
