### ISSUE TITLE
v0.4: Datetime field type does not validate time input

### ISSUE THREAD

**Issue by geloescht** [keystonejs/keystone#2898] opened 2016-05-20 12:14 UTC
Entering an invalid value into the time input of a Datetime field does not cause validation to fail and incorrectly stores `1970-01-01 1:00:00 am` in the database instead.
### Expected behavior
- enter an invalid time into the time input of a Datetime field, such as `foobar`
- hit save
- **An error is shown informing about the invalid format of my input. I'd expect the same error as when entering an invalid date: `Please enter a valid date and time in the Foo Bar field`**
- the date & time inputs are unchanged
- reload the page
- **the date& time inputs are reset to the values before editing**
### Actual behavior
- enter an invalid time into the time input of a Datetime field, such as `foobar`
- hit save
- **A message is shown informing about successful saving: `Your changes have been saved successfully`**
- the date & time inputs are unchanged
- reload the page
- **the date & time inputs are set to `1970-01-01 1:00:00 am`**

**Comment by divyabiyani** [comment] 2016-05-21 06:56
@mxstbr Hi,I want to work on this bug.
Could you please help me in telling me from where to start this?

**Comment by mxstbr** [comment] 2016-05-21 07:00
The relevant code is in the `fields/types/DateTime/DateTimeType.js` file, specifically the [`validateInput` function](https://github.com/keystonejs/keystone/blob/master/fields/types/datetime/DatetimeType.js#L66-L75). 

We use the `Date` field `parse` function to validate that we have a correct date, which is in `fields/types/Date/DateType.js` [right here](https://github.com/keystonejs/keystone/blob/master/fields/types/date/DateType.js#L94-L103). This function uses `moment` to parse the date, so there's two possibilities of a bug here: 

- We need to pass `strict` to `return m(value);` in the Date field `parse` method, which might fix this bug

- This is a "bug" (or a feature) of `moment`, in which case we can't fix this.

**Comment by jstockwin** [comment] 2016-05-25 16:09
@geloescht I'm unable to reproduce this on the test server.
![image](https://cloud.githubusercontent.com/assets/8227759/15547377/72b86ef2-229b-11e6-9844-b07dd51078f0.png)

**Comment by geloescht** [comment] 2016-05-25 16:36
@jstockwin you need to enter a valid date and an invalid time. Btw, great work with those those new tests! I am going to tackle one or two tomorrow.

**Comment by jstockwin** [comment] 2016-05-25 16:48
This can now be reproduced on the current master by running
`node test/e2e/server.js --config ./test/e2e/adminUI/nightwatch.json --group test/e2e/adminUI/tests/group999FixMe/2898.js`

When this issue is fixed, please could lines 25-33 and line 45 of the FixMe test file be placed into `group005Fields/testDatetimeField.js` as a new test. This should be the first test that runs (so put it before line 20) and call it 'Datetime field should validate correctly'. You could also repeat this with other invalid inputs to make this a bit more thorough. Similar tests on other fields would also be amazing.

**Comment by geloescht** [comment] 2016-05-28 08:37
@divyabiyani Hi, are you still interested in fixing this bug?

**Comment by export-mike** [comment] 2017-03-22 04:13
This issue no longer seems to be an issue with tests I'm currently adding to keystone with nightmare. Its likely this has been fixed with the significant amount of refactoring on the admin panel since this issue was made. https://github.com/keystonejs/keystone/commit/3847222c7133642eaf47861edd0295d3e99bb18f

**Closed by export-mike** 2017-03-22 04:13 UTC
Labels: bug, reproduced (e2e)
