### ISSUE TITLE
CloudinaryImage field being cleared on Save in Safari

### ISSUE THREAD

**Issue by nathsimpson** [keystonejs/keystone#1967] opened 2019-11-17 00:33 UTC
# Bug report

## Describe the bug
When creating an item in Keystone Admin UI that has a cloudinary image field, the field is cleared when the Save button is pressed.

## To Reproduce
- Log in to a Keystone site using Safari for Mac.
- Go to a list screen in Keystone Admin UI, press the '+' to create a new item.
- The 'sidebar' slides out, fill it out with your information, and upload an image.
- Pressing 'Create item' navigates you to the edit item screen. Image is still there (uploads to cloudnary).
- Press 'Save changes', image is immediately removed from the field, appearing as if it is empty.

## Expected behaviour
Image still exists after pressing 'Save changes'

## Screenshots
![image](https://user-images.githubusercontent.com/12689383/69001127-b26eb700-092d-11ea-8bc0-8b8dab539de2.png)

## System information

- OS: macOS Mojave + Catalina
- Browser: Safari

## Additional context
The website was made for my Dad, who uses Safari as his default browser. Happy to show Thinkmill team the repo if needed.

**Comment by singhArmani** [comment] 2020-02-04 05:04
@nathsimpson, @MadeByMike  : This issue seems to be resolved now. I couldn't reproduced it. Closing it

**Closed** 2020-02-04 05:06 UTC
Labels: bug
