### ISSUE TITLE
DB Create gets called twice on second openDatabaseConnection

### ISSUE THREAD

**Issue by johanjordaan** [keystonejs/keystone#3474] opened 2016-09-12 00:39 UTC
### Steps to reproduce the behavior

Call openDatabaseConnection once (with the 'auto update' flag set') the .on('open'... event gets called once as expected. Then close the database and call openDatabaseConnection again. Now the .on('open'... event gets called twice. I would bet that on the third call it will be called 3 times. The event handler get registered each time the openDatabaseConnection method is called and never cleared out. 
### Expected behavior

I would expect the call .on('open'... event to be called once each time the openDatabaseConnection method is called.
### Actual behavior

The .on('open'... event gets called n+1 times where n is the number of previous calls to openDatabaseConnection.

**Comment by Noviny** [comment] 2017-04-04 04:43
Closing this as the issue is resolved. Thanks again @johanjordaan for the PR.

**Closed by Noviny** 2017-04-04 04:43 UTC
