### ISSUE TITLE
"Template not found: layouts/default.html" using nunjucks

### ISSUE THREAD

**Issue by keith24** [keystonejs/keystone#3857] opened 2017-01-07 02:42 UTC
### Steps to reproduce the behavior

Use yeoman generator to create a new project, choosing nunjucks as templating engine.  

### Expected behavior

Keystone runs.  

### Actual behavior

Keystone can't find `layouts/default.html`.  

I tried setting it with

```javascript
nunjucks.configure('templates');
```

but that didn't work.  Can anyone reproduce this or am I going crazy?

**Comment by robintiwari** [comment] 2017-01-31 04:00
Try this: https://github.com/keystonejs/generator-keystone/issues/181

**Comment by diramazioni** [comment] 2017-03-06 17:13
I don't understand why this issue is closed, that fix was already merged and I see the same exact problem

**Comment by keith24** [comment] 2017-03-07 00:30
That's my bad.  

It looks like it was only [half fixed in the PR](https://github.com/keystonejs/generator-keystone/pull/194#issuecomment-266877585).

**Comment by Noviny** [comment] 2017-03-07 14:57
Hi, this issue is better dealt with over on the [generator repo](https://github.com/keystonejs/generator-keystone) itself, as the issue is with the generator setup.

That being said, we merged a fix in [here](https://github.com/keystonejs/generator-keystone/commit/107dd519f23534c92c422640996f2a18974989d0), and \*should\* be getting a new version published to npm before the end of this week, however you can use master to regenerate the project.

As noted by the change in that commit, the file location needed to be moved so that nunjucks could find it as it expected.

**Closed by Noviny** 2017-03-07 14:57 UTC

**Comment by diramazioni** [comment] 2017-03-07 19:17
yes moving the files worked. I was trying with relative import ../layouts but was not working :+1:
