### ISSUE TITLE
static files not correctly handled in node@5.7

### ISSUE THREAD

**Issue by dracupid** [keystonejs/keystone#2344] opened 2016-02-29 11:10 UTC
When I am using node@5.7, some static files, such as `/keystone/styles/keystone.min.css` can not be accessed correctly. The request to the static file is logged at the terminal, and redirected (HTTP 302) to signin page.
<img width="594" alt="2016-02-29 18 58 53" src="https://cloud.githubusercontent.com/assets/5706703/13392589/84404136-df16-11e5-90fd-aec026060e8b.png">

Both keystone@0.3.x and master reproduce this problem. While node@5.6 works fine.
`npm test` passed, except some lint errors.

Help wanted.

**Comment by victoriafrench** [comment] 2016-02-29 19:26
Duplicate of #2325

**Closed** 2016-03-01 15:36 UTC
