### ISSUE TITLE
Making a Number field Optional is not working

### ISSUE THREAD

**Issue by sparkit** [keystonejs/keystone#1107] opened 2015-02-24 17:50 UTC
required:false is not working any more if we leave a numeric field empty.

var value = this.getValueFromData(data);

the above will be returning an empty string not undefined.

Code base: Master

**Comment by JohnnyEstilles** [comment] 2015-02-25 00:02
Duplicate of issue mentioned in #1098

**Comment by JedWatson** [comment] 2015-02-28 12:23
Fixed, will be released with 0.3.3

**Closed** 2015-02-28 12:23 UTC
