### ISSUE TITLE
Keystone Admin UI not always loading CSS

### ISSUE THREAD

**Issue by ttsirkia** [keystonejs/keystone#1295] opened 2015-04-09 22:13 UTC
I have noticed that often Admin UI does not load CSS files when the Keystone page is loaded for the first time. After refreshing the view, usually it works fine.

Can someone confirm this issue? I have noticed this at least two separate instances. I'm using mainly Firefox and can't say now if I have noticed this with Chrome.

**Comment by SharadKumar** [comment] 2015-04-09 22:41
We witnessed this in production after some changes were made to servers. After troubleshooting it turned out to be permissions issue node_modules path. 

Make sure your read permissions are proper for the web-worker account.

Not sure if you have the same situation though.

**Comment by ttsirkia** [comment] 2015-04-09 22:43
All permissions are OK. It can't be a permission problem because sometimes it works, sometimes not.

**Comment by ttsirkia** [comment] 2015-04-10 21:14
After investigating this a bit more, it seems that this happens typically after the Keystone process has been restarted. So one possibility is that the compiled CSS is not available when the first Admin UI page load occurs but after the compilation it will be there and everything works.

**Comment by JedWatson** [comment] 2015-04-13 12:36
This may have been #1299

**Comment by ttsirkia** [comment] 2015-04-13 17:18
I don't think so because this happens only when the CSS is loaded for the first time. I was trying to debug it more but wasn't able to replicate it today although I haven't updated or changed anything. I report more when I get some results what is happening.

**Comment by JedWatson** [comment] 2015-04-14 00:05
thanks @ttsirkia, let us know when you can replicate it so we can get it fixed :)

**Comment by ttsirkia** [comment] 2015-04-14 07:07
It seems that after the Keystone server is started, the first Admin UI page load will return '500 Internal server error' for the CSS file. After reload everything works and CSS is available.

**Comment by creynders** [comment] 2015-04-14 07:18
@ttsirkia I can't reproduce this _at all_ on a Mac OS X 10.10.2, keystone v0.3.4, with latest FF, chrome, opera, safari.

**Comment by ttsirkia** [comment] 2015-04-14 07:29
I have two different Keystone instances running on two different servers and they both behave like this. It is always reproducible with Firefox and Chrome. However, yesterday I wasn't able to replicate this in my virtual server. I keep investigating what is happening.

**Comment by creynders** [comment] 2015-04-14 07:40
Have you tried outputting the error stack to see what causes the `500`?

**Comment by ttsirkia** [comment] 2015-04-14 07:45
Not actually but I noticed that the server returned my own `500` page. It should have shown the stack trace because I'm logged in as admin but it didn't. So one clue might be that some Admin UI resources are requested before the user is registered with the session. And in my virtual server I'm using the non-production cookies (as Keystone does) for auth which are not use in the real servers so there is at least one difference.

**Comment by ttsirkia** [comment] 2015-04-14 07:50
Or actually, the session is probably never attached to static file requests...

**Comment by ttsirkia** [comment] 2015-04-14 07:58
```
An error occurred:
EACCES, open '/var/www/xxx/node_modules/keystone/public/styles/keystone.min.css'
Error: EACCES, open '/var/www/xxx/node_modules/keystone/public/styles/keystone.min.css'
    at Error (native)
```

So is it reading the minified CSS while it is still being minimized?

**Comment by creynders** [comment] 2015-04-14 08:15
Hmmm, I'm afraid there's not a lot we can do then, since that's handled by `less-middleware`. 
You could try [setting verbose logging in less-middleware](https://github.com/keystonejs/keystone/blob/83b3396da973a3bc0847a8b550cf137b3452ee8f/lib/core/static.js#L16) to see what's happening:

```js
app.use('/keystone', require('less-middleware', {debug:true})(__dirname + path.sep + '..' + path.sep + '..' + path.sep + 'public'));
```

**Comment by creynders** [comment] 2015-04-14 08:18
I think you're right, it's probably a race condition: the less file is still being compiled when the HTML is sent down the wire, it tries to serve the .min.css file, but since it doesn't exist an error is thrown.
Or something like that.

**Comment by JedWatson** [comment] 2015-04-20 01:23
Sounds like we may be better off building this explicitly on server start and just serving the static file than using `less-middleware`... I've been tempted to do this for both the LESS and browserified Javascript for a little while. The middleware approach is nice for development but not production.

**Comment by celiao** [comment] 2015-08-21 22:01
I experienced the same issue.  The first time I accessed my server, the javascript formatting was missing from my home page and I received the message:
```
GET / 304 175.610 ms
Error thrown for request: /styles/site.min.css
Error: EACCES, open '/var/www/xxx/public/styles/site.min.css' at Error (native)
```
When I refreshed my browser, the proper javascript was displayed.

**Comment by yusiswtor** [comment] 2015-09-05 21:43
Im having this issue, but not being solved by reloading the page:
GET / 304 256.791 ms
Error thrown for request: /styles/site.min.css
Error: EACCES, open '/var/www/test/my-site/public/styles/site.min.css'
GET / 304 4.826 ms
GET /keystone/ 302 8.375 ms
GET /keystone/signin 200 178.421 ms
Error thrown for request: /keystone/styles/auth.min.css
Error: EACCES, open '/var/www/test/my-site/node_modules/keystone/admin/public/styles/auth.min.css'
POST /keystone/signin 302 1235.310 ms
GET /keystone/ 200 779.107 ms
Error thrown for request: /keystone/styles/keystone.min.css
Error: EACCES, open '/var/www/test/my-site/node_modules/keystone/admin/public/styles/keystone.min.css'

**Comment by jorisw** [comment] 2015-11-17 08:57
Same here on OS X 10.11.1 with Node 4.0.0, only my `site.css` just loads forever, and my browser hence never finishes loading the page. Also, this is not just the admin, but `/` too, after first install of Keystone.

My project is configured to use sass instead of less, and `lib-sass` as some of you may know is a major [PITA](http://stackoverflow.com/questions/29461831/libsass-bindings-not-found-when-using-node-sass-in-nodejs) w.r.t. installing and building, so I kind of suspect `lib-sass` to be the problem in my case.

**Comment by jorisw** [comment] 2015-11-17 09:03
Yeah, so switching to LESS fixes the issue for me rightaway (replace `sass` with `less` in `keystone.js`).

**Comment by jacargentina** [comment] 2016-02-25 11:20
I've found the paths passed in `createStaticRouter.js` are invalid.

Fix in my own fork here: https://github.com/jacargentina/keystone/commit/d656e30ec8e9211bb73dc819e11746b998fededb

The directories are wrong, less was looking for the .less files in (for example):

`/public/styles/keystone.less` but it must look for them in `/admin/public/styles/keystone.less`

They are up three levels `__dirname + '../../../public/styles'`, but should be just two __dirname + '../../public/styles'

Sorry, i'm too lazy right now to make the PR. Hope this also fixes #2325 ?

**Comment by ttsirkia** [comment] 2016-02-25 11:34
@jacargentina If this is the case, why reloading the admin page fixes the issue?

**Comment by jacargentina** [comment] 2016-02-25 11:41
@ttsirkia Are you sure reloading _fixes_ really the issue? Not in my case.
The bug is simply as i've pointed out.
Now i've added one more commit (i was missing an / at the start of each path)

**Comment by ttsirkia** [comment] 2016-02-25 11:47
@jacargentina I'm sure. This ticket is about a problem that prevents CSS loading for the first time when the Keystone process has been started. After refreshing the page, everything works. This affects versions up to 0.3.16.

**Comment by jacargentina** [comment] 2016-02-25 12:20
Ahhh, sorry. My patch is for 0.4 (current master). But i can take a look at the code on v0.3.16 to help you.

**Comment by jacargentina** [comment] 2016-02-25 12:30
I'm just guessing as i dont have a testing instance running 0.3.x. U can help to check my guess on your instance: try changing file `admin/app/static.js` at line 45/46.

````javascript
router.use('/styles', less(__dirname + '../../public/styles', lessOptions));
router.use(express.static(__dirname + '../../public'));
````

should be:

````javascript
router.use('/styles', less(__dirname + '/../../public/styles', lessOptions));
router.use(express.static(__dirname + '/../../public'));
````

**Comment by ttsirkia** [comment] 2016-02-25 12:32
This cannot be the solution because otherwise it would be broken all the time. The issue here is that the LESS process is still running when the admin page loaded for the first time and therefore the CSS files are not available. There is kind of race condition which causes this. It is not related to any paths.

**Comment by tinganho** [comment] 2016-03-09 07:54
I can confirm that downgrading to `npm@2.14.9` works and then reinstall everything.

@jacargentina I also tried your solution it doesn't work for me.

**Comment by mxstbr** [comment] 2016-08-25 02:24
This is definitely fixed in `master`, I've been clicking around and opening it like a maniac for the past weeks and have never had this happen.

Closing for now, let us know if this is still happening for you with the newest version!

**Closed by mxstbr** 2016-08-25 02:24 UTC
Labels: bug
