### ISSUE TITLE
node keystone is giving this error in windows 

### ISSUE THREAD

**Issue by ravi100k** [keystonejs/keystone#3982] opened 2017-02-08 21:43 UTC
```
H:\hybrid\ReactLearning\acme>node keystone.js
Error: %1 is not a valid Win32 application.
\\?\H:\hybrid\ReactLearning\acme\node_modules\bson\build\Release\bson.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\hybrid\ReactLearning\acme\node_modules\bson\ext\in
dex.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\hybrid\ReactLearning\acme\node_modules\bson\lib\bs
on\index.js:3:24)
js-bson: Failed to load c++ bson extension, using pure JS version
H:\hybrid\ReactLearning\acme\node_modules\keystone\lib\core\mount.js:330
                                throw e;
                                ^

Error: ENOENT: no such file or directory, scandir 'H:\hybrid\ReactLearning\acme\
node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (H:\hybrid\ReactLearning\acme\node_modules\no
de-sass\lib\extensions.js:121:13)
    at foundBinariesList (H:\hybrid\ReactLearning\acme\node_modules\node-sass\li
b\errors.js:20:15)
    at foundBinaries (H:\hybrid\ReactLearning\acme\node_modules\node-sass\lib\er
rors.js:15:5)
    at Object.module.exports.missingBinary (H:\hybrid\ReactLearning\acme\node_mo
dules\node-sass\lib\errors.js:45:5)
    at module.exports (H:\hybrid\ReactLearning\acme\node_modules\node-sass\lib\b
inding.js:15:30)
    at Object.<anonymous> (H:\hybrid\ReactLearning\acme\node_modules\node-sass\l
ib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\hybrid\ReactLearning\acme\node_modules\node-sass-m
iddleware\middleware.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

H:\hybrid\ReactLearning\acme>
```

**Comment by bassjacob** [comment] 2017-02-08 22:20
I don't have a windows machine, but it looks like the node-sass binaries might be busted on your machine. Can you try running `npm rebuild node-sass` and see what happens?

@jstockwin or @webteckie have you seen this before?

**Comment by jstockwin** [comment] 2017-02-08 22:26
I've not seen this, no

**Comment by ravi100k** [comment] 2017-02-09 05:51
The error is still the same, and the binary is fine.

Error: %1 is not a valid Win32 application.

**Comment by ravi100k** [comment] 2017-02-09 06:02
in Linux machine the error is:
 
Error: /vagrant/ReactLearning/acme/node_modules/bson/build/Release/bson.node: invalid ELF header

**Comment by bassjacob** [comment] 2017-02-09 06:46
I've not seen this error before, but does it seem like this thread is related? https://github.com/mongodb/js-bson/issues/58

**Comment by ravi100k** [comment] 2017-02-09 15:11
the keystone is working properly with this error.

**Comment by o2nitin** [comment] 2017-02-09 15:31
Hi folks,
The same error was showing to me on my windows machine.
It's actually a warning [click here](https://github.com/Automattic/mongoose/issues/3436) for more information.

**Comment by Noviny** [comment] 2017-10-02 22:30
As we've been struggling to reproduce this, closing this issue. If you have a reoproducible case, please let us know and we'll dig into it.

**Closed by Noviny** 2017-10-02 22:30 UTC
Labels: needs reproduction
