### ISSUE TITLE
Problems to manage DateTime scalar types in virtual fields or custom resolver

### ISSUE THREAD

**Issue by wegorich** [keystonejs/keystone#8083] opened 2022-11-08 13:49 UTC
When I make custom resolver for example:

```
    typeDefs: `type Mutation {
        getMyPost(postId: String!): Post;
    }`,
    resolvers: {
        Mutation: {
           getMyPost: async (obj, query, context) => {
               let post = await context.sudo().query.User.findOne({
                          where: { id: query.postId },
                          query: 'id createdAt',
              });
              return post;
          }
     }
 }         
```

Where the Post:

```
export const Post = list({
    fields: {
        createdAt: timestamp({
            defaultValue: {
                kind: 'now',
            }
        }),
     }
});
```

The result is: 
```
Unexpected value provided to DateTime scalar: 2022-11-03T13:32:43.329Z
```

The problem is, in resolver post object createdAt is a string. But scalar DateTime trying serialise the field by using the string input not supported by the code: 

https://github.com/keystonejs/keystone/blob/ad54ef340ee6d13f4ebdebcce1363ddb98b4f5e1/packages/core/src/types/schema/graphql-ts-schema.ts#L238

I checked the same DateTime scalar realisation at the guild project: 

https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/iso-date/DateTime.ts#L22 

they just double check is the string a date, for that case.

While researching couple ideas:
- just fix
- having possibilities to override the Keystone scalar times on top.

**Comment by borisno2** [comment] 2022-12-19 21:52
Hi @wegorich Thanks for posting. 
When you use the keystone-generated GraphQL type, in your case `Post`, if your custom resolvers like 
```ts
getMyPost(postId: String!): Post;
``` 
You will need to use `context.db` instead of `context.query`. The problem is using `context.query` it two fold, firstly, as you have found, it will return the date as a string and GraphQL will not be happy, secondly it will only return what you put in the `query` so the GraphQL schema will say you can fetch everything on the `Post` but it will again error if you try to get anything other than that in your `query`.

So you have two options:
- return the `context.db` ie:
```ts
    typeDefs: `type Mutation {
        getMyPost(postId: String!): Post;
    }`,
    resolvers: {
        Mutation: {
           getMyPost: async (obj, query, context) => {
               let post = await context.sudo().db.User.findOne({
                          where: { id: query.postId },
              return post;
          }
     }
 } 
```
Or add your own custom Type for this `mutation` - you can see an example of adding an extra type using `mergeSchema` from `@graphql-tools/schema` in our example here https://github.com/keystonejs/keystone/tree/main/examples/extend-graphql-schema-graphql-tools where a new type of `Statistics` is added to a `Query` called `stats`

**Comment by borisno2** [comment] 2023-01-10 02:50
Hey @wegorich I am going to close this issue now, feel free to reopen if there is still an issue

**Closed by borisno2** 2023-01-10 02:50 UTC
