### ISSUE TITLE
Model defaultFilters

### ISSUE THREAD

**Issue by emaddoma** [keystonejs/keystone#2568] opened 2016-04-02 21:50 UTC
Thought it might be cool if it were possible to set default filters for the Admin UI on a model.

```
var MyModel = new keystone.List('MyModel', {
    defaultFilters: [
        {
            fieldName: 'value'
        }
    ]
});
```

**Comment by meelis79** [comment] 2016-04-08 10:51
+1 we need this functionality

I would suggest it like this:
defaultFilters: { fieldName: 'value', otherField: true}

I also need "not null" and ''null" type filter, so I can use default filter lockedDate: ''null"

**Comment by mxstbr** [comment] 2016-04-08 11:30
Closing as a duplicate of #741, thanks for notifying us @meelis79! We'll look into adding this!

**Closed by mxstbr** 2016-04-08 11:30 UTC
