### ISSUE TITLE
Post created, but fails to show details

### ISSUE THREAD

**Issue by ihorskyi** [keystonejs/keystone#3649] opened 2016-10-29 14:28 UTC
I Created a post on http://demo.keystonejs.com (Post 2)
It is visible in list here http://demo.keystonejs.com/blog

But when I go to details http://demo.keystonejs.com/blog/post/post-2 it says: **"Sorry, an error occurred loading the page (500)"**

**Comment by jstockwin** [comment] 2016-12-11 13:01
This is a problem with the demo site, and not a general problem with keystone itself, so should be logged against that repository. 

In fact, I think this is a duplicate of https://github.com/keystonejs/keystone-demo/issues/62

**Closed by jstockwin** 2016-12-11 13:01 UTC
