### ISSUE TITLE
Search box disappears after not founding something

### ISSUE THREAD

**Issue by ellipticaldoor** [keystonejs/keystone#3260] opened 2016-08-02 11:40 UTC
When I'm on the admin and I search something and it's not found if I delete my search query the search box disappears.

**Comment by mxstbr** [comment] 2016-08-02 12:51
Are you on the latest `npm` version or `master`?

**Comment by ellipticaldoor** [comment] 2016-08-02 21:41
I did this for installing keystone:

```
git clone https://github.com/keystonejs/keystone
cd keystone
yo keystone
npm i keystonejs/keystone
```

right now I'm on the master branch

**Comment by wmertens** [comment] 2016-08-03 09:24
This is a duplicate of #3117

**Closed by wmertens** 2016-08-03 09:24 UTC
Labels: bug
