### ISSUE TITLE
Invalid `uuid` is breaking relationship filters when using postgresql 

### ISSUE THREAD

**Issue by skindc** [keystonejs/keystone#8884] opened 2023-11-03 07:18 UTC
I am currently trying to upgrade including core@5.6.0
There is now a bug in RelationshipSelect where on entering text to filter the related items the UI breaks and just displays 'Error'

To replicate:
As far as I can see all my relationships that use the 'select' ui option, therefore I am presuming this affects all relationship fields.

Expected:
When I type any value into the input field of RelationShip select I expect it to filter the dropdown list by filtering the `search fields` defined in the relationship or the related item.

<img width="447" alt="image" src="https://github.com/keystonejs/keystone/assets/73968/3048225c-0b98-4523-9391-eca2ce2f82fb">
<img width="477" alt="image" src="https://github.com/keystonejs/keystone/assets/73968/8a0a24a5-76cc-4a9e-b007-3d0d7a00f606">

I have done some investigation into this.

When attempting to debug this I watched the network panel of developer tools in chrome to see if there was a Graphql Error reported. In fact there was.

The response from the RelationshipQuery when entering the filter reported the error below.

```json
        {
            "message": "Prisma error: Inconsistent column data: Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `g` at 1",
            "locations": [
                {
                    "line": 7,
                    "column": 3
                }
            ],
            "path": [
                "count"
            ],
            "extensions": {
                "code": "KS_PRISMA_ERROR",
                "prisma": {
                    "name": "PrismaClientKnownRequestError",
                    "code": "P2023",
                    "clientVersion": "4.16.2",
                    "meta": {
                        "message": "Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `g` at 1"
                    }
                },
                "stacktrace": [
                    "GraphQLError: Prisma error: Inconsistent column data: Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `g` at 1",
                    "    at Object.prismaError (/Users/skin/Projects/activeProjects/Lokalliving/lokalliving-stack/apps/keystone6/node_modules/@keystone-6/core/dist/graphql-errors-f1c235e2.cjs.dev.js:43:10)",
                    "    at runWithPrisma (/Users/skin/Projects/activeProjects/Lokalliving/lokalliving-stack/apps/keystone6/node_modules/@keystone-6/core/dist/config-e832ee3f.cjs.dev.js:37:25)",
                    "    at async Object.count (/Users/skin/Projects/activeProjects/Lokalliving/lokalliving-stack/apps/keystone6/node_modules/@keystone-6/core/dist/config-e832ee3f.cjs.dev.js:821:17)"
                ]
            }
        },
```
You can see that is complaining about the letter 'g', of which is what I typed into the UI input could not be used to construct a UUID. I believed this was because despite the 'id' not being in my defined search fields that the `where` statement was including a comparitor  for the id from the my input. I inspected the query to prove this correct and yes it was indeed.

```json
{
  "operationName": "RelationshipSelect",
  "variables": {
      "where": {
          "OR": [
              {
                  "id": {
                      "equals": "g"
                  }
              },
              {
                  "id": {
                      "equals": "g"
                  }
              },
              {
                  "name": {
                      "contains": "g",
                      "mode": "insensitive"
                  }
              },
              {
                  "email": {
                      "contains": "g",
                      "mode": "insensitive"
                  }
              },
              {
                  "contactNumber": {
                      "contains": "g",
                      "mode": "insensitive"
                  }
              },
              {
                  "notes": {
                      "contains": "g",
                      "mode": "insensitive"
                  }
              }
          ]
      },
      "take": 10,
      "skip": 0
  },
  "query": "query RelationshipSelect($where: ContactWhereInput!, $take: Int!, $skip: Int!) {\n  items: contacts(where: $where, take: $take, skip: $skip) {\n    ____id____: id\n    ____label____: name\n    __typename\n  }\n  count: contactsCount(where: $where)\n}"
}
```

I believe this could have possibly been introduced in commit 27a8933 when the `useFilter` function in RelationshipSelect View was changed.

**Comment by skindc** [comment] 2023-11-03 07:46
I have just rolled back one release at a time and the last release of core where this seems to operate as expected is `5.3.2`

**Comment by dcousens** [comment] 2023-11-05 03:39
I haven't seen this in my own projects, but I'll try and replicate this soon

**Comment by klemola** [comment] 2023-11-09 13:25
I can verify that this happens to us too, exactly in the same way as the for @skindc .

Additionally, this has broken search in lists in the admin UI: 

<img width="1162" alt="Screenshot 2023-11-09 at 15 23 46" src="https://github.com/keystonejs/keystone/assets/1923450/b8688e4f-6e3a-485d-afd5-bcc1b8075e3b">

Same root cause: the letters in my search query are assumed to be part of an uuid by Prisma, and therefore the search fails.

We are on core v5.7.0.

**Comment by skindc** [comment] 2023-11-18 07:59
Hey, any news on this? Maybe something I could help with when I get a minute.

**Comment by klemola** [comment] 2024-01-04 07:02
I'm also curious about a potential fix to this issue. Ping @jsaarest, you should subscribe to be notified of any resolution!

**Comment by esaruoho** [comment] 2024-01-17 20:26
any progress on this issue? we're meeting it consistently

**Comment by dcousens** [comment] 2024-01-17 23:05
Can someone provide a minimum reproducible example?

**Comment by klemola** [comment] 2024-01-22 07:48
@dcousens Here you go, repro:

https://github.com/klemola/keystone-id-bug-repro

While building the repro I noticed few things:

- Only happens with `idField: { kind: "uuid" }`
- Only happens with postgres - works with sqlite, even using `uuid()` instead of `cuid()`

About the repro: 
I wanted to include the base setup we have, with auth and all. 
Requires Postgres, I added a docker-compose.yml for easy setup - it also shows the example DB config.

Also ping @jsaarest

**Comment by skindc** [comment] 2024-02-16 03:26
@klemola Thank you for submitting this sample, I just havn't had time.

**Comment by gautamsi** [comment] 2024-02-23 21:20
you can generate uuid yourself if you set `kind: 'string'`

**Comment by fkrauthan** [comment] 2024-05-02 00:34
Any progress here? I would love to update to latest version to be finally able to use node 20

@gautamsi how would you configure that `kind: 'string'` and then have a custom generation code in keystone?

**Comment by dcousens** [comment] 2024-05-02 12:20
@fkrauthan please see https://github.com/keystonejs/keystone/blob/bd33f0785da2301ec6ff1e7e6ec3a135d6a3cd4c/examples/custom-id/schema.ts#L33-L51

**Comment by fkrauthan** [comment] 2024-05-02 19:00
Ah yeah, unfortunately that changes the id field in the database (for existing data). To me the issue seem to be as "simple" as currently when using free text search (on dropdown and/or the admin list page) keystone just assembles a query for all searchable columns and adds the value entered. However it seems like that prisma got more strict if you have a UUID column. So what probably needs to change is that if you search for a value and the field is a UUID field (e.g. id) and the entered value is not a valid UUID to skip passing it into the query. That would solve that issue I believe.

I tried looking a bit into the code-base but couldn't really find the place where that search would be translated to individual queries.

**Comment by Arithmetics** [comment] 2024-07-27 03:34
should this be closed as solved?

**Closed** 2024-07-27 13:14 UTC
Labels: 🐛 bug
