### ISSUE TITLE
Types.Url does not validate

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone#2704] opened 2016-04-28 11:24 UTC
Raised while adding e2e field tests for urls [here](https://github.com/keystonejs/keystone/pull/2702). 

A url field allows the text "Url Field Test 1", which is most certainly _not_ a url.

**Comment by mxstbr** [comment] 2016-04-28 14:02
The URL field has the same validation as the text field. There is a `// TODO` [in the code](https://github.com/keystonejs/keystone/blob/master/fields/types/url/UrlType.js#L19-L23), but we're not sure adding complex URL validation logic is worth it.

I'll close this for now, because this is intended behaviour currently!

**Closed by mxstbr** 2016-04-28 14:02 UTC

**Comment by jstockwin** [comment] 2016-04-28 14:04
@mxstbr thanks for clarifying, and fair enough. This appears to be the same across multiple fields, i.e. the color field accepts "That's not how you spell colour" as an input, even though this isn't a valid format.

**Comment by mxstbr** [comment] 2016-04-28 14:11
Yessir, we're not very strict with validation. We'd probably accept a PR to change that, but I think our efforts are better spent on getting bigger things in at the moment :blush:
