### ISSUE TITLE
defaultValue function values possibly broken

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone#2043] opened 2019-12-05 06:31 UTC
# Bug report

## Describe the bug

Ok, so the docs say fields can take a `defaultValue` key as a string or function. Strings work fine, but I can't seem to get functions to do anything at all.

I notice they aren't passed to the Admin UI, so it makes sense they wouldn't resolve and display when creating an item, but even if you simply save a field with no value the `defaultValue` function is never called.

Testing using this config in the TODO demo:
```js
keystone.createList('Todo', {
  schemaDoc: 'A list of things which need to be done',
  fields: {
    name: {
      type: Text,
      schemaDoc: 'This is the thing you need to do',
      isRequired: true,
      defaultValue: () => { return 'test text' },
    },
  },
});
```

`List._resolveDefaults` is where I would expect the default function to be resolved server-side, but `getDefaultValue` is only called for `id` since `name` has a `null` value already.

**Comment by MadeByMike** [comment] 2019-12-11 01:01
So I did a complete investigation of this and have concluded that it is not a bug.

The `getAdminMeta` function is executed at build time and generates a JSON blob that is passed to the AdminUI. I could resolve the function at build time but if that is possible it might as well be a string. This is how data is passed from Keystone configuration to the AdminUI.

This means that data can pretty much only be scalar data types and not functions or other complex types. There are a few exceptions to this including field views and pages. For these to work they need to be separate files and they are imported via an `importView` (which does a bunch of complex and magic stuff not worth mentioning here) and results in functions built and packaged for use in the front-end.

This is not a good API if you want to intersperse bits of configuration for the Admin UI amongst the list and field configurations.

```keystone.createList('Todo', {
  schemaDoc: 'A list of things which need to be done',
  fields: {
    name: {
      type: Text,
      schemaDoc: 'This is the thing you need to do',
      isRequired: true,
      defaultValue: importViews(`./path-to-some-function-with-default-export`),
    },
  },
});
```   
Not only that, it requires a bunch of work to implement each time we want to do it. That why I'm moving towards a single configuration file for the Admin UI via hooks:

```
const adminApp = new AdminUIApp({
  hooks: require.resolve('./admin-ui/')
});
```

I think hooks is the correct API in future for any customisation of the Admin UI that needs to occur at runtime. In the index file for hooks we export a configuration:

```
import CustomDashboard from './dashboard';

export default {
  pages: () => [
    {
      label: 'A new dashboard',
      path: '',
      component: CustomDashboard,
    }
  ],
}
```

Currently we only have hooks for pages, but we could have a hook that override values for field defaults and even allows the field configuration to specify the name of this: 

`./admin-ui/index.js`
```

export default {
  myDefaultValueKey: async () => {
    return 'Anything'
  }
}
```

`./index.js`
```
keystone.createList('Todo', {
  fields: {
    name: {
      type: Text,
      isRequired: true,
      defaultValueHookName: 'myDefaultValueKey'
    },
  },
});
```

**Closed** 2019-12-11 05:08 UTC

**Comment by Vultraz** [comment] 2020-02-21 12:24
So, not sure if this is at all relevant, but I just discovered something related to this completely by accident. If [this](https://github.com/keystonejs/keystone/blob/master/packages/app-admin-ui/client/components/CreateItemModal.js#L75) line passes an empty object as the `data` variable to `createItem` (which is the mutation setter), like so:
```js
createItem({ variables: { data: {} } })
```
the default value function in my first post just... works. Just like that. 🤔

**Comment by reubano** [comment] 2020-02-23 17:55
Not sure why this isn't considered a bug. So should the docs be updated to say that `defaultValue` can only be a scalar?

**Comment by reubano** [comment] 2020-02-23 20:07
@MadeByMike this [`importView`](https://github.com/keystonejs/keystone/blob/master/packages/build-field-types/src/index.js)? It seems all it does is return a string to the full path.

**Comment by reubano** [comment] 2020-02-23 20:54
@Vultraz can you post a fully working example? Thanks!

**Comment by Vultraz** [comment] 2020-03-19 07:17
@reubano Sorry, I didn't see this earlier! I don't really have a working example, since I only discovered it worked with a random change to the Admin UI internals.

**Comment by mbrowne** [comment] 2021-01-05 04:32
For me, a function as a default value simply doesn't work at all, no matter whether it's a required field or not. For example, this has no effect:

```js
        foo: {
            type: Integer,
            defaultValue: () => 123,
        }
```

But this works:

```js
        foo: {
            type: Integer,
            defaultValue: 123,
        }
```

**Comment by mbrowne** [comment] 2021-01-06 16:40
I discovered a workaround using custom fields. Here's how it works in case anyone else is interested... you can create a custom field type that extends an existing field type, and change only the way it obtains the default value. Custom fields are explained here:
https://www.keystonejs.com/tutorials/custom-fields

My field definition looks like this:
```js
import { Integer } from '@keystonejs/fields'

export default {
    ...Integer,
    type: 'IntegerWithCustomDefault',
    views: {
        ...Integer.views,
        Controller: require.resolve('./views/Controller.js'),
    },
}
```

And the Controller for my custom field type looks like this:

```js
import IntegerController from '@keystonejs/fields/types/Integer/views/Controller'

export default class IntegerWithCustomDefaultController extends IntegerController {
    constructor(config, ...args) {
        const defaultValue = // logic to obtain custom default value...
        super({ ...config, defaultValue }, ...args)
    }
}
```

**Comment by famel** [comment] 2021-01-10 12:21
Hi all,

**Comment by mbrowne** [comment] 2021-01-10 12:36
@famel 
> Hi all, what is the final status with default values with functions? Is it still not working?

I am not one of the maintainers of this repo, but from reading the source code it appears that the feature is no longer supported but the docs weren't updated to reflect that. In any case, if passing a function for `defaultValue` still does anything at all, it would be something that doesn't apply to the admin UI, because it's explicitly mentioned in a comment that only static values (not functions) can be received as default values by the admin UI.

**Comment by famel** [comment] 2021-01-11 19:49
Thanx - it seems so
