### ISSUE TITLE
Search bar in UI Admin List view doesn't work

### ISSUE THREAD

**Issue by justintemps** [keystonejs/keystone#2613] opened 2020-03-31 08:05 UTC
# Bug report

## Describe the bug

The Search component in the UI Admin List View is unresponsive. When user attempts to interact with it, React throws the following error:

```
Warning: Cannot update a component (`Search`) while rendering a different component (`Search`).
To locate the bad setState() call inside `Search`, follow the stack trace as described in
https://fb.me/setstate-in-render
```

## System information

This happens on MacOS Catalina Chrome. Current Keystone installs look like this

```
"@keystonejs/adapter-mongoose": "^5.2.1",
"@keystonejs/app-admin-ui": "^5.9.2",
"@keystonejs/app-graphql": "^5.1.2",
"@keystonejs/auth-password": "^5.1.2",
"@keystonejs/fields": "^7.0.0",
"@keystonejs/keystone": "^6.0.1",
```

**Comment by Vultraz** [comment] 2020-03-31 08:19
Duplicate of #2419 I think.

**Comment by justintemps** [comment] 2020-03-31 12:22
@Vultraz That seems likely. Do you want me to close this? Slightly different error message here than in #2419 specifically as it relates to the <Search /> component.

**Comment by Vultraz** [comment] 2020-04-01 13:57
Ok, apparently the second warning ("Cannot update a component from inside...") was introduced in React 16.13.0. I've tracked it down to the `useQuery` call in `useListQuery`... Investigating. Turns out it's a separate issue from the Tooltip one, so leave this open for the Search problem.

**Comment by Vultraz** [comment] 2020-04-01 19:11
Relevant: https://github.com/apollographql/react-apollo/issues/3863

**Comment by Vultraz** [comment] 2020-04-02 03:34
The more detailed error with React 16.13.1.
![image](https://user-images.githubusercontent.com/3558659/78208013-0817ba80-74ef-11ea-8e36-64c259fbf2a8.png)

**Closed** 2020-05-05 01:30 UTC
