### ISSUE TITLE
Support TimeOfDay field type

### ISSUE THREAD

**Issue by tinganho** [keystonejs/keystone#1453] opened 2015-06-09 06:10 UTC
Can't really do opening hours correctly right now for a client website.

```
Mon-Fri 10am - 22pm
Sat 10am - 23pm  
```

**Comment by WingedToaster** [comment] 2015-06-09 12:54
+1
Should we try to find a good time picker ui to use for this? This one seems decent...any others?
http://jquense.github.io/react-widgets/docs/#/datetime-picker

I'm not a big fan of this one...takes too many clicks to get the time that you want.
http://zippyui.com/react-time-picker/

**Comment by tinganho** [comment] 2015-06-10 14:14
Maybe also have TimeOfDayRange as well. That support start and end time.

**Comment by ppiekarczyk** [comment] 2015-06-22 16:00
@WingedToaster if you are talking about an Admin UI, that will be taken care of via Elemental
http://elemental-ui.com/date-picker

It's just a matter of implementing a solution :)

**Comment by ttsirkia** [comment] 2015-06-26 21:49
This is kind of same as in #1171

**Comment by mxstbr** [comment] 2016-03-21 01:00
Closing as a duplicate of #1171, thanks very much for notifying us of the need for this field type, we'll take a look!

**Closed by mxstbr** 2016-03-21 01:00 UTC
