### ISSUE TITLE
Can Select multiple?

### ISSUE THREAD

**Issue by arthurtalkgoal** [keystonejs/keystone#1318] opened 2015-04-19 14:31 UTC
Hi, I tried to have multiple Select Field in admin UI but failed. 

I tried to add ```multiple: true```, or ```many: true``` to my ```type: Types.Select``` model fields.

Is multiple Select allowed in Admin UI?

**Comment by creynders** [comment] 2015-04-23 07:13
@arthurtalkgoal I don't think that's supported ATM. Closing this as a duplicate of #12

**Closed by creynders** 2015-04-23 07:13 UTC
Labels: (status) invalid / duplicate

**Comment by akoesnan** [comment] 2015-05-21 15:14
@creynders  do you know what is needed to support hits?

**Comment by morenoh149** [comment] 2015-05-21 18:29
@akoesnan we need support for user defined fieldTypes. We're not there yet. If you'd like to join our slack to discuss let me know.

**Comment by akoesnan** [comment] 2015-05-24 18:43
@morenoh149  What is the slack for keystonejs?

**Comment by morenoh149** [comment] 2015-05-26 17:52
@akoesnan https://keystonejs.slack.com/ pm me your email and I'll add you
